### ISSUE TITLE
browser pop-up does not close on script if the browser is minimized

### ISSUE THREAD

**Issue by iptvcld** [thomasloven/hass-browser_mod#104]
browser pop-up does not close on script if the browser is minimized, it only closes on automation when the browser is in focus.

**Comment by KTibow** [comment]
What version are you using? If the websocket auto-disconnected because it was out of focus for >5 minutes, you can disable that in the profile page.

**Comment by iptvcld** [comment]
Thanks, I am on the latest. But it self closes now.

**Comment by KTibow** [comment]
If it's fixed, mind closing so there aren't 53 open issues? Thanks!
