### ISSUE TITLE
Issues using MS Edge

### ISSUE THREAD

**Issue by DeadEnded** [thomasloven/hass-browser_mod#109]
I am trying to setup the browser mod in multiple browsers on multiple devices.
So far everything appears to be working except MS Edge.
I was able to use the console to get the deviceID, but the `browser_mod.debug` service still doesn't seem to display anything in MS Edge, and the browser does not appear in the dev tools - states current entities list either.

Is there a known issue with MS Edge?
I searched the issues list and didn't find anything.
Or is there something special that needs to be done for MS Edge?

Thanks!
DeadEnd

**Comment by KTibow** [comment]
I have this working. Try updating:
- Home Assistant
- browser-mod
- Microsoft Edge

and see if you still have this problem.

**Comment by DeadEnded** [comment]
Seems to be working now.
Thanks!
