### ISSUE TITLE
Feature Request - Webcam Access

### ISSUE THREAD

**Issue by K4ds3** [thomasloven/hass-browser_mod#11]
Hey, it would be awesome if you could use the device's webcam as a camera entity in home-assistant!

**Comment by thomasloven** [comment]
That can't be done generally.
Browser_mod uses the abilities of your browser, and it would be a *very* bad thing if websites could access your webcam.

However, you may want to check out [Fully Kiosk Browser](https://www.ozerov.de/fully-kiosk-browser/).

**Comment by K4ds3** [comment]
> Browser_mod uses the abilities of your browser, and it would be a _very_ bad thing if websites could access your webcam.

You can access the user's webcam by using the [MediaDevices API](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices) in JavaScript. All major browsers should support this feature

**Comment by thomasloven** [comment]
Thanks for the hint. I'll look into this.

**Comment by thomasloven** [comment]
Wow.
Thanks a lot! https://github.com/thomasloven/hass-browser_mod/releases/tag/11
