### ISSUE TITLE
Add overflow:hidden to body when popup is opened (and remove it when closed)

### ISSUE THREAD

**Issue by septeven** [thomasloven/hass-browser_mod#110]
Hi Thomas,
In order to not have the background scrolling when a popup is opened (which is not user-friendly at all), would you mind adding an overflow:hidden to the body when a popup is opened, and remove it when it's closed ?

Thanks,

**Comment by KTibow** [comment]
What do you mean? Mind sharing a screenshot/screen recording?

**Comment by septeven** [comment]
I was talking about the CSS rule `overflow:hidden` since I was experiencing the whole body of lovelace interface (I'm talking about html tag here) to scroll up and down when a popup was opened. Anyway, it seems to not happening anymore, though I don't know why but I haven't noticed it since a bit, so I'm closing it for now.

Thanks anyway
