### ISSUE TITLE
problem with variable deviceid 

### ISSUE THREAD

**Issue by UnclePhil** [thomasloven/hass-browser_mod#111]
Hello, i've a problem  to obtain a fixed deviceid on one of my dashboard because it's based on RPI and balena.io software (balena_dash project).
The balena start a WPE docker container, and at each start of these, the deviceid change and all automation are HS
 
Is it possible to fix the discover of the deviceid with an environment variable ??
Ex: if BROWSER_MOD_DEVID exist, we use this one , if not, we use the standard one.

I cannot find (for the moment) where the deviceid is created but if i have the js code i can do that in10 min

Best regards

Ph Koenig

**Comment by thomasloven** [comment]
Unfortunately, the frontend is sandboxed from the machine it runs on and can't access anything locally, such as env variables, that it didn't put there itself.

**Comment by UnclePhil** [comment]
Even if we put the Environment variable on the frontend machine ???
that's more my idea.
The javascript on the front-end read a local , fixed variable.

**Comment by thomasloven** [comment]
Even then. Browsers are entirely sandboxed. Pretty much the only thing the webpage gets to know about the computer it is displayed on is how big the browser window is.
Any more and you'd have a potential security hole - I for one would *not* want any website I visit to be able to read the contents of e.g. my `SSH_CLIENT`, not to mention the various application and encryption keys that are commonly stored in env variables for server software...

**Comment by UnclePhil** [comment]
That's partially true if you are working with "big" /Grand Public/  browser, and even there, i've done some configuration where an local environment variable can impact the content of a page.
But specifically WPE  used in the balena.io dash image is completely  Env driven, So in this case we can do whatever we need.
I'm going to make some patch in my test environment to test it on my side
But be sure, I agree totally with you for the security side on "standard" browser for standard usage

**Comment by thomasloven** [comment]
How about this? https://github.com/thomasloven/hass-browser_mod/releases/tag/1.1.6

**Comment by UnclePhil** [comment]
I'm going to test this during the weekend, but the idea seems good

**Comment by UnclePhil** [comment]
This is working perfectly !!!

Many thanks'

Best regards .
Phiippe
