### ISSUE TITLE
Devices not loading until page (re)loads since 0.111

### ISSUE THREAD

**Issue by kbrohkahn** [thomasloven/hass-browser_mod#113]
I am using a tablet as a dashboard and have the "light" entity displayed on the home screen as a button. When HA restarts, the entity does not load and 1 of 2 errors will show:

  - "HA is starting, not everything may be available yet"
  - "entity 'light.XXX' is unavailable"

And these errors will show for the button until I refresh the page / navigate to a different page on the tablet. I could write a script to refresh the page every minute or so, but HA does not load any of the tablet's Browser Mod entities until a page (re)load occurs. I think this has been occurring since 0.111 when the frontend started before loading all the integrations, though I'm not sure exactly how Browser Mod was affected by this change.

**Comment by KTibow** [comment]
This is unrelated to browser-mod. Anything could be affected by this change, if it doesn't load in 5 seconds or something. Mind closing, and instead raising an issue in the card that you use to display the entities?

**Comment by thomasloven** [comment]
browser_mod devices are not saved between restarts of Home Assistant. To reconnect, you must reload the page on the device after restarting Home Assistant.
