### ISSUE TITLE
pop ups not applying styles (HA 0.113 and browser mod 1.1.0)

### ISSUE THREAD

**Issue by basesnow** [thomasloven/hass-browser_mod#117]
Pop ups are functioning, but style is not being applied. Also noticed on my pop ups that they are not centered on screen. Sometimes are partially off screen.

same here..... styles not applied
![recorte](https://user-images.githubusercontent.com/7722479/88429170-15361d80-cdee-11ea-99a4-818349e4b869.png)

_Originally posted by @joseska in https://github.com/thomasloven/hass-browser_mod/issues/115#issuecomment-663702172_

**Comment by thomasloven** [comment]
Since so much is broken anyway, I bit the bullet and moved over to card-mod styles in 1.1.1.
https://github.com/thomasloven/lovelace-card-mod

That means card-mod must be installed for styling to work, and that the syntax is entirely different.


It's a very breaking change, but it's also much more powerful, and means popups can be styled via the theme.
I haven't had the time to come up with a migration guide yet, but I'll keep this issue open and maybe someone will post their discoveries.

Good luck!

**Comment by basesnow** [comment]
Welp, this fixed everything for me. I wasn't modifying style of my pop up cards. So I didn't have to change anything. Updated to latest and now the cards are showing up properly. Quick turnaround is an understatement here! Thanks again

**Comment by ronaldheft** [comment]
Great change here. 1.1.1 fixed all my popup styles and everything is loading perfectly.

**Comment by theone11** [comment]
Can someone post an example of how to change the width of a popup with the new card-mod?
I tried a few options and could get it to work.

**Comment by thomasloven** [comment]
Try:
```yaml
style: |
  .content {
    width: 90vw !important;
    height 90 vh;
  }
```

**Comment by thomasloven** [comment]
Here's some styles for setting height and width, making a transparent background and setting a border radius 

```yaml
style:
  $: |
    .mdc-dialog .mdc-dialog__container .mdc-dialog__surface {
      border-radius: 25px;
    }
  .: |
    :host {
      --mdc-theme-surface: rgba(0,0,0,0);
      --secondary-background-color: rgba(0,0,0,0.5);
      --ha-card-background: rgba(0,0,0,0.5);
    }
    :host .content {
      width: 90vw;
      height: 90vh;
     }
```

**Comment by basesnow** [comment]
OK, I spoke a little too soon. Pop ups work fine on my fire tablet using fully kiosk. But they don't show up at all now on my iPhone running the HA companion app, or in safari on my Mac. I restarted HA and cleared my cache in the app and in safari, but no luck. The pop ups would show up in 1.1.0, but the styling was messed up. Now I am getting nothing running 1.1.2

**Comment by thomasloven** [comment]
Oh look. Yet another javascript function that safari just doesn't support... I swear it's the IE6 of the 20teens...

I know what the problem is, but won't have time to fix it for a few hours.

**Comment by thomasloven** [comment]
Should work now

**Comment by UmbeMont** [comment]
Hi , same problem , popum mac & iphone not showing  any popup , i hold the button , but nothing come out.

<img width="938" alt="image" src="https://user-images.githubusercontent.com/60969724/88466404-d1ade300-cec3-11ea-8ebe-6bc99ac48c03.png">

**Comment by thomasloven** [comment]
After updating to 1.1.3, try adding `?whatever` to the end of the resource URL and do a hard refresh.

**Comment by UmbeMont** [comment]
i do not have browser mod in resources , i only use card mod and i do not have updates available.
1.1.3 version is browser mod ?

**Comment by thomasloven** [comment]
Oh! Silly me. Of course. Sorry about that.

**Comment by UmbeMont** [comment]
Updated just now browser mod folder , restarted and all good! 
Thanks a lot!

<img width="415" alt="image" src="https://user-images.githubusercontent.com/60969724/88700079-19b94980-d100-11ea-949c-7f66a6549af3.png">

**Comment by ASNNetworks** [comment]
> Updated just now browser mod folder , restarted and all good but....
> 
> The only problem now is when you go on settings , it does not open anymore the setting of the light 
> 
> Thanks a lot!
> 
> 
> 
> <img width="415" alt="image" src="https://user-images.githubusercontent.com/60969724/88700079-19b94980-d100-11ea-949c-7f66a6549af3.png">
> 
> 
> 
> 
> 
> <img width="246" alt="image" src="https://user-images.githubusercontent.com/60969724/88700520-b976d780-d100-11ea-9e26-aad72f46e090.png">
> 
> 

That has nothing to do with browser mod, but light-pop-card you use. It has been updated and no longer shows settings. You need to envoke a custom card now. See [this](https://github.com/DBuit/light-popup-card#settings) for more information.

**Comment by NR3Y** [comment]
Hmmm, I'm having a similar issue (styles not being applied).

I have created an automation that throws up a pop-up card when a device changes state. (In this example, a light coming on, but the code is a placeholder for a freezer door being open, when I get around to purchasing the appropriate hardware.)

Trigger (in this case) the light does in fact bring up a popup card, but none of the requested styles are applied.

If anyone has any brilliant suggestions, I'd much appreciate it.

Code from my automation script:

- id: '1680206256594'
  alias: Test Popup for Light
  description: Tests Popup if Light Comes On
  trigger:
  - platform: state
    entity_id:
    - light.landing
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: browser_mod.popup
    data:
      dismissable: true
      autoclose: false
      content: 
        type: custom:popup-card
        entity: light.upstairs_alcove
        title: ACTION NEEDED
        card:
          type: markdown
          style: |
            ha-card {
            color: red;
            width: 100%;
            height: 100%;
            background-color: #3C4048;
            text-align: center;
            padding-top: 0px;
            font-size: 30px;
            }
        content: Alcove Light is On
        size: normal
  mode: single

**Comment by nochlab1** [comment]
> Hmmm, I'm having a similar issue (styles not being applied).
> 
> I have created an automation that throws up a pop-up card when a device changes state. (In this example, a light coming on, but the code is a placeholder for a freezer door being open, when I get around to purchasing the appropriate hardware.)
> 
> Trigger (in this case) the light does in fact bring up a popup card, but none of the requested styles are applied.
> 
> If anyone has any brilliant suggestions, I'd much appreciate it.
> 
> Code from my automation script:
> 
> * id: '1680206256594'
>   alias: Test Popup for Light
>   description: Tests Popup if Light Comes On
>   trigger:
>   
>   * platform: state
>     entity_id:
>     
>     * light.landing
>       from: 'off'
>       to: 'on'
>       condition: []
>       action:
>   * service: browser_mod.popup
>     data:
>     dismissable: true
>     autoclose: false
>     content:
>     type: custom:popup-card
>     entity: light.upstairs_alcove
>     title: ACTION NEEDED
>     card:
>     type: markdown
>     style: |
>     ha-card {
>     color: red;
>     width: 100%;
>     height: 100%;
>     background-color: #3C4048;
>     text-align: center;
>     padding-top: 0px;
>     font-size: 30px;
>     }
>     content: Alcove Light is On
>     size: normal
>     mode: single

Hi did you figure it out?

**Comment by NR3Y** [comment]
Hi Thomas,

Sadly, no. Actually, I did (temporarily) abandon the idea and instead used the default notification service, which actually works out a little better in my case.

I’m using (at the moment) an old iPad Air as my wall-mounted tablet. In the IOS settings, I set notifications to persist. In the HA automation, I now call a ‘send notification to the iPad companion app’ service with the appropriate message. This nicely pops up a notification on my panel, along with a nice beep as an audible attention-getter, and the message stays there (persistent notification) until I tap on it, where it dutifully disappears. The down-side is that the popup is always at the top of the screen, but I can live with that.

Going down the road, I might replace the iPad with a cheap Android tablet for the following reasons:
Waking the tablet up from a ‘deep sleep’ remotely might be easier on Android; can’t do that on the iPad
I might be able to use the tablet’s camera to automatically wake up the tablet - something iPad doesn’t support

Thanks for checking, though.

Darrell

**Comment by taggy99** [comment]
Hi,
Anyone know has to style the title text of the browser-mod pop-up, the below changes the background color but has to effect on the text. What am I doing wrong?

content {
       background: green;
       color: red;
       font-size: 10px;
     }
