### ISSUE TITLE
Some entities don't update in popups since update to 0.113 and 1.1.1

### ISSUE THREAD

**Issue by BradAndAU** [thomasloven/hass-browser_mod#118]
Hi @thomasloven thanks for all your work on this and all your other cards.
I've noticed since the update to 0.113 and browser_mod 1.1.1 that some entities no longer dynamically update in popups, for instance I use the more-info popup with the light-entity-card and if I move the color wheel or select a different effect from the dropdown it updates, but if I move the brightness slider the % doesn't change until I close the popup and re-open.

**Comment by thomasloven** [comment]
Should be fixed in 1.1.2
