### ISSUE TITLE
Custom elememts does not exists if upgrade from 1.1.1 to "1.1.2 or 1.1.3 "

### ISSUE THREAD

**Issue by pergolafabio** [thomasloven/hass-browser_mod#120]
None of my cards load when i upgrade to latest release 1.1.2 , previous releases are working fine
i tried also incognito, cleared cache
its definety related to 1.1.2 

if i also disable the custom component, it loads fine

screenshot : https://www.dropbox.com/s/vom10mo1doyl6te/custom1.PNG?dl=0

**Comment by roflcoopter** [comment]
I just got the same issue. Dekstop Chrome or iOS app is the same.
Cleared cache on both to no avail

**Comment by roflcoopter** [comment]
Seems to be some timining issues, if i continually refresh it works eventually, but then a new refresh breaks it again.

**Comment by pergolafabio** [comment]
Glad I am not the only one here, hopefully he can look into it

**Comment by pergolafabio** [comment]
Have you tried also 1.1.3 ?

**Comment by roflcoopter** [comment]
Yes, i hade the same issue.
However i think its related to lovelace-preloader-card. Are you also using it?
It kept throwing an error, so i cloned that repository and fixed the code and now i dont have issues.
I opened a ticket [here](https://github.com/gadgetchnnel/lovelace-card-preloader/issues/6)

**Comment by pergolafabio** [comment]
Hmm, not 100 sure, need to look later

**Comment by pergolafabio** [comment]
No, I am not using pre loader anymore, I used it before...

I noticed in 1.1.2 code changed , he changed something to async ... Not sure if that something to do with it

**Comment by pergolafabio** [comment]
installed the 1.1.3 version, but still same, for testing, i want todo this change manally, to see if it has any effect
allthough , i cant find that file in my custom folder?  :-)

https://www.dropbox.com/s/6jsvqb7klfuaa8b/custom2.PNG?dl=0

**Comment by roflcoopter** [comment]
Yeah mine stopped working again, guess i got lucky a few times then.

**Comment by pergolafabio** [comment]
Do you know where to change that main.js file?

**Comment by roflcoopter** [comment]
It is packaged with webpack so you need to clone the repo and build it yourself

**Comment by pergolafabio** [comment]
Ok, that's out of my control ;)

**Comment by roflcoopter** [comment]
Just reverted back to 1.1.1 aswell and its working, however that version has the issue of popus not working in Safari :(

**Comment by pergolafabio** [comment]
but why  is this issue just limited to us 2 ? :)

**Comment by basesnow** [comment]
@thomasloven mentioned in another issue thread that you can add ``` ?whatever ``` to the end of your URL and force a refresh. That fixed the custom element error for me. Haven't had it since.

**Comment by pergolafabio** [comment]
Hmm, it also happens in incognito mode, on all devices
Don't think it's a cache issue

**Comment by Juggels** [comment]
I’m seeing this behavior intermittently as well, most of the time a refresh fixes it, sometimes it takes another refresh.

The custom integrations I have running are:
- custom-header
- browser-mod
- card-mod
- layout-card
- button-card

**Comment by pergolafabio** [comment]
Ok, hopefully fixed soon... I also see it in the HA Android app and also in chrome on desktop

**Comment by afxefx** [comment]
I also have this issue if I go past 1.1.1, haven't had a chance to debug any possible causes yet though.

**Comment by thomasloven** [comment]
What do your browser consoles say?

**Comment by migo-dev** [comment]
Same here - but only via cloud. Works fine locally.

Here's my browser console:

```
chunk.8b29f0c82629b54e915d.js:25233 Uncaught (in promise) TypeError: Cannot read property 'connection' of undefined
    at HTMLElement.value (chunk.8b29f0c82629b54e915d.js:25233)
    at l (browser_mod.js:1)
```

**Comment by pergolafabio** [comment]
> Same here - but only via cloud. Works fine locally.
> 
> Here's my browser console:
> 
> ```
> chunk.8b29f0c82629b54e915d.js:25233 Uncaught (in promise) TypeError: Cannot read property 'connection' of undefined
>     at HTMLElement.value (chunk.8b29f0c82629b54e915d.js:25233)
>     at l (browser_mod.js:1)
> ```


i can confirm same error! indeed locally works fine, but not with cloud , in my case nabucasa

**Comment by yieldhog** [comment]
I am having the same issue on Safari / Chrome / Home Assistant companion (iOS) after upgrading to 1.1.3. Even after emptying cache / reloading. On HA 0.113.1

**Comment by Multifunk-maker** [comment]
I get the same trouble when connection via cloud, nabucasa. 

`browser_mod.js:149 BROWSER_MOD 1.1.3 IS INSTALLED 
chunk.8b29f0c82629b54e915d.js:25233 Uncaught (in promise) TypeError: Cannot read property 'connection' of undefined
    at HTMLElement.value (chunk.8b29f0c82629b54e915d.js:25233)
    at l (browser_mod.js:1)`

**Comment by Mariusthvdb** [comment]
seeing this, but not always, enough to make it unusable unfortunately. After upgrading both HA to 113.x and Browser mod above 1.1.1.

need to refresh a lot to get rid of it. downgrading to 1.1.1 solves it immediately. Odd thing is I only have card-mod related errors in the inspector.

**Comment by pollinolas** [comment]
Something curious, if I am connected to the wifi then the interface will be loaded sometimes and sometimes not, if I am with the mobile data it never loads the interface

**Comment by thomasloven** [comment]
I think I know what's happening.
A weird edge case where browser_mod is loaded in way before anything else and the connection to the backend isn't established yet.

Note to self:
- Move load_lovelace to _connect?
- Check for hc-lovelace being defined?
- Frequent repolling?

**Comment by pergolafabio** [comment]
What can we do to test?

**Comment by thomasloven** [comment]
You could try 1.1.4

**Comment by pergolafabio** [comment]
fixed, thnx! :à)

**Comment by migo-dev** [comment]
Thank you very much! 1.1.4 fixed it for me too
