### ISSUE TITLE
"More Info" is behind Popup-window

### ISSUE THREAD

**Issue by cotwild** [thomasloven/hass-browser_mod#126]
I am on 0.113 and browser mod 1.1.4 and everything is working great so far. The only thing that's not working right now is that when I use the popup cards and press on a sensor to show history or just more info, the new opened window is behind the popup-card. when I close the popup-card i can actually see the more-info card.

Is there somehow a layer order I could change?
![image](https://user-images.githubusercontent.com/8470092/88917944-ed6d0c80-d268-11ea-9733-5a7c64958b6f.png)
![image](https://user-images.githubusercontent.com/8470092/88918029-11c8e900-d269-11ea-9b60-83a511c710e6.png)

**Comment by syphernl** [comment]
It appears that 1.1.6 has fixed this. In my setup the more_info popups are now opening on top of the browser_mod modal.

**Comment by cotwild** [comment]
Yes, seems to be fixed! Thanks a lot!
