### ISSUE TITLE
PopUp Website ( Spotify ) 

### ISSUE THREAD

**Issue by thib5** [thomasloven/hass-browser_mod#131]
Hi, would it be possible to load a website in a popup card ? ( "https://open.spotify.com" ) I try to put it as an iframe but Spotify do not work in a iframe. so I need something like ... ? 

              service: browser_mod.popup
              service_data:
                navigation_path: "https://open.spotify.com"
                deviceID:
                  - this

Thanks

**Comment by KTibow** [comment]
Yes, it is possible to load a website in a popup card. No, the actual spotify page can't be loaded. Yes, there are spotify player cards for Home Assistant (I think). No, if this solved your issue it'd be nice if you didn't keep it open.
