### ISSUE TITLE
Android App - Browser_mod

### ISSUE THREAD

**Issue by Bredin76** [thomasloven/hass-browser_mod#135]
Hi,

I'm not able ton have browser_mod working in HA android App.

i use that code for in a picture-element card 
![image](https://user-images.githubusercontent.com/52492895/92333952-bbca3b00-f089-11ea-862d-ed1cb4edc7cb.png)

when i tap on my sensor-icon in my android app while Chrome Laptop still opened, popup appeared on my laptop screen 
When i do the same while chrome laptop closed then - nothing happen

I tried to use ``browser_mod.debug`` in my android_app but nothing happen. Worse, the popup appeared on my laptop screen 
and ID is the same as in my chrome laptop

can i use browser_mod in an android app ?

**Comment by mikepan-ovoenergy** [comment]
Same question for the iOS / MacOS app? :) It doesn't work there, only in browsers.

**Comment by KTibow** [comment]
Try tapping once on the screen.

**Comment by mikepan-ovoenergy** [comment]
> Try tapping once on the screen.

Sorry, what does that mean? I'm tapping a lot and nothing happens. No console errors either.

**Comment by KTibow** [comment]
Oh. Thought that it wasn't displaying because it needed interaction first.

**Comment by vdiogo** [comment]
Same here with iOS App (Home Assistant)

**Comment by KTibow** [comment]
> @vdiogo: Same here 

Use the +1 button
![image](https://user-images.githubusercontent.com/10727862/102541177-f36f5880-4064-11eb-8058-7763f3fccd8d.png)

**Comment by thomasloven** [comment]
It's `deviceID`, not `device`.
