### ISSUE TITLE
set_theme not working

### ISSUE THREAD

**Issue by hjbotha** [thomasloven/hass-browser_mod#136]
Home Assistant 0.114.4
browser_mod 1.1.6

Fresh install of Home Assistant. The only additions:
HACS
browser_mod
midnight theme

Opened Home Assistant in two different browsers.
Main: Firefox
Target: Chrome

1. In Firefox, I used Home Assistant developer tools > States to get the deviceID of the Chrome browser.
2. In Firefox, I used Home Assistant developer tools > Services to call browser_mod.navigate on Chrome's device ID, using the following data:
```
navigation_path: /
deviceID: 97049f9b-09fea11c
```
3. I confirmed that Chrome navigated to the specified path.
4. In Firefox, I used Home Assistant developer tools > Services to call browser_mod.set_theme on Chrome's device ID, using the following data:
```
theme: midnight
deviceID: 97049f9b-09fea11c
```
5. The theme in Chrome does not change as expected

I tried repeating step 4 in various ways. Different themes, no theme (so that it sets the theme back to default) but it never has any effect.

Unfortunately I don't know when this stopped working. Is it possible that the format of the settheme event in the frontend changed when they introduced dark mode?
https://github.com/home-assistant/frontend/commit/4ca13c409b9086c457435816c8d0aab7a025a684#diff-866ba8f3b6e1047a72fea51640ef989e
I feel like it stopped before that, but I didn't investigate very deeply when I first realised the theme wasn't changing anymore, so I can't be sure.

**Comment by thomasloven** [comment]
Fixed by #149. Syntax updated in Home Assistant.
