### ISSUE TITLE
Styles not working on 0.114.4

### ISSUE THREAD

**Issue by StraMil** [thomasloven/hass-browser_mod#138]
I can't get style to work, have updated browser_mod to 1.1.6 and card-mod 2.0.0 and still nothing

Copied some code from a solved issue but no luck

![Screenshot_1](https://user-images.githubusercontent.com/48089271/93127713-b0e95900-f6ce-11ea-862a-624e1b5a8d2b.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/48089271/93127711-b050c280-f6ce-11ea-908d-7c77a98819c1.jpg)

**Comment by KTibow** [comment]
Try scrolling down in the style panel and making sure card-mod is installed.

**Comment by StraMil** [comment]
It's installed, I'm using it on almost every card, even the slider on the photo and it's working fine, it just won't work with the browser mod popup
In the Inspect Element the <card-mod> for the popup doesn't show up, but for the grey slider it does

**Comment by KTibow** [comment]
I've tried to do this and couldn't successfully override it. Try ` !important`, but I don't think this will work.

**Comment by StraMil** [comment]
Yeah tried that already, doesn't work

**Comment by KTibow** [comment]
:( Can you even find the card-mod style?

**Comment by StraMil** [comment]
No :( , there is a <style> but it isn't from the card-mod
![Screenshot_3](https://user-images.githubusercontent.com/48089271/93138581-83f17200-f6df-11ea-9360-75e56f41a042.jpg)

**Comment by KTibow** [comment]
Weird...
