### ISSUE TITLE
Feature Request: Ability to delete unused entities

### ISSUE THREAD

**Issue by skynet01** [thomasloven/hass-browser_mod#14]
Is there a way to delete entities? I have about 10 of them that accumulated over 2 weeks. Also it looks like once you assign an alias to an entity you can't change the entity to something else you have to create another unique alias.

For example if I assign xxxx_xxxx to ipad and that browser changes then I can't update the ipad alias to the new entity. Some command to purge entities that are in the "unknown" state would be great :)

**Comment by thomasloven** [comment]
Browser_mod entities are cleared on Home Assistant restarts.
