### ISSUE TITLE
Browser hangs on wakeup from blackout if left for a long time

### ISSUE THREAD

**Issue by KiwiLostInMelb** [thomasloven/hass-browser_mod#140]
Hi Thomas,

Thanks for a great mod! Really really appreciate it.

I have an issue with a new android tablet running 10 go edition however.  Webkit (android not ASOP) is v85 etc. mod_browser is v1.1.6.

I use the blackout feature as a screen saver for a wall mounted tablet - blackout after 60 seconds of inactivity so it doesnt annoy people walking past - not for power saving as I dont care about power used.  

Wake on touch works if the screen is touched within a few seconds but if I leave it for say 5 minutes or longer then the screen will not wake.

Tested on fully kiosk AND the HA companion app.  Both have the same behavior.  
Things I have tried:
 - cleared cache
 - I have disabled all setting to put the screen to sleep
 - disabled lock 
 - including developer settings - don't allow screen to sleep
 - Tried fully kiosk and HA app - both have the same issue
 - Seemed to work fine on an ipad I have

If I repeatedly tap the screen then it **might** wake up after 5 or so taps OR I get an error - app not responding message.

The funny thing is if I send a no_blackout message then the screen wakes when in this state fine - after a bit of a lag (2 seconds or less).

No errors in the HA logs on the server side.

So, I am thinking that this seems to be a webkit issue maybe? Any ideas? Anything else I can try or test?

Thanks heaps mate!

**Comment by KTibow** [comment]
I think that this is a problem with the app most likely. Are you sure you've disabled falling asleep in settings?

**Comment by KiwiLostInMelb** [comment]
Found it - Android 10 issue - always turns off screen instead of black screen.  Android 10 doesn't allow apps to run as a service - at least not in android 10 GO edition grrr.

Wish I had a rom for Android 9 or earlier.  Good to close.  Thanks for the reply.
