### ISSUE TITLE
Current Fully Kiosk Version doesn't show as device_id

### ISSUE THREAD

**Issue by paddy0furniture** [thomasloven/hass-browser_mod#142]
I'm unable to get fully Kiosk to connect to HA as a device_id. I'm connected with two tablets via Fully Kiosk but browser mod never picks up device_Ids from either of them. Other browsers (PC, iphone, silk, etc.) work fine. FK settings for Javascript are enabled.

**Comment by paddy0furniture** [comment]
On my PC the card appears to work fine. On the tablet I get Custom element doesn't exist: browser-player

**Comment by KTibow** [comment]
So then browser-mod isn't loading.

**Comment by KTibow** [comment]
Or there's an exception somewhere.

**Comment by paddy0furniture** [comment]
Yeah it's weird. Silk on the same device works fine just an issue in fully kiosk.

**Comment by thomasloven** [comment]
Please try release 1.2.0

**Comment by paddy0furniture** [comment]
> Please try release 1.2.0

Unfortunately no joy there. Same result. Other devices register and are accessable (window PC - Chrome, Iphone- safari, Silk Browser on the same tablets that normally run Fully Kiosk). The Fully Kiosk browser just isn't  registering a device ID, but I am able to use pull camera images from the Fully Kiosk URL using a generic camera setup in the config...yaml.

**Comment by smeehrrr** [comment]
I am having this same issue: No device ID issued to Fully Kiosk.  Fully Kiosk version is 1.42.4-fire with plus license, browser_mod version is 1.2.3.

**Comment by ybizeul** [comment]
Doesn't work with fully kiosk here either, works fine in Fire Tablet browser
