### ISSUE TITLE
Volume control missing in browser-player card in Home Assistant 0.116

### ISSUE THREAD

**Issue by gadgetchnnel** [thomasloven/hass-browser_mod#143]
In Home Assistant 0.116, the volume controller is not displayed on the browser-player card:

![image](https://user-images.githubusercontent.com/2099542/95596952-f1c25c80-0a45-11eb-84cf-d9d6c86969b8.png)

It looks like this may be due to it user ha-paper-slider instead of ha-slider, as changing

```javascript
<ha-paper-slider
        min=0
        max=1
        step=0.01
        ?disabled=${e.muted}
        value=${e.volume}
        @change=${this.handleVolumeChange}
      ></ha-paper-slider>
```
to

```javascript
<ha-slider
        min=0
        max=1
        step=0.01
        ?disabled=${e.muted}
        value=${e.volume}
        @change=${this.handleVolumeChange}
      ></ha-slider>
```
in browser_mod.js in the custom_components/browser_mod folder brings back the volume control.

**Comment by KTibow** [comment]
Wanna send in a PR? ❤️
