### ISSUE TITLE
media_player video

### ISSUE THREAD

**Issue by tunerooster** [thomasloven/hass-browser_mod#146]
When I play video to a browser_mod media_player, I can hear the audio playing, but there is no video.

E.g.,
```
entity_id: media_player.browser_basement_gentoo
media_content_id: 'https://mydomain.com/local/SampleVideo_1280x720_5mb.mp4'
media_content_type: video
```
I have tried it on 3 different tablets *and* my desktop browser, all with the same result...
What could be wrong?

**Comment by KTibow** [comment]
That it doesn't support video. It's meant for stuff like playing doorbell chimes or adding sound to the UI. Edit to a feature request probably.

**Comment by tunerooster** [comment]
What does this mean then, from the description:

Make the camera feed from your front door pop up on the tablet in your kitchen when someone rings the doorbell.

**Comment by KTibow** [comment]
Using `browser_mod.popup`

**Comment by tunerooster** [comment]
Is there an example of how to do this.  I.e., display my camera feed on a remote tablet?  That is exactly what I would like to do.  The examples of pop-up don't refer to a camera entity.

Thanks!

**Comment by tunerooster** [comment]
I found an example at:

https://community.home-assistant.io/t/browser-mod-turn-your-browser-into-a-controllable-device-and-a-media-player/123806/14

In m case this worked!
```
service: browser_mod.command
command: more-info
deviceID: browser_touchpad_1
entity_id: camera.frontdoor
```

Thanks for your patience!
