### ISSUE TITLE
deviceID Problem

### ISSUE THREAD

**Issue by tunerooster** [thomasloven/hass-browser_mod#147]
Somehow, the generated deviceID changed on me.  This happened twice on two different devices.  I have no idea what I did to cause this.  I am using the custom alias to assign a name for the deviceID, but when to underlying generated deviceID changes, the alias does not pair.

To prevent this from happening, I see that I can specify deviceID in the Home Assistant URL.  That sounded great but...

I am using the Home Assistant Android App:

* I went to App Configuration and entered Home Assistant URL: https://mydomain.com/?deviceID=test
* There is no "save" button I can see, so I hit the back arrow.
* I select App Configuration again, and the Home Assistant URL has reverted back to: https://mydomain.com (i.e., with no deviceID)
* Restarting the App makes no difference.
* So I cleared the App data and cache, ant reinitialized the App.  I.e., it asked for the external URL during startup.
* Again I entered:  https://mydomain.com/?deviceID=test
* Once initialized and logged in, I went to App Configuration and was disappointed to see it still reverted to:  https://mydomain.com (i.e., with no deviceID)

I understand this is not necessarily a browser_mod issue, but I am posting here because I am hoping others here have figured a way to specify deviceID for the Android App.

Is there a way to get the App to preserve the ?deviceID= in the URL?

Is there is another way?  If so, please provide a complete example, as I am new to Home Assistant and especially lovelace cards...

BTW, is there a more appropriate place to post this?

**Comment by KTibow** [comment]
You could try to directly set the cookie/local storage with a custom JS script.

**Comment by tunerooster** [comment]
So the deviceID is stored in a browser cookie?  I don't see deviceID in the chrome cookie for HA on my desktop, where I regularly access homeassistant.  I'm not techincal enough, I guess, to know how to go about that, but thanks in any case for the suggestion.

Do you have an Android phone/tablet with the HA App installed?  Perhaps you could try adding deviceID= to the URL in the app and let me know if it fails to persist.  At least I would then know it is not something I am doing wrong.  :)

Thanks!

**Comment by KTibow** [comment]
I don't actually have browser_mod installed right now, but if you asked on the forum thread lots of people would give their opinion on it.

**Comment by tunerooster** [comment]
Pardon my ignorance, but where is the correct forum for this?

**Comment by KTibow** [comment]
https://community.home-assistant.io/t/browser-mod-turn-your-browser-into-a-controllable-device-and-a-media-player/123806

**Comment by thomasloven** [comment]
Did you check what your deviceID is after going to `?deviceID=test`?
It's a one-time thing.

**Comment by tunerooster** [comment]
No, I didn't realize that. What happens if you set it twice.  Like to
change it from test?  Where is it stored?  Can it be changed in the place
it is stored?  I'm referring to the android app.

**Comment by thomasloven** [comment]
If you do it twice, you get the second deviceID.

It's stored in the browser, in a database known as `localStorage`. I do not think there's any way to manually change the settings there in the app.

**Comment by tunerooster** [comment]
Interesting...  I may look into that.

I haven't checked if it *was* actually stored (before being removed from the App's URL field).  I will check into that too...  If it is, then problem solved (I can forget localStorage).

Many thanks!

**Comment by tunerooster** [comment]
This looks interesting (probably only to me though :) ...

https://developers.google.com/web/tools/chrome-devtools/storage/localstorage

**Comment by xbmcnut** [comment]
@tunerooster Did you ever resolve this? I've had my Device ID reset for the 3rd time on my tablet running BM 1.2.3 under Fully Kiosk and I'm assuming that's because the cache has been cleared? It's not clear from reading this repository or the forum whether there is a way to permanently stick a device ID as it's stored in the browser cache?

From what I understand, I can force a device ID by appending ?deviceID=1234-5678 to the URL and this then stores this device ID. Is that correct? If so, whenever the cache is cleared, I'd have to use that URL method to ensure the device ID programmed in all of my automations is reset to the one defined in the configuration.yaml?

**Comment by tunerooster** [comment]
You can change it permanently using a:

type: 'custom:browser-player'

lovelace card.  In the lower left corner of the card (on each device).

**Comment by xbmcnut** [comment]
Thanks @tunerooster So if I use that method shown below, the device ID will survive a browser cache clearing?
![image](https://user-images.githubusercontent.com/1492137/100015675-37dc4f80-2e3d-11eb-8f09-37c72ce50c19.png)

**Comment by tunerooster** [comment]
I doubt it.  lt is stored in browser "local storage" so if that is
considered part of cache, then likely not.
