### ISSUE TITLE
FEATURE REQUEST: (Play video, not just sound)

### ISSUE THREAD

**Issue by tunerooster** [thomasloven/hass-browser_mod#148]
I would like to be able to do the following: (play a previously recorded video from my camera)

```
entity_id: media_player.browser_basement_gentoo
media_content_id: 'https://mydomain.com/local/front-camera.mp4'
media_content_type: video
```

It doesn't see like it should be to hard, since it can already play my camera stream directly:
```
service: browser_mod.command
command: more-info
deviceID: browser_touchpad_1
entity_id: camera.frontdoor
```

...and it already plays "the audio" from the mp4 file.

Thanks!

P.S.
I was unable to see a place to make a feature request, so I am posting under "Issues".  If there is a "Feature Request" procedure, please inform me.

**Comment by thomasloven** [comment]
Closed because of Browser Mod 2.0 release.
Please see #354.
