### ISSUE TITLE
Styles not dynamic.

### ISSUE THREAD

**Issue by MaartenMees** [thomasloven/hass-browser_mod#160]
My Home Assistant version: 17.XX.X

What I am doing:

I made a browser_mod popup with buttons. If you push button should change color.

What happened instead:

Buttons keep color. Unless you reopen the popup.

This:

![Screenshot_20201109-124459_Home Assistant.jpg](https://user-images.githubusercontent.com/26173684/98538720-7eea1280-228b-11eb-80f2-1acd54d5b4bd.jpg)

Shoud be this after pushing "Aan". But only happens after reopening..

![Screenshot_20201109-124442_Home Assistant.jpg](https://user-images.githubusercontent.com/26173684/98538849-afca4780-228b-11eb-85d5-80a2437511fb.jpg)

Any ideas somebody? Works fine without popup. I use custom:button-card  for the buttons.

Thanks!

**Comment by KTibow** [comment]
This might be a known issue with button-card. I've found that sometimes it doesn't update in edit mode as well.

**Comment by MaartenMees** [comment]
According to Romrider from button-card mod it's not their problem. (Don't say it's browser_mod, can always just be me xd)

Quote:
"Button card will only update if it receives the update from the pop-up, if it's not receiving anything, it will not update. It's not something I have control over."

**Comment by MaartenMees** [comment]
My bad. Was using styles from custom:button-card
When using card-mod everything works as expected.
