### ISSUE TITLE
Full Screen option

### ISSUE THREAD

**Issue by niccolobusato** [thomasloven/hass-browser_mod#162]
hi, thanks for your work. 

we currently have "blackout" // or "large" option but wold be cool to be able to have a full width and full height pop up to put a clock o something else in the middle.. 

is that possible? thanks a lot

**Comment by KTibow** [comment]
You can use the kiosk-mode add-on, with a panel mode dashboard, with the `browser_mod.navigate` service.

**Comment by niccolobusato** [comment]
can't find anything about kiosk-mode add-on.. is a custom component?

**Comment by KTibow** [comment]
It's an addon, shows right up for me when I google it with "home assistant".
https://github.com/maykar/kiosk-mode

**Comment by niccolobusato** [comment]
thanks works amazing well!!
