### ISSUE TITLE
No sensor on Google Home Hub

### ISSUE THREAD

**Issue by dotKrad** [thomasloven/hass-browser_mod#165]
My Home Assistant version: 0.118.2

What I am doing:

When using catt the browsermod is not creating the sensor in the Google Home Hub, I have a Lenovo Smart Display and its working on it

What I expected to happen:

Create sensor, light, and media_player

What happened instead:

Only create light and media_player

**Comment by KTibow** [comment]
What did you want to use the sensor for?

**Comment by dotKrad** [comment]
I'm using the Visibility attribute to keep the Google Home Hub displaying the Home Assistant frontend

**Comment by KTibow** [comment]
What is catt doing to show it? Do you see any errors related to `frontend` in the HA log?

**Comment by dotKrad** [comment]
No errors related to frontend in the HA log

**Comment by KTibow** [comment]
Have you tried restarting? Do the other entities work?

**Comment by dotKrad** [comment]
Sorry didn't realize I do have errors
`2020-11-21 01:59:52 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [1848581976] Error handling message: Unknown error
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
handler(self.hass, self, schema(msg))
File "/config/custom_components/browser_mod/connection.py", line 42, in handle_update
devices[deviceID].update(msg.get("data", None))
File "/config/custom_components/browser_mod/connection.py", line 83, in update
self.sensor = self.sensor or create_entity(
File "/config/custom_components/browser_mod/helpers.py", line 47, in create_entity
adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'`

**Comment by KTibow** [comment]
Can you just reboot HA, and wait 10-30 minutes? Other people said that solved it.

**Comment by dotKrad** [comment]
> Have you tried restarting? Do the other entities work?

Yes, other entities work, only sensor missing in that specific device, all other devices working perfectly

**Comment by dotKrad** [comment]
> Can you just reboot HA, and wait 10-30 minutes? Other people said that solved it.

I did it last night, rebooted HA before going bed, today in the morning I "catt" HA to Google Home again and nothing, no sensor

**Comment by KTibow** [comment]
> What is catt doing to show it?

**Comment by dotKrad** [comment]
"cattt" is a python package used to "cast all the things" into chromecast devices, im using it to show a web page "HA" in the Home Hub

**Comment by DBuit** [comment]
> "cattt" is a python package used to "cast all the things" into chromecast devices, im using it to show a web page "HA" in the Home Hub

Hello @dotKrad, i am also missing the sensor for my nest hub. Every solved it?
