### ISSUE TITLE
popup media browser (just like more info but now popup the mediabrowser for the specific media player entity)

### ISSUE THREAD

**Issue by 1ntroduc3** [thomasloven/hass-browser_mod#167]
Hi Thomas,

This is my first feature request, sorry of it lacks of information, please feel free to ask/point me to the right direction.

### What I'm trying to achieve

**From any card, being able to open media browser for a specified/preselected player**
> From any card
> Open media browser card for a specific mediaplayer
> For example, spotify to select a playlist/song/album etc.

Some related info is available here (I think, with my limited programming knowledge)
Tks, 

[https://github.com/home-assistant/frontend/pull/7467](url)

**Comment by KTibow** [comment]
You could try embedding it using an iframe card, but I would rely more on `browser_mod.navigate`. Also questions are in the forum, maybe if you could make your feature request more general (popup panel instead of popup media browser) it would be better here.

**Comment by Quentin-Cloos** [comment]
Exactly what I'm looking for, the iframe card is not perfect for this, the native media browser popup from the media player should be available from a service, so that we can have it directly in a button in a card for exemple. It's a so powerful tool, it's too bad that we can't play with it more.

**Comment by thomasloven** [comment]
Closed because of Browser Mod 2.0 release.
Please see #354.
