### ISSUE TITLE
Feature Request: auto_close and timeout for more-info command

### ISSUE THREAD

**Issue by j0dan** [thomasloven/hass-browser_mod#17]
I use the more-info dialog to get a streaming video when someone presses the doorbell and it would be nice to auto-close it like I can with a popup.

**Comment by thomasloven** [comment]
The close_popup command works on more-info dialogs.

**Comment by j0dan** [comment]
Thanks Thomas. The close_popup command always worked on more-info commands. Did this release also add the auto_close and time options to a more-info dialog?

**Comment by thomasloven** [comment]
No. That isn't quite trivial, but you can popup a [more-info-card](https://github.com/thomasloven/lovelace-more-info-card).

**Comment by j0dan** [comment]
Thanks. That's what I'm doing now with an additional script to call the close_popup after a delay, but it would nice to have it time-out so I don't risk closing other popups.

**Comment by shaymdev** [comment]
@j0dan Have you found a solution for closing the camera more-info popup and not closing other popups (in the event the user has manually closed the camera more-info popup and is in the middle of using an unrelated popup?
