### ISSUE TITLE
How to get rid of these fellows?

### ISSUE THREAD

**Issue by severeski** [thomasloven/hass-browser_mod#176]
My Home Assistant version: 2020.12.2

What I am doing: Uninstalling

What I expected to happen: Be gone.

What happened instead:

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:84
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: December 30, 2020, 10:27:26 PM (16035 occurrences)
Last logged: 6:44:42 PM

[1711549840] Received invalid command: browser_mod/connect
[1711549840] Received invalid command: browser_mod/update
[1663027136] Received invalid command: browser_mod/connect
[1663027136] Received invalid command: browser_mod/update

the 16000+ caught my eye

**Minimal** steps to reproduce: Uninstall it

It does not really bother me but I am curious about the source. So I thought it might interest you how this ghost in the machine might generate these excessive amounts of errors and ho to fix it.

And really it does not bother me so in your spare time or something. and not sure if it is a addon bug or a home-assistant quirk. just wanted to report it.

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [ x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [ x] Have made sure I am using the latest version of the plugin.

- [ x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [ x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by KTibow** [comment]
You need to refresh the browser.

**Comment by severeski** [comment]
I already did that. cleared cache and everything. There is a piece about it in the documentation.

Only thing i can think of is I accessed it with a browser on a device I cannot think of right now. Only thing that makes sense.

**Comment by KTibow** [comment]
You can do a Fing scan to see all of the devices on your network.

**Comment by Corneloues** [comment]
I'm getting this too. I've uninstalled, removed the `browser_mod:` from my config yaml but these errors keep appearing.

> Logger: homeassistant.components.websocket_api.http.connection
> Source: components/websocket_api/connection.py:84
> Integration: Home Assistant WebSocket API (documentation, issues)
> First occurred: 12:06:51 (184 occurrences)
> Last logged: 12:22:02
> 
> [548255592352] Received invalid command: browser_mod/update
> [548255622240] Received invalid command: browser_mod/update

**Comment by KTibow** [comment]
You need to reload every single browser that has browser_mod installed. Remember you can always block logs using the `logger` component.
