### ISSUE TITLE
TypeError: this._do_connect is not a function

### ISSUE THREAD

**Issue by NemesisFN** [thomasloven/hass-browser_mod#179]
My Home Assistant version: 2021.1.3

What I am doing:
Restarting HA

What I expected to happen:

What happened instead:
Logger: frontend.js.latest.202012291
Source: components/system_log/__init__.py:193
First occurred: 4:51:47 PM (1 occurrences)
Last logged: 4:51:47 PM
http://X.X.X.X:8123/browser_mod.js:149:182 TypeError: this._do_connect is not a function 

**Minimal** steps to reproduce:
Restart HA

```yaml
# The least ammount of code possible to reproduce my error



# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [x ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [ x] Have made sure I am using the latest version of the plugin.

- [x ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [ x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by KTibow** [comment]
Please format your code with backticksand don't put spaces in the checkboxes.

**Comment by NemesisFN** [comment]
I’m not doing anything.  You know what it says, close it if you want I
don’t care
