### ISSUE TITLE
media_content_id is empty

### ISSUE THREAD

**Issue by KixMan28** [thomasloven/hass-browser_mod#180]
My Home Assistant version: core-2021.1.4

What I am doing:
I have set up browser mod on my HA running on a RPi 3B+. 
I access my home assistant instance via duckdns.org on my laptop in Chrome browser. All entities (sensor, light, media_player) are created by the integration. 
The media_content_id value is missing from the media_player so it cannot play any sound.
If I click on the Gear in the media player card, the setup window won't pop up.
How can I set up the media_content_id manually? This is my media_player entity:

```

volume_level: 1
is_volume_muted: false
media_content_id: ''
type: browser_mod
deviceID: Dell Chrome
supported_features: 21005

```

If I access my HA instance via nabu casa, from the same chrome browser, I have this media_player entity and this one works fine:

```
volume_level: 0.52
is_volume_muted: false
media_content_id: >-
  https://192.168.1.20:8123/api/tts_proxy/0c2019bb6a44503789b972420dc47319cb13936c_en-us_a9c18110b0_cloud.mp3
type: browser_mod
deviceID: 52584d3b-a1d34452
supported_features: 21005
```

What I expected to happen:
I would like to use the media_player tts function.

What happened instead:
The media_player tts function doesn't work because there is no media_content_id set in the media_player entity.

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error



# End of code
```

Error messages from the browser console:
![2021-01-18 15_09_11-Start](https://user-images.githubusercontent.com/33165356/104925523-40658800-599f-11eb-8b52-83ca702c477c.jpg)

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by KTibow** [comment]
> doesn't work because there is no media_content_id set in the media_player entity.

Are you sure that's the case? If you call TTS services, nothing happens, right?

**Comment by KixMan28** [comment]
@KTibow Yes, this is what I experience: in the media_player.dell_chrome, there is no media_content_id defined, while in the media_player.dell_nc there is. The dell_chrome, won't open the settings, while the dell_nc works as intended.
![2021-01-18 16_14_15-Search](https://user-images.githubusercontent.com/33165356/104933011-a60a4200-59a8-11eb-9e85-506d7a468d4d.jpg)
![2021-01-18 16_14_41-Search](https://user-images.githubusercontent.com/33165356/104933021-a9053280-59a8-11eb-92fa-07fa1b48b497.jpg)

How can I set the media_content_id manually or how can I force the integration to add the media_content_id in case of media_player.dell_chrome?

**Comment by KTibow** [comment]
What if you clear cache/cookies in the HA thing, and remove and re-add the computer to config?

**Comment by KixMan28** [comment]
@KTibow OK, cleared the cache and the cookies and now it works in both tabs. Thank you for your support.

**Comment by KTibow** [comment]
Consider closing?
