### ISSUE TITLE
Media player volume

### ISSUE THREAD

**Issue by elik745i** [thomasloven/hass-browser_mod#184]
Would be good to be able to set media player's (browsers) volume for played sound. fo instance I have alarm, I want it to sound loud and when disabled to play disable tome quieter.

**Comment by KTibow** [comment]
It might be hard to modify the sounds. I would recommend just modifying the alarm you made.

**Comment by elik745i** [comment]
no need to modify sounds, just to define volume from 1 to 100% for sound or TTS or media to be played.

**Comment by KTibow** [comment]
What exactly does
> no need to modify sounds

mean?

**Comment by elik745i** [comment]
> What exactly does
> 
> > no need to modify sounds
> 
> mean?

# Play mp3:

Service: media_player.play_media
Entity: media_player.desktop_pc

Service data:

entity_id: media_player.desktop_pc
media_content_id: /local/audio/test.mp3
media_content_type: 'audio/mp3'

to add option: media_content_vol: 50

**Comment by elik745i** [comment]
Maybe this is not under your control too, not sure..

**Comment by elik745i** [comment]
OK I solved it like this:
script.yaml:
`
set_volume_player:
  alias: Set player volume
  sequence:
    - service: media_player.volume_set
      data:
        entity_id: media_player.browser_mod_3e1a835f_6b9b27e9
        volume_level: 0.05
    - service: media_player.play_media
      data:
        entity_id: media_player.browser_mod_3e1a835f_6b9b27e9
        media_content_id: /local/audio/nuke.mp3
        media_content_type: audio/mp3
`
