### ISSUE TITLE
Disable mouse click out off popup area

### ISSUE THREAD

**Issue by elik745i** [thomasloven/hass-browser_mod#185]
Would be good to add disable mouse click outside off popup area. I have integrated alarm_panel into popup - works great! but the problem is I want for this card to disable mouse clicks outside of popup area till correct pin is entered or alarm is still armed.

**Comment by KTibow** [comment]
I don't understand your use case. What's the problem with closing the popup?

**Comment by elik745i** [comment]
I do not want user to be able to close popup if security system is armed, otherwise he has access to the rest of HA and can disable security system by removing card or executing disable security automation

**Comment by KTibow** [comment]
> and can disable security system by removing card

That's not how security systems in HA work. They might not be controllable via the card, but they're still there.

>  or executing disable security automation

They can only execute automations if you add them to your UI.

> I'm controlling HA through tablet on the wall.

Make sure the user that the tablet is signed into isn't admin.

**Comment by elik745i** [comment]
How to disable mouse click outside off popup? I'm sure it is easy to do. There is still option to show or hide close button. Can that instance to be automated? i.e. to show or hide close button? Popup itself can be closed via automation.

**Comment by KTibow** [comment]
I do really not get what you're trying to say. Could you restate more concisely?

**Comment by elik745i** [comment]
> I do really not get what you're trying to say. Could you restate more concisely?
Excuse my bad English, Option: hide_header: - what is it for if popup window can be closed simply by clicking around? 
Hope you understand now.

**Comment by elik745i** [comment]
Oh i think that behavior is not related to browser_mod but HA, browser_mod is just calls standard HA behavior (from looking at your code...)

**Comment by KTibow** [comment]
Did you even read https://github.com/thomasloven/hass-browser_mod/issues/185#issuecomment-773600479?

**Comment by oziee** [comment]
must be a way to do this.. a modal popup like in bootstrap 

seems that HA did once have a way (was a bug I think)
 https://community.home-assistant.io/t/wth-cant-i-click-outside-of-a-dialog-to-close-the-dialog/222756

would be good to have browser_mod integrate a modal type that has to have a button in the popup or behind code able to close it

**Comment by thomasloven** [comment]
Closed because of Browser Mod 2.0 release.
Please see #354.
