### ISSUE TITLE
Amateur HA user want to play music

### ISSUE THREAD

**Issue by gyenesadam** [thomasloven/hass-browser_mod#187]
Hi!

Sorry for my question, but I have no idea, where I need to write.
First...sorry for bad english, i from hungary.
My problem is:

I've got a Youtube music in my HA. When I write in the YT music integration's option tab's "Enter the default output player's entity ID" a test chromecast receiver's entity ID, works perfectly.
But I need to play the content on a phone (Android), or PC, or tablet. If, I write into the field, the ID my browser_mod media_player (media_player.player or media_player.browserID), nothing happening, just he YT music show's error messages (attached image, the red mark).
![Névtelen2](https://user-images.githubusercontent.com/77073590/107127429-5687a980-68b6-11eb-8859-774a98060244.png)

What I need to do for work, please help me!

Sorry again my amateur question!

**Comment by KTibow** [comment]
Couldn't you just use the official YouTube Music app instead of HA?

**Comment by gyenesadam** [comment]
Yes, maybe. But in HA is more elegant solution.

**Comment by KTibow** [comment]
What entity ID did you pass?

**Comment by gyenesadam** [comment]
I tried:
media_player.play
media_player.browserID (the correct browser ID, I checked).
It didn't worked for me, only error messages, like the picture, I attached.
But if I type the chromecast receiver's ID (media_player.htc), stream goes to the phone (not a good solution for me, only installed for test!)

**Comment by KTibow** [comment]
Can you share the real entity ID?
