### ISSUE TITLE
browser_mod.more_info does not autoplay

### ISSUE THREAD

**Issue by tunerooster** [thomasloven/hass-browser_mod#188]
Whether calling it from a script, or from Developer Tools -> Services page, browser_mod.more_info does not autoplay the camera/video.  It opens the media play window with a circle play button and does not play until the play button is clicked.

This is contrary to the way more_info work in the picture-entity or the picture-glance cards.

To reproduce, go to Developer Tools -> Services and enter:
```
service: browser_mod.more_info
entity_id: camera.frontdoor
deviceID:
  - this
large: true
```
Click "Call Service"

Camera video window displays, but does not play without further intervention.

This is particularly annoying when using an automation on a remote dashboard tablet on a wall where you then have to walk over and click play.

Thanks... browser is super great and I use it all the time!

**Comment by KTibow** [comment]
browser_mod is just calling built-in functionality.

**Comment by tunerooster** [comment]
Hmm...  OK, but I would have thought the built-in functionality would be the same from browser_mod as from picture-entity and picture-glance.

Thanks in any case...

**Comment by KTibow** [comment]
Well in normal operation, you use a user-initiated gesture to show the popup, which allows the popup to auto-play. But with browser_mod, it's from an automation.

**Comment by tunerooster** [comment]
Were you able to confirm the behavior I am experiencing?  I want to be sure it is not something I have misconfigured...

Thanks!

**Comment by tunerooster** [comment]
What does "user-initiated" gesture have to do with autoplay?  Is that something chrome does to prevent  unwanted videos from poping up on web sites or something?

**Comment by KTibow** [comment]
Basically, that’s how it works. Firefox is even stricter.
