### ISSUE TITLE
Received invalid command: browser_mod/update

### ISSUE THREAD

**Issue by reotto613** [thomasloven/hass-browser_mod#196]
My Home Assistant version: 2021.2.3 (Core), 2021.02.11 (Supervisor), and 5.12 Home Assistant OS.  Installed on Rasperry Pi 3B+

**What I am doing:**
Looking at the server logs

**What I expected to happen:**
I should not be expecting errors.

**What happened instead:**

**Minimal** steps to reproduce:
Error are present attributed to this software.

```yaml
# The least amount of code or steps possible to reproduce my error
Boot up with browser mod installed, and errors occur.
# Put your code/steps here
```
Error looks like this:
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:84
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:59:39 PM (125 occurrences)
Last logged: 1:04:49 PM

[547559828688] Received invalid command: browser_mod/update
[547559826288] Received invalid command: browser_mod/update
[547559827488] Received invalid command: browser_mod/update
[547559730864] Received invalid command: browser_mod/update

**Error messages from the browser console:**
XXXX
```
// Select everything from the browser console and copy it

// Paste it here
```
XXXX
---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X ] Have made sure I am using the latest version of the plugin.

- [X ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by KTibow** [comment]
Does it work anyway? What's your configuration in `configuration.yaml`?
