### ISSUE TITLE
Alias not replacing the device ID in the entity ID address

### ISSUE THREAD

**Issue by mwolter805** [thomasloven/hass-browser_mod#197]
My Home Assistant version:  core-2021.2.3 on Home Assistant OS running in a virtual machine.
--

**What I am doing:**
New Home Assistant user trying to setup a browser_mod alias. Browser_mod and home assistant are the latest versions. Not sure what I am doing wrong and I’ve tried to be very careful when reading the instructions and following videos. 

**What I expected to happen:**
Expect the device ID portion of the entity ID’s address to be replaced by the alias.

**What happened instead:**
In the particular browser_mod device, the device ID is replaced by the alias but for the particular device’s entities, the device ID remains in the entity ID address.

![7343ECD7-2AAE-4EC8-9908-9D42B1644C3C](https://user-images.githubusercontent.com/24851651/108598215-31c51480-7341-11eb-9380-3f90e7fb4551.jpeg)

![408E9985-5690-40A3-938F-250FA4CAA938](https://user-images.githubusercontent.com/24851651/108596425-c9bf0000-7339-11eb-8e69-36f67d992e32.jpeg)

This is not was is supposed to happen according to pinkywafer’s video or the read me. Here’s an excerpt from the readme:

Connecting with the computer named Arrakis above with deviceID: 99980b13-dabc9563 will create the entities sensor.arrakis, media_player.arrakis and light.arrakis.

**Minimal** steps to reproduce:
I have applied the alias to configuration.yaml. I’ve verified the device ID. I’ve reinstalled browser_mod. I’ve tried using a dash - in the device ID instead of an underscore _. 

![E33C0C4B-944C-4F06-A392-19E97A5F5760](https://user-images.githubusercontent.com/24851651/108596487-3e923a00-733a-11eb-814f-3ce1b582c303.jpeg)

![894248CC-C762-4CB8-9196-47E6C1A4625D](https://user-images.githubusercontent.com/24851651/108596495-45b94800-733a-11eb-8c27-45c70c0988bb.jpeg)

**Error messages from the browser console:**
No errors are reported in the home assistant logs. 

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by KTibow** [comment]
That's odd, and from what I can tell from my experience in browser_mod issues probably not your fault. You've rebooted HA, right?

**Comment by mwolter805** [comment]
Yessir, rebooted core and the server.

**Comment by KTibow** [comment]
You can always manually modify it:
![image](https://user-images.githubusercontent.com/10727862/108599617-13621780-7347-11eb-9e1f-653a58584574.png)

**Comment by mwolter805** [comment]
Thanks KTibow, Manually edited the Entity ID and it appears to work. Hopefully this help provide info to Thomas so it can be resolved or saves someone else some time. 

![BB0B3A18-41A5-4781-93E5-3074B5A752B4](https://user-images.githubusercontent.com/24851651/108599733-ce8ab080-7347-11eb-933b-a01e2583c42f.jpeg)

**Comment by stittel** [comment]
I experience the same issue. Also use the latest software versions.

**Comment by rlowens** [comment]
I just installed browser_mod and found the same issue. Renamed them by hand as suggested (though that's a little harder for the media_player entities since they aren't nested under the devices like the sensors and lights are).

**Comment by stittel** [comment]
> I just installed browser_mod and found the same issue. Renamed them by hand as suggested (though that's a little harder for the media_player entities since they aren't nested under the devices like the sensors and lights are).

I understand that it will be labour intensively. But on the other hand several people experience this problem so my expectation is that it will be resolved.

**Comment by mwolter805** [comment]
Appears this was resolved with a recent Home Assistant update, not sure which one.

**Comment by GitHubGoody** [comment]
This is an issue still/again.

**Comment by Protoncek** [comment]
Yes, i have the same problem, and the problem is not about changed device ID. Let me explain:
- i connect with my tablet with manually set deviceID, say, 22222222-22222222. I get entities with this ID. 
- then i create an alias for this ID in configuration, say, "kitchen". Restart HA.
- my tablet still has same "media_player.browser_22222222_22222222" and not "media_player.browser_kitchen". even after multiple restarts, removing / re-adding browser addon...

So, what are the steps so that in HA old entity would "dissapear"  (become unavaialble) and new one would appear?

Interesting thing is that sometimes some devices DO get replaced by alias... just not always and not all devices.
