### ISSUE TITLE
service.browser_mod.window_reload not releoding browser

### ISSUE THREAD

**Issue by clandestine-avocado** [thomasloven/hass-browser_mod#198]
My Home Assistant version: 
2021.2.3

Browser Mod v1.3.0

**What I am doing:**
Trying to reload a browser/Lovelace page that is not updating/refreshing automatically for some reason.

**What I expected to happen:**
I was expecting browser_mod.window_reload to reload the browser, the same as if I hit the refresh button in Chrome, but nothing happens. 

If I DO manually hit the refresh button in Chrome, the page reloads properly, and states are all updated.

**What happened instead:**
Nothing happens. I do not see any errors in the log.

**Minimal** steps to reproduce:
After running with no issues for over 18 months, I’m now having an problem where a Lovelace dashboard (on a Dell touchscreen monitor) freezes periodically. **When I say “freezes” I mean no states are being updated visually in Lovelace, and nothing is responsive to touch (buttons, toggles, more-info, etc). This is only within Lovelace as far as I can tell - meaning the touchscreen still works fine if I press anything outside the Lovelace dash - like another bookmark (from the toolbar for example), or hit the refresh or home button, or anything in the toolbar. So it appears to be specific to Lovelace.

This is a 24" Dell touchscreen monitor, running Chrome 88.0.4324.150, connected to a WIN10 machine. I thought I would get lucky because I DO know exactly when it last updated - because I have a digital clock card in Lovelace that gets frozen at whatever time it locked up. I have inspected the HA logs at, and around, the “freeze time” and there is nothing that jumps out at me in the logs as unusual.

The only thing that fixes it is a manual refresh of the browser, either via hitting the refresh button on the browser, or selecting a bookmark that points to the URL for my Lovelace dashboard.

I’ve tried:

- Running service.browser_mod.window_reload - [the documentation](https://github.com/thomasloven/hass-browser_mod#--window_reload) says this service is the same as hitting the refresh button on the browser. I’ve tried it with, and without, including a deviceID in the service call, and neither seem to work at all.
- Running service.browser_mod.lovelace_reload - my understanding is this shouldn’t work, and it didn’t, but I’m grasping at straws at this point.

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:**

```
auto-entities.js:2 AUTO-ENTITIES 1.7.0 IS INSTALLED 
swipe-navigation.js:50 ≡ swipe-navigation      ⋮ version 1.3.5            
multiple-entity-row.js:1  MULTIPLE-ENTITY-ROW  4.1.1 
layout-card.js:92 LAYOUT-CARD 1.3.1 IS INSTALLED 
browser_mod.js:149 BROWSER_MOD 1.3.0 IS INSTALLED    DeviceID: 942efbc8-7ed7fedf
An SSL certificate error occurred when fetching the script.
fold-entity-row.js:46 FOLD-ENTITY-ROW 19.0.0 IS INSTALLED 
slider-entity-row.js:68 SLIDER-ENTITY-ROW 1.0.0 IS INSTALLED 
card-tools.js:90 CARD-TOOLS 2.1.2 IS INSTALLED  DeviceID: 942efbc8-7ed7fedf
card-mod.js:5 CARD-MOD 2.0.3 IS INSTALLED 
simple-thermostat.js:265 simple-thermostat: 0.41.1
app.645d69e3.js:46562 Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://192.168.1.237:8123/') with script ('https://192.168.1.237:8123/service_worker.js'): An SSL certificate error occurred when fetching the script.
(anonymous) @ app.645d69e3.js:46562
async function (async)
(anonymous) @ app.645d69e3.js:46562
(anonymous) @ app.645d69e3.js:46562
setTimeout (async)
value @ app.645d69e3.js:46562
performUpdate @ app.645d69e3.js:12471
_enqueueUpdate @ app.645d69e3.js:12471
async function (async)
_enqueueUpdate @ app.645d69e3.js:12471
requestUpdateInternal @ app.645d69e3.js:12471
initialize @ app.645d69e3.js:12471
initialize @ app.645d69e3.js:12471
C @ app.645d69e3.js:12471
H @ app.645d69e3.js:12471
F @ app.645d69e3.js:43690
(anonymous) @ app.645d69e3.js:43690
(anonymous) @ app.645d69e3.js:43690
(anonymous) @ app.645d69e3.js:43690
(anonymous) @ app.645d69e3.js:43690
(anonymous) @ app.645d69e3.js:43690
(anonymous) @ app.645d69e3.js:43690
(anonymous) @ app.645d69e3.js:43690
(anonymous) @ app.645d69e3.js:43690
(anonymous) @ app.645d69e3.js:43690
(anonymous) @ app.645d69e3.js:43690
(anonymous) @ app.645d69e3.js:43690
(anonymous) @ app.645d69e3.js:43690
(anonymous) @ app.645d69e3.js:43690
xe @ app.645d69e3.js:43690
(anonymous) @ app.645d69e3.js:46562
r @ app.645d69e3.js:46450
finisher @ app.645d69e3.js:12471
runClassFinishers @ app.645d69e3.js:46450
(anonymous) @ app.645d69e3.js:46450
(anonymous) @ app.645d69e3.js:46450
(anonymous) @ app.645d69e3.js:46562
(anonymous) @ app.645d69e3.js:46562
button-card.js:425   BUTTON-CARD   Version 3.4.2 
entities.js:28   SPOTIFY-CARD   Version 2.3.7    
mini-graph-card-bundle.js:1  MINI-GRAPH-CARD  0.10.0 
swipe-card.js:21    SWIPE-CARD   Version 4.0.0 
bar-card.js:4855   BAR-CARD   Version 3.1.7    
atomic-calendar-revive.js:522  atomic-calendar-revive  Version: 3.2.1 
atomic-calendar-revive.js:522  atomic-calendar-revive  Version: 3.2.1 
[Violation] Forced reflow while executing JavaScript took 44ms
main.js:3  Thermostat Card   Version  1.3.0 
floorplan.js:65 Floorplan for Home Assistant (ha-floorplan)Version 1.0.18
[Violation] Forced reflow while executing JavaScript took 30ms

```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [ ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [ ] Have made sure I am using the latest version of the plugin.

- [ ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [ ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by KTibow** [comment]
> When I say “freezes” I mean no states are being updated visually in Lovelace

check this setting:
![image](https://user-images.githubusercontent.com/10727862/108629441-bcc30f00-7414-11eb-8e2e-d58be15fc836.png)
There's also an auto-reload-card you could try.

**Comment by clandestine-avocado** [comment]
@KTibow I'll try setting the "Automatically Close Connection" toggle to off and see if that helps. I don't really understand this setting - what causes the server to be hidden? I know next to nothing about websockets, but do have websocket related errors in my HA log. There are others in the log, but here is an example:

```
2021-02-20 21:32:44 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140665675431840] Received invalid command: browser_mod/connect
2021-02-20 21:32:52 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140665639525824] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 42, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 92, in update
    self.media_player = self.media_player or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 47, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'media_player'
```


I've tried the auto-reload-card - doesn't appear to be working either.

**Comment by KTibow** [comment]
That's just normal while browser_mod is booting up.

**Comment by clandestine-avocado** [comment]
ok - if those logs are normal, I'm still unsure why it doesn't reload the window, when hitting the "physical" refresh button does. I went ahead and rolled back to v1.2.3 and it has not frozen on me since (~24 hrs). 

I'll monitor it for a while before drawing any conclusions, but it's got me wondering if v1.3 was causing the freeze in the first place, since it hasn't happened since downgrading to v1.2.3. It would be quite a coincidence if it were something else, but it's possible I guess.

**Comment by KTibow** [comment]
Maybe. Anything resource-intensive on a low-power device could cause it to freeze.
