### ISSUE TITLE
Feature Request: add browser_mod prefix to entities for easy targeting in configs

### ISSUE THREAD

**Issue by skynet01** [thomasloven/hass-browser_mod#20]
First of amazing plugin! It's a staple in my home automation. 

Quick suggestion, anyway you can add a prefix to the generated id's. This would make it easier to figure out that these media player devices belong to Browsermod. You usually run the detect command once, but new devices appear on the network often so I always have some unknown browsermod entities floating around. 

Adding a prefix like **mod-**  to device id would help targeting devices. It would be "media_player.mod-1daa8134_e62fdffe" this would allow for customization and regex targeting in HA config. 

For example if I don't want to see any of the added browser_mod media players in my Alexa I can just exclude everything with _media_player.mod-*_  Right now there are about 50 browsermod entities in alexa (since it doesn't clear them it just adds them).

Or if I want all of my browser_mod players to have unique icon in lovelace it will be easy to target them as well.

 Maybe the prefix can be followed by first thing that's after the "(" in user agent. So `_userAgent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148_`  would add prefix iPhone to the name as well.

Thank you so much for considering this!

**Comment by thomasloven** [comment]
Great idea!
