### ISSUE TITLE
With update to core-2021.3.2 the websocket API starts complaining about invalid browser_mod/connect

### ISSUE THREAD

**Issue by kongo09** [thomasloven/hass-browser_mod#203]
My Home Assistant version: 2021.3.2

**What I am doing:**
I noticed an error log related to browser_mod showing up.

**What I expected to happen:**
No error log

**What happened instead:**

**Minimal** steps to reproduce:
I don't know what might be calling the websocket API. Unsure if this is even a problem of browser_mod or HA or something else.

**Error messages from the HA error log**

```
2021-03-07 11:26:35 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [4062882928] Received invalid command: browser_mod/connect
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by KTibow** [comment]
This means that something is trying to talk to browser-mod, but browser-mod hasn't booted up yet.

**Comment by kongo09** [comment]
Understood. The error is new and I'm not aware that I changed anything that cause this. Is there a way to find out what is trying to call browser-mod?

**Comment by KTibow** [comment]
A browser. When you load HA while browser_mod is installed, it loads up a script that tries to communicate with browser_mod via a websocket. Now you go restart HA.
It goes offline. Then it boots up. The backend websocket becomes available, and your browser connects to it. And browser_mod tries to connect. But browser_mod's backend hasn't quite loaded yet. So your browser is trying to connect; and normally your browser sends a command to HA, which browser_mod intercepts. But since it can't boot up, it can't intercept it. So you get this issue in your logs.

**Comment by kongo09** [comment]
Understood, thanks for clarifying. So bottom-line here is: this should be ignored?

**Comment by KTibow** [comment]
Yes. It's just a byproduct of browser_mod taking a while to boot up.

**Comment by kongo09** [comment]
Before this is closed automatically, let's rather make this a conscious decision.

In my setup, no other integration produces a similar error. I still feel, this should be addressed somehow. Its there not a way for the frontend to signal to browser_mod that HA is starting so that it doesn't try to connect a still booting system?
