### ISSUE TITLE
Issue while changing volume

### ISSUE THREAD

**Issue by PePeLLee** [thomasloven/hass-browser_mod#204]
My Home Assistant version: 2021.3.2

**What I am doing:**
I try to change volume on my tablet from PC (home assistant lovelace gui - media control widget)

**What I expected to happen:**
Change volume

**What happened instead:**
No change

**Minimal** steps to reproduce:
Configure browser_mod on 1 device, play some media, change volume

**Error messages from the browser console:**
browser_mod.js:149 Uncaught (in promise) TypeError: t[e.command.replace(...)] is not a function
    at T.msg_callback (browser_mod.js:149)
    at Object._connection.subscribeMessage.type [as callback] (browser_mod.js:149)
    at a._handleMessage (core.a3d9350b.js:1)
    at WebSocket.<anonymous> (core.a3d9350b.js:1)

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by PePeLLee** [comment]
It seems there is typo "-" vs "_". I'm not good at js but maybe that is a problem:
![image](https://user-images.githubusercontent.com/61408245/110752210-3cd6da80-8245-11eb-9ad4-462a3e2cae18.png)

**Comment by KTibow** [comment]
Can you make a PR then?

**Comment by prigal** [comment]
Same problem here, happy to see that the fix is coming :) 

Thanks !
