### ISSUE TITLE
Call from Node Red?

### ISSUE THREAD

**Issue by jimmyeao** [thomasloven/hass-browser_mod#206]
Is it possible to call this from node red? I just want to be able to send a toast notification when something happens to all devices

**Comment by KTibow** [comment]
It's a service. As long as you can call a service from node-red, it should work.

**Comment by jimmyeao** [comment]
The issue is, it has no domain (like light, switch, notify etc) so I’m struggling to see how I can call it from nodered unless I set up a virtual switch linked to a service and trigger an automation from node red.

Jimmy White
________________________________

**Comment by KTibow** [comment]
No, it's a service. The domain is `browser_mod`.

**Comment by jimmyeao** [comment]
Ah, got it!

Thanks, may be worth adding to the readme?
![image](https://user-images.githubusercontent.com/5197831/112279496-e5406200-8c7b-11eb-81c2-e569c995dc8b.png)

**Comment by KTibow** [comment]
IMO this is a more general thing that new Node Red with HA users learn, not necessarily specific to browser_mod.
