### ISSUE TITLE
many entities and devices in the browser mod integration?

### ISSUE THREAD

**Issue by jenniferlee1818** [thomasloven/hass-browser_mod#208]
![image](https://user-images.githubusercontent.com/44507767/112848292-27471a80-9065-11eb-9af4-bc6c4e4f5a06.png)
![image](https://user-images.githubusercontent.com/44507767/112847778-a5ef8800-9064-11eb-85c4-5b5e752f60e7.png)
![image](https://user-images.githubusercontent.com/44507767/112847869-bbfd4880-9064-11eb-905b-a14c599b94a6.png)
![image](https://user-images.githubusercontent.com/44507767/112848151-fe268a00-9064-11eb-9a7f-59e485ee46d3.png)

What is all this?

**Comment by KTibow** [comment]
If you use private browsing, or clear your cache / cookies, it keeps old devices.

**Comment by mpejstrup** [comment]
@KTibow 
Is there a solution or do you just leave it?

**Comment by KTibow** [comment]
Either uninstall and reinstall the integration, or delete the devices/entities.

**Comment by mpejstrup** [comment]
Will try that. Just feels like the entities keeps coming even though

**Comment by KTibow** [comment]
You can always try changing your domain, securing your passwords, and logging into HA only where needed.

**Comment by jenniferlee1818** [comment]
I only have four browser mod devices set up in configuration.yaml.   Where do the other (27) devices come from?

**Comment by KTibow** [comment]
I don't know. It registers browsers that aren't set up by default, you need to set up https://github.com/thomasloven/hass-browser_mod#disabling-entities to disable that.

**Comment by GerdBlomb** [comment]
Same here: more than 350 Objekts by browser_mod. Mostly with a red icon. In less than two weeks.

And the list is growing.

I think we need a garbage collection here.

**Comment by KTibow** [comment]
So if this does get implemented, how do you think garbage collection should be implemented? Should it need you to move your mouse or be on the page for at least a few seconds? Should it auto-delete devices that haven't connected in a week (configurable)?

**Comment by GerdBlomb** [comment]
At the moment i delete all items which have a "red icon". Lately around 350 items (i use the add on for around 10 days). 

It seams that every cookie clearance in the browser leads to new entries on connect. One of the reasons to go the stony HA way is privacy. Preserving browser data like cookies etc. can not be a solution....

**Comment by KTibow** [comment]
> Preserving browser data like cookies etc. can not be a solution....

That's how browser-mod works. It generates a unique ID, and stores it in localStorage.

**Comment by GerdBlomb** [comment]
Thats absolute clear to me. But i think this should be somehow improved. Maybe. I can not judge this.

**Comment by thomasloven** [comment]
Then how should browser_mod preserve the browser id?

It uniquely identifies your browser - one of the biggest no-nos in all of browser security, so if you're worried about cookies you shouldn't be using it at all.

Try running the service `browser_mod.clean_devices` to clean up the list.

**Comment by drjjr2** [comment]
Is there a way to find out where the device came from? Recently I've also had the problem of multiple devices showing up in the list that then almost immediately become unavailable.

**Comment by thomasloven** [comment]
Only the user agent string in the sensor attribute. Again, browsers do everything they can to avoid being uniquely identifiable, so there's nothing but the deviceID.

**Comment by drjjr2** [comment]
I suspect my iPhones when coming & going are getting new IDs. But I also get notified of new devices being added when I'm not even at home...

**Comment by thomasloven** [comment]
Maybe you should change your password?

**Comment by DannyFeliz** [comment]
This still a problem today, and it looks like the `browser_mod.clean_device` is not a thing anymore
