### ISSUE TITLE
Can not uninstall Browser Mod (without remaining errors)

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/hass-browser_mod#209]
My Home Assistant version:2021.4.0b6

**What I am doing:**
trying to delete browser_mod, but errors keep showing in the log
and Notification is shown:

<img width="468" alt="Schermafbeelding 2021-04-07 om 19 55 52" src="https://user-images.githubusercontent.com/33354141/113912364-5125dd00-97db-11eb-9a2e-6fd806fc9a64.png">

**What I expected to happen:**

Browser_mod to be uninstalled
**What happened instead:**

**Minimal** steps to reproduce:
- deleted browser_mod config in configuration.yaml
- deleted the entry in resources
- deleted the folder in custom_components
- disabled the integration in Integrations
- of course, restarted, refreshed cache multiple times etc etc
<img width="316" alt="Schermafbeelding 2021-04-07 om 19 54 22" src="https://user-images.githubusercontent.com/33354141/113912133-17ed6d00-97db-11eb-92b5-577a2a0d4986.png">

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it
2021-04-07 19:35:49 ERROR (MainThread) [homeassistant.setup] Setup failed for browser_mod: Integration not found.
----
2021-04-07 19:36:29 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2856462032] Received invalid command: browser_mod/update
2021-04-07 19:36:39 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2856462032] Received invalid command: browser_mod/update
2021-04-07 19:36:49 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2856462032] Received invalid command: browser_mod/update

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by KTibow** [comment]
It's still in the internal configured integrations file. You need to delete it, not just disable it. It looks like disabling is just disabling all configured devices.

**Comment by Mariusthvdb** [comment]
A third restart made it happen...
Meanwhile I have reinstalled because the reason I wanted to test has proven unsubstantiated. 

Thanks for you comments though ;-)
