### ISSUE TITLE
how should i use "deviceID" in script?

### ISSUE THREAD

**Issue by niccolobusato** [thomasloven/hass-browser_mod#21]
How should i write the script in the front-end to use the "deviceId"?

this work:
`{
  "command": "blackout"
}`

this do not work:
`{
  "command": "blackout",
  "deviceID": "my_device"
}`

which one is the right syntax to use?

**Comment by skynet01** [comment]
it's a little confusing since entities have a syntax with underscore: ex "d2fc860c_16379d23" but inside commands you have to use dashes. So in your example it would have to be:
 { "command": "blackout", "deviceID": "d2fc860c-16379d23" }  and not "d2fc860c_16379d23"

**Comment by niccolobusato** [comment]
this is not working anyway..

but thanks for the quick reply.

is correct to set "deviceID" just under "command"?

**Comment by thomasloven** [comment]
DeviceID should be a *list*, i.e. `[ "12345678-12345678"]`.
