### ISSUE TITLE
Media_player entities aren't associated with devices like sensors and lights are

### ISSUE THREAD

**Issue by rlowens** [thomasloven/hass-browser_mod#212]
My Home Assistant version: core-2021.4.4

**What I am doing:**
Using Configuration->Integrations->browser_mod click on number of devices to see all devices in browser_mod, then click each device to go rename all the entities inside of it.

**What I expected to happen:**
Each device should show the light_, sensor_, media_player_ entities under it, but only the light_ and sensor_ entities appear there.

**What happened instead:**
The media_player_ entities aren't associated with any device, just with the browser_mod integration.

**Minimal** steps to reproduce:
In Configuration->Devices click any device in browser_mod and see that only the sensor_ and light_ entities are shown.

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

![media_browser not related to device](https://user-images.githubusercontent.com/35885181/114494809-376d0700-9bda-11eb-846b-e4c1cf14cc04.png)
![device only shows light ans sensor](https://user-images.githubusercontent.com/35885181/114494812-376d0700-9bda-11eb-8aa0-fe88aefbbed8.png)
![light is related to device and sensor](https://user-images.githubusercontent.com/35885181/114494813-38059d80-9bda-11eb-836f-790d228e75bb.png)

**Comment by thomasloven** [comment]
Cannot reproduce.
Try removing the device and reloading it.
