### ISSUE TITLE
Unable to load popup on some cards

### ISSUE THREAD

**Issue by ThePicklenat0r** [thomasloven/hass-browser_mod#22]
Coming from popup-cards. Is it possible to cause a popup from tapping a card that doesn't support tap-actions? In popup-cards I could use the weather card or mini-graph-card and tapping them would bring up a popup. Since neither of these support tap_actions (that I know of?), I'm not sure how/if this is possible.

edit: mini-graph-card does have a tap_action feature, but haven't gotten it to work yet, still playing with it. The question still stands for the built in weather-forcast card, though.

**Comment by thomasloven** [comment]
https://github.com/thomasloven/hass-browser_mod/releases/tag/15
