### ISSUE TITLE
Can't create popup with deviceID "this"

### ISSUE THREAD

**Issue by mariosoliman** [thomasloven/hass-browser_mod#220]
My Home Assistant version: 2021.4.6

**What I am doing:**
Trying to show a simple popup with light entity with deviceID "this". Using the deviceID or no deviceID at all works, but I need it to always work on the current device only. Is there an alternative?

**What I expected to happen:**
A popup should show up with the following

![image](https://user-images.githubusercontent.com/14789748/117183208-e4cbd880-ad9c-11eb-9408-899a3898340c.png)

**What happened instead:**
Nothing shows up

**Minimal** steps to reproduce:
Here's my service call

```yaml
service: browser_mod.popup
data:
  title: Test
  card:
    type: light
    entity: light.bedroom_light
  deviceID:
    - this
```

**Error messages from the browser console:**
Nothing happens and I don't see errors.

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by drjjr2** [comment]
I think this might help:
[](https://github.com/thomasloven/hass-browser_mod/releases/tag/1.3.0)

**Comment by mariosoliman** [comment]
> I think this might help:
> https://github.com/thomasloven/hass-browser_mod/releases/tag/1.3.0

Ah, thank you!
