### ISSUE TITLE
Integration card menu pops under other cards in Chrome

### ISSUE THREAD

**Issue by tykeal** [thomasloven/hass-browser_mod#223]
My Home Assistant version: core-2021.5.3

**What I am doing:**

I go to Configuration -> Integrations and select a triple dot menu on a card that has cards surrounding it

**What I expected to happen:**

The menu will pop over the cards

**What happened instead:**

The menu pops under the cards. The menu may pop-over other cards if it hit it before the page completely loads, but after it fully loads it always ends up under other cards!

If I turn off browser_mod and remove the Lovelace resource and force a refresh then menus start working correctly again.

I have even fully purged my chrome caches (directly on disk while chrome was not running and then started chrome forcing me to login everywhere again).

**Minimal** steps to reproduce:

* Install browser_mod via HACS
* Turn on browser mod via configuration.yaml
* Verify configuration and restart HA
* Add /browser_mod.js to lovelace resource
* Force refresh of browser
* Go to Configuration -> Integrations
* Select triple dot menu of top left card
* Observe menu popping under other cards

**Error messages from the browser console:**

```
auto-entities.js:194 AUTO-ENTITIES 1.8.5 IS INSTALLED 
card-tools.js:90 CARD-TOOLS 2.1.2 IS INSTALLED  DeviceID: 1eb062fc-5dcdde21
fold-entity-row.js:42 FOLD-ENTITY-ROW 20.0.4 IS INSTALLED 
numberbox-card.js:3 NUMBERBOX_CARD 2.7
scheduler-card.js:1646   SCHEDULER-CARD    Version: v2.1.2 
kiosk-mode.js:49 ≡ kiosk-mode            ⋮ version 1.6.5            
tempometer-gauge-card.js:1  TEMPOMETER-CARD       v1.3       
lovelace-card-templater.js:8   CARD-TEMPLATER   Version 0.0.9  
utils.ts:3  BATTERY-STATE-CARD  1.6.4
card-mod.js:5 CARD-MOD 3.0.12 IS INSTALLED 
kiosk-mode.js:37 Uncaught (in promise) ReferenceError: regeneratorRuntime is not defined
    at v (kiosk-mode.js:37)
    at k (kiosk-mode.js:37)
    at kiosk-mode.js:44
v @ kiosk-mode.js:37
k @ kiosk-mode.js:37
(anonymous) @ kiosk-mode.js:44
Promise.then (async)
(anonymous) @ kiosk-mode.js:43
icon.png:1 GET https://brands.home-assistant.io/browser_mod/icon.png 404
browser_mod.js:142 BROWSER_MOD 1.3.1 IS INSTALLED    DeviceID: 1eb062fc-5dcdde21
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
This is an upstream Home Assistant problem.
