### ISSUE TITLE
Autoclose on mouse movement

### ISSUE THREAD

**Issue by mleiber** [thomasloven/hass-browser_mod#226]
When setting `auto_close: true`, on touch screen devices (e.h. phones and tablets) everything works as expected and it provides a nice user experience for e.g. a grid of favorite buttons to select from in a pop-up menu.

On the desktop in the browser `autoclose` though is not usable at all (or something is  wrong with my setup). Moving the mouse immediately closes the pop-up window.

Would it make sense to provide an option to disable `autoclose` on mouse movement - or make it that way right away - I don't see how close on mouse move would make sense at all.

**Comment by mutzl** [comment]
I totally agree. 
I don't see a use case for auto-closing on mouse movement. 

So currently `auto_close: true` it is a show stopper for me.

**Comment by thomasloven** [comment]
Closed because of Browser Mod 2.0 release.
Please see #354.

**Comment by mleiber** [comment]
I don't think the issue is resolved. With the 2.x release I see the same behavior as before - any mouse movement immediately closes the popup. Thus autoclose is still not usable on a mouse-driven device.
