### ISSUE TITLE
Unable to uninstall from HA

### ISSUE THREAD

**Issue by jaswalters** [thomasloven/hass-browser_mod#228]
My Home Assistant version: 1.3.1

I remove the integration from supervisor/integrations
I even tried to remove entry line from config file before removal but then it complained in the logs about that as an issue.

Integration to be removed after restart of HA

After restart integration still exists
Currently the integration does not exist under integrations and it does not exist within HACS and there is no line in the config file for the module but after every restart i see the below in the logs.
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:87
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 2:41:16 PM (23 occurrences)
Last logged: 2:44:11 PM

[139718608800208] Received invalid command: browser_mod/update

Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:482
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 2:41:39 PM (1 occurrences)
Last logged: 2:41:39 PM

Component error: browser_mod - Integration 'browser_mod' not found.

Delete integration from integrations page
Restart HA

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [ X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [ X] Have made sure I am using the latest version of the plugin.

- [ X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [ X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by jaswalters** [comment]
I thought I resolved the issue but it is partially resolved.

**Comment by yargok** [comment]
Having this issue too -

**Comment by fredericomcorda** [comment]
Hi, having same issue, any suggestion how to solve?
