### ISSUE TITLE
HA 2021.5.5, Error during setup of component browser_mod

### ISSUE THREAD

**Issue by adizag** [thomasloven/hass-browser_mod#230]
My Home Assistant version: 2021.5.5

**What I am doing:**
restarting HA

**What I expected to happen:**
nothing

**What happened instead:**
browser_mod loading error

**Minimal** steps to reproduce:
Installed through HACS, worked before, suddenly notice it Is not working and saw the error in the logs
tried to uninstall and reinstall the plugin - no help.

**Error messages from the browser console:**

```
Logger: homeassistant.setup
Source: custom_components/browser_mod/__init__.py:39
Integration: browser_mod (documentation)
First occurred: 21:33:17 (1 occurrences)
Last logged: 21:33:17

Error during setup of component browser_mod
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 248, in _async_setup_component
    result = await task
  File "/config/custom_components/browser_mod/__init__.py", line 39, in async_setup
    for d in config[DOMAIN].get(CONFIG_DEVICES, {}):
KeyError: 'browser_mod'
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by adizag** [comment]
solved by the hand of God... just solved itself...

**Comment by Th30wl** [comment]
It started happening to me on each HA start since 2021.7 update
HA version: 2021.7.3
Supervisor version: 2021.6.8

```
This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/browser_mod/__init__.py:39
Integration: browser_mod (documentation)
First occurred: 12:51:22 AM (1 occurrences)
Last logged: 12:51:22 AM

Error during setup of component browser_mod
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 249, in _async_setup_component
    result = await task
  File "/config/custom_components/browser_mod/__init__.py", line 39, in async_setup
    for d in config[DOMAIN].get(CONFIG_DEVICES, {}):
KeyError: 'browser_mod'

```

**Comment by Th30wl** [comment]
This also happens if `browser_mod:` entry is missing from configuration.yaml
