### ISSUE TITLE
Touch events

### ISSUE THREAD

**Issue by bublikOff** [thomasloven/hass-browser_mod#232]
It would be nice to have ability to catch touch events in HA automation.
For eg I want dim display brightness while idle and light it up again on any display touch.

**Comment by DivanX10** [comment]
This function can be implemented via fully kiosk. The Home Assistant has fully kiosk + integration put it on the tablet. Thanks to fully kiosk, you can adjust the brightness or turn on the screen by double tap. You need to turn on the vibration sensor for high sensitivity. You can turn on the screen remotely, for example, you opened the door or turned on the light and the tablet screen turned on. You can display the tablet sensors in the HA, for example, monitor the charge level of the tablet and turn on the smart socket to charge the tablet. You can output audio to the tablet. fully kiosk has great features.
![image](https://user-images.githubusercontent.com/64090632/121801601-cd57f900-cc40-11eb-908f-a9adc73840c0.png)

**Comment by thomasloven** [comment]
As mentioned. Fully Kiosk Browser can do this by itself.
For other browsers, the screen brightness cannot be controlled, but otherwise this sounds like exactly why the `time` option for the `blackout` function exists.

**Comment by Jpsy** [comment]
I don't think that the core of this feature request is met by the answers. It is about reporting touch events to HA. (Lighting up the display with it was only an example.)

Maybe a better usage example would be: 
When idle (=not touched) for some time I want to close any popups that were left open.

This is currently not possible, not even through Fully. 
If this makes sense it would be great to reopen the request. I actually see many interesting use cases for it.

**Comment by bublikOff** [comment]
> I don't think that the core of this feature request is met by the answers. It is about reporting touch events to HA. (Lighting up the display with it was only an example.)
> 
> Maybe a better usage example would be: When idle (=not touched) for some time I want to close any popups that were left open.
> 
> This is currently not possible, not even through Fully. If this makes sense it would be great to reopen the request. I actually see many interesting use cases for it.

As for me Ive made a system service which monitors touch events on system level ... and report it to HA ... so now HA know that touch screen was touched by someone

**Comment by Jpsy** [comment]
> ... a system service which monitors touch events on system level ... and report it to HA

Wow! So you have the solution in hands. Could you share it? Maybe share it for all in the HA forum and link it here?

**Comment by bublikOff** [comment]
> > ... a system service which monitors touch events on system level ... and report it to HA
> 
> Wow! So you have the solution in hands. Could you share it? Maybe share it for all in the HA forum and link it here?

It will work only with touch screen connected directly to HA server hardware ... for me my touch screen connected to mini PC (GMK with  J4125) ... which work as HA server and it also shows HA GUI on connected touch screen.
so here is touch events service file

Script file
```
#!/bin/bash

function RT
{
    declare line_l;
    for line_l in "${@:2}"; 
    do 
        if ! [[ "$line_l" =~ $1 ]];
        then
            return 1;
        fi
    done
    return 0;
}

#
evtest /dev/input/by-id/usb-TSTP_MTouch_CMTP_1.0-event-if00 | while read line; do

    if RT "type 1 \(EV_KEY\), code 330 \(BTN_TOUCH\), value 1" "$line"; then
        curl \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer <LONG_LONG_AUTH_KEY>" \
            --request POST \
            --data '{"event": "touch"}' \
            -s http://192.168.88.10/api/events/panel > /dev/null
    fi

```

Service file
```
[Unit]
Description=Kiosk Touch Screen event monitor
After=network.target

[Service]
Environment=DISPLAY=:0
Type=simple
ExecStart=/bin/bash /u01/kiosk-touches.sh
Restart=always
RestartSec=5s

[Install]
WantedBy=multi-user.target

```

And something like that in HA
```
  - alias: "System: Touch events handler"
    trigger:
      - platform: event
        event_type: panel
        event_data:
          event: "touch"
    action:
      - service: timer.start
        data:
          entity_id:
            - timer.panel_touch_debounce
            - timer.panel_idle_timeout

```

1) <LONG_LONG_AUTH_KEY> - must be replaced with your own
2) /dev/input/by-id/usb-TSTP_MTouch_CMTP_1.0-event-if00 - must be replaced with correct path to your touch device
3) http://192.168.88.10/ - must be replaced with your HA address
