### ISSUE TITLE
Add media_seek functionality to media_player to allow for replay/skip capabilities.

### ISSUE THREAD

**Issue by rnotley** [thomasloven/hass-browser_mod#233]
It doesn't appear the media_player.media_seek service is usable on the media_player entity created by browser_mod.  Poking around the code, it looks like browser_mod creates an Audio() object in JavaScript, but just didn't add the capabilities to track the media position or ability to seek.

The use case for doing this: to play podcasts on the browser and use lovelace buttons to rewind -10s or skip +10s while the media is playing.  I'm able to do this with other media_player entities like an Amazon Echo device.  But I really want to do this directly from the audio of a tablet running Fully Kiosk Browser.

**Comment by thomasloven** [comment]
Closed because of Browser Mod 2.0 release.
Please see #354.
