### ISSUE TITLE
deviceID when using home companinion

### ISSUE THREAD

**Issue by sylviepipi** [thomasloven/hass-browser_mod#236]
I regular get a new deviceID on my ipad kios, no clue why. Don't cleany cookies and i do use "home companion" as my kiosk browser. can browser_mod be home companion aware, (or home companion be browser_mod aware to always make sur i have the same device id.

**Comment by sylviepipi** [comment]
I now use the device_id=..... to reset it regularly, but it requires a manual visit... 

Additionally i notice that browser_mod is not available when i reboot home assistant untill I forcefully restart the home companion... I did ask a feature on the home companion to be able to 'restart' using a home assistant service call.

**Comment by thomasloven** [comment]
Closed because of Browser Mod 2.0 release.
Please see #354.
