### ISSUE TITLE
Browsermod audio player doesn't work because of generated ID

### ISSUE THREAD

**Issue by jsormani** [thomasloven/hass-browser_mod#237]
Sometimes browser mod generates an ID with a minus between the two codes , so 999d6be5-ed815d53 in stead of 999d6be5_ed815d53 per example. This causes playback to fail if any of the selected players in the automation has this error. If you manually change the ID it works again.

**Comment by thomasloven** [comment]
I don't understand the problem description. Please use the issue template to help you make sure enough information is supplied.
