### ISSUE TITLE
Integration not found

### ISSUE THREAD

**Issue by maxbec** [thomasloven/hass-browser_mod#241]
Hey guys,

i just tried to uninstall and re-install the browser-mod integration.
I deleted all entries from configuration.yaml and removed the integration in HACS.

Then i reinstalled it but now if i want to add it under Settings -> Integrations there is no browser-mod integration to add.

Any ideas how to fix that?

**Comment by ifuchs** [comment]
I have a similar problem. I added custom_components/browser_mod to /config/custom_components/browser_mod and when I do a Check Configuration, HA says the configuration is invalid 
Component error: browser_mod - Integration 'browser_mod' not found

**Comment by chey** [comment]
manual install (without HACS) does not work. the integration isn't found in "+ ADD INTEGRATION"

HA OS: 2021.12.7

**Comment by KTibow** [comment]
Have all of you guys tried clearing your cache?

**Comment by chey** [comment]
> Have all of you guys tried clearing your cache?

Yes. I'm able to get other custom components to show up except this one. For example, i can get the [blueprint_integration](https://github.com/custom-components/integration_blueprint) to show up.

**Comment by xiNeRoar** [comment]
> Hi! The only difference here is that I've simply installed it from HACS. Should I have also manually added anything anywhere?

what is the name of the browser mod in HACS? I couldn't find it and I am having the same issue while manual install...it is so weird that no one encountered this problem besides us?

**Comment by KTibow** [comment]
@xiNeRoar this 
![image](https://user-images.githubusercontent.com/10727862/152648065-3940c0cc-cd19-44fc-b6ca-c5888c982b80.png)

**Comment by Blackbird2k** [comment]
@xiNeRoar I don't know if it helps but I had the same problem. But it was not a problem, I just looked in the wrong category. The download is only visible under Integrations and not under Frontend.

**Comment by telmomarques** [comment]
For manual installs:
1. Copy the files to custom_components folder
2. **RESTART**, if you don't you'll get the "integration not found" error
3. Add `browser_mod:` to `configuration.yaml`
4. Restart again, "Browser Mod" should now appear on Integrations screen

**Comment by evilrip** [comment]
> For manual installs:
> 
> 1. Copy the files to `custom_components` folder
> 2. **RESTART**, if you don't you'll get the "integration not found" error
> 3. Add `browser_mod:` to `configuration.yaml`
> 4. Restart again, "Browser Mod" should now appear on Integrations screen

That solved it for me. Thanks @telmomarques :)

**Comment by tenkaibr** [comment]
> For manual installs:
> 
>     1. Copy the files to `custom_components` folder
> 
>     2. **RESTART**, if you don't you'll get the "integration not found" error
> 
>     3. Add `browser_mod:` to `configuration.yaml`
> 
>     4. Restart again, "Browser Mod" should now appear on Integrations screen

Does it show up on the Integrations screen? Here it does not appear and is not working.
