### ISSUE TITLE
Can't close popup on IOS app 

### ISSUE THREAD

**Issue by Berto93** [thomasloven/hass-browser_mod#243]
Hello! unfortunately i can't close popup by touching anywhere out of cards on mobile ios app. If i use desktop everything goes fine.
Any tips? Thank you

**Comment by ischorr** [comment]
Same here on Android.  It's like the full screen registers as part of the popup instead of the actual card.  You have to specifically hit "back" (or the "X" if header isn't hidden) to close the popup

**Comment by marcusforsberg** [comment]
I have the same issue on the iOS mobile app for popups that don't have a header. Since the popup is full-screen there's no way to tap outside of it to close it.
