### ISSUE TITLE
Unable to displaying a popup via a script in the latest version browser_mod and cardmod

### ISSUE THREAD

**Issue by horacecar** [thomasloven/hass-browser_mod#25]
Unable to displaying a popup via a script in the latest version browser_mod and cardmod
nonething pop up when i use this example, but service: browser_mod.popup can use in the entity tap action, cannot use in script.

HA VERSION: 99.3

scripts.yaml

test_popup:
  sequence:
    - service: browser_mod.popup
      data_template:
        deviceID: "{{ deviceID }}"
        title: Testing script
        card:
          type: entities
          entities:
            - light.bed_light
ui-lovelace.yaml

...
  - type: entity-button
    entity: sun.sun
    tap_action:
      action: call-service
      service: script.test_popup
      service_data:
        deviceID:
          - this

**Comment by ebnerjoh** [comment]
Have the same issue here...

**Comment by thomasloven** [comment]
Please, try `deviceID: this` in lovelace.

**Comment by ebnerjoh** [comment]
You mean in the "scripts.yaml"?

**Comment by Dino-Tech** [comment]
Can confirm that `deviceID: this` in lovelace per the Cookbook, works on my Android v10 using FKB *and* Chrome. Have not been successful with my wife's iPhone.

**Comment by horacecar** [comment]
> Please, try `deviceID: this` in lovelace.

After update to HA 0.106.5 and latest version of browser_mod , even deviceID: this is not working anymore, but if it Specify give it a deviceID: c9f5fd48-51c9f5fd , then i works
