### ISSUE TITLE
Every time a new device-ID

### ISSUE THREAD

**Issue by sohnvonoff** [thomasloven/hass-browser_mod#251]
I have the following problem with the device IDs. For my tablet (fully) and smartphone it works fine.
But a new device ID with new devices is created on my workstation PC with Firefox every time the browser is started. Incognito mode is not active!
When you quit Firefox, all cookies are deleted.

One can prevent recreate the device ID in certain device/browser?

**Comment by poudenes** [comment]
Have same issue... Asked this also on the forum of HA. Disable the option "Enable newly added entities" didn't work for me.

**Comment by DivanX10** [comment]
How to turn off littering in the Home Assistant with incomprehensible devices? They are really already cluttering up the entire Home Assistant
![image](https://user-images.githubusercontent.com/64090632/132901127-669efcea-6f62-4c5e-8ae0-7ea04f812ec3.png)

**Comment by fmonday** [comment]
Same thing here with the numerous inactive IDs, and apparently the only way to delete them is to hunt for them in the system files in .storage. 
Also I'm unable to override the new IDs by changing it in the media_player; it appears to have changed and is sticky in the player itself, but the sensors/etc don't change over to the newly indicated ID and commands don't work using that deviceID.

**Comment by knarf6969** [comment]
I had the same issue. I updated my web browser (Firefox) and everything is back in order.

**Comment by DivanX10** [comment]
> I had the same issue. I updated my web browser (Firefox) and everything is back in order.

updating the browser has nothing to do with it, you might as well clear the cache files. The browser mod integration itself spams entities, generating a bunch of incomprehensible entities and I delete them when too many of them accumulate

**Comment by Stupco** [comment]
Also have this issue, really love the pop-up function, but the cluttering of my devices is crazy:

Browser Mod
125 devices and 75 entities

**Comment by KTibow** [comment]
By the way, try uninstalling/reboot/reinstalling, and check `.storage` for the entity/device files (you might be able to clear them).

**Comment by Buster14** [comment]
Hi i have same issue,
i'm running nativefier'ed HA instance on my NUC dashboard.
Is there anyway to lock the device id?
Can't use android / ios since i'm using NUC, so its either windows (what i'm using right now) or linux,
either one of them can only use chrome.
