### ISSUE TITLE
How to remove?

### ISSUE THREAD

**Issue by Patrick1610** [thomasloven/hass-browser_mod#252]
Hi, 
I have removed browser mod since I currently have no use for it, but the devices/entities keep existing. 
How can I remove these? Also, if I in the future do install it again, how do I prevent it making all these devices/entities?

![Screenshot 2021-09-12 at 10 53 34](https://user-images.githubusercontent.com/6585375/132981463-8416fed3-a977-4207-a5aa-7df5662517dd.png)

**Comment by ShlomiPorush** [comment]
If you what to remove these devices/entities install it again and call the service 'browser_mod.clean_devices'. 
To prevent automatic creation of devices / entities add this to your configuration.yaml

```
browser_mod: 
  disable:
    - all
```

**Comment by J-o-h-n-M** [comment]
I reinstalled it, but there is no service 'browser_mod.clean_devices' to delete it. I uninstalled it some time ago, and just want to get rid of the trash it left.

**Comment by ahmaddxb** [comment]
I get this when I try

![image](https://user-images.githubusercontent.com/43728586/141924798-70295055-544b-4931-bfe5-482e021ad4a7.png)

**Comment by ahmaddxb** [comment]
After a restart the call serviced worked
