### ISSUE TITLE
Hide header when replacing more-info dialogs

### ISSUE THREAD

**Issue by Stephan1908** [thomasloven/hass-browser_mod#253]
Hi there,

Hi there,
is it possible to hide the header? when replacing more-info dialogs?
so that only the card is shown: 

![replace](https://user-images.githubusercontent.com/60405276/134238624-315a87a5-2880-4847-bff0-0cac68a24a7e.PNG)

Thank you,

Greetings Stephan

**Comment by dykandDK** [comment]
It is already possible to hide the header by using hide_header: true in the code where you are replacing the more-info dialogs

**Comment by thomasloven** [comment]
Closed because of Browser Mod 2.0 release.
Please see #354.
