### ISSUE TITLE
Get actual navigation_path possible?

### ISSUE THREAD

**Issue by ManniTom** [thomasloven/hass-browser_mod#257]
i use the navigate function.
Is it possible to read out the actual navigation path (view or url)?
This is needed to return to this view, after an automation has changed the view by using navigate.
When that automation ends, i want to automatically return to the previous view.
Only thing that is needed is to get the actual navigation path (view or url)

**Comment by jenniferlee1818** [comment]
this is how i do it
```
service: input_text.set_value
target:
  entity_id: input_text.view_path_before_navigate
data:
  value: >-
    {% if not state_attr('sensor.jennifer_kt107_app', 'path') == None %}           
    {{ state_attr('sensor.jennifer_kt107_app','path') }}          
    {% endif%}
```

**Comment by ManniTom** [comment]
Thanks, Jen,
i got it working with your help!
key was your info where to look for the right entity and attribute.
Since i use AppDaemon, i can now read, set and restore the view like this:
   Automate.love_navi_path = self.entities.sensor.browser_mod_e27acee2_8ccccf45["attributes"]["path"]
   self.call_service("browser_mod/navigate", entity_id = "all", navigation_path = "/lovelace/video")
   ...
   #restore
   self.call_service("browser_mod/navigate", entity_id = "all", navigation_path = Automate.love_navi_path)

happy :)
