### ISSUE TITLE
Feature request: disable creating devices

### ISSUE THREAD

**Issue by bruxy70** [thomasloven/hass-browser_mod#26]
Can I disable creating the `sensors`, `lights` etc if I only want to use this on `this` device (as a replacement of the popup card)?

**Comment by skynet01** [comment]
I like this idea too, once devices and their aliases are setup i don't want to see new ones showing up :)

**Comment by Sjeff** [comment]
Great idea!
Maybe its possible to make light, media_player and sensor a 'opt-in' like camera and binary_sensor.

**Comment by skynet01** [comment]
> Great idea!
> Maybe its possible to make light, media_player and sensor a 'opt-in' like camera and binary_sensor.

I like that idea too, it can be just an option in the config on what sensors you want created. I for example just use the popup and screen turn off feature so i dont need any other sensors created.

**Comment by thomasloven** [comment]
Fixed.
