### ISSUE TITLE
Disable popup title tooltip

### ISSUE THREAD

**Issue by matt8707** [thomasloven/hass-browser_mod#264]
In popups, the title follows the mouse cursor. Is it possible to rename that variable to disable the tooltip?

`<card-tools-popup title="Balkong">` conflicts with [HTML title Attribute](https://www.w3schools.com/tags/att_title.asp)

![1](https://user-images.githubusercontent.com/36163594/140602791-d6bedc20-8678-4b10-838b-856f8afd711a.png)

**Comment by thomasloven** [comment]
Closed because of Browser Mod 2.0 release.
Please see #354.
