### ISSUE TITLE
I can't create EMPTY automations after I installed Browser Mod

### ISSUE THREAD

**Issue by pickonedev** [thomasloven/hass-browser_mod#266]
My Home Assistant version: core-2021.11.2

**What I am doing:**
I am trying to create a new EMPTY automation

**What I expected to happen:**
It should open the screen with "New Automation"

**What happened instead:**
The screen for "New Automation" it is closing instantly

**Minimal** steps to reproduce:
I go to "Automations", click "Add Automation", and if I click "Start with an empty automation", it is showing me the screen of new automation creation and in not even one second, it dissapears and it is taking me into the list of old autoamtion, back.

**Workaround** if is possible:
The only workaround is to click "Add Automation", then click on "CREATE", not "start with an empty automation", then  click on Skip, and I'm in the "New automation" creation screen...

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```
BROWSER_MOD 1.5.1 IS INSTALLED
    DeviceID: 75cbbd5a-e8d77e94
---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by pickonedev** [comment]
Another issue, after some time, the mobile HA app it is closing... Uninstalling the addon, it is solving the problems... but still, I like this addon, how can I use it without problems?

**Comment by SamTebbs33** [comment]
I have seen this issue even without this component (but with others installed) so it's likely a common issue with custom components.

**Comment by pickonedev** [comment]
For me, only this component made some issues
