### ISSUE TITLE
IP4 posted to Home Assistant

### ISSUE THREAD

**Issue by johanjongsma** [thomasloven/hass-browser_mod#267]
Hi Thomas,

Sometimes, I need to connect directly to Fully Kiosk on my tablets. For that, I'd like to see the IP (String fully.getIp4Address()) of my tablets as an attribute in HA. Can you please add that?

Thanks, Johan Jongsma

**Comment by thomasloven** [comment]
Closed because of Browser Mod 2.0 release.
Please see #354.
