### ISSUE TITLE
Home assistant restart causes Browser unavailable.

### ISSUE THREAD

**Issue by criticallimit** [thomasloven/hass-browser_mod#268]
Hi,

every time HA is restartet, I have to close and open the Browser on the Wall mounted iPad as well.

Log:

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:89 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 10:09:03 (2 occurrences) 
Last logged: 10:09:04

[548297419360] Received invalid command: browser_mod/connect
[548296364720] Received invalid command: browser_mod/connect

After restarting the Browser everything is working fine again.

**Comment by bublikOff** [comment]
the same for me

**Comment by yacinegithub** [comment]
same here

**Comment by jay-gates** [comment]
For Firefox on Linux, I just needed to reload the browser page to resolve this.

**Comment by Protoncek** [comment]
Yes, page reload is enough also in fully kiosk. But, it would be nice if this can be resolved. since after HA restart nothing in connection with browser-mod works until refresh is made.

**Comment by jay-gates** [comment]
A work-around might be to auto-reload the page on a timer (say, hourly). [How to Reload a Page using JavaScript](https://www.w3docs.com/snippets/javascript/how-to-reload-a-page-using-javascript.html)

**Comment by curtisdr** [comment]
I solved _most_ of my issues by using Fully Kiosk and having it reload every hour.

**Comment by Protoncek** [comment]
Yes, by auto-refresh when HA restarts:
[https://community.home-assistant.io/t/browser-mod-turn-your-browser-into-a-controllable-device-and-a-media-player/123806/1491](url)
