### ISSUE TITLE
A command to switch to another app

### ISSUE THREAD

**Issue by felipecrs** [thomasloven/hass-browser_mod#275]
Since Fully Kiosk allows to have not only browser but also apps, it would be very cool if we could have a command like "switch to another app", which I would use to switch from the HA frontend to the Tuya Smart app when someone presses my doorbell button.

**Comment by KTibow** [comment]
It's impossible to trigger intents without user interaction. Also, what is in the Tuya Smart app that can't be accessed with the new HA integration?

**Comment by felipecrs** [comment]
Unless by using the Remote Admin API then, I guess...

The doorbell, mainly the call when someone rings the button.

**Comment by KTibow** [comment]
>The doorbell, mainly the call when someone rings the button.

Like, what interfaces does the Tuya app have? Do you mean the live view w/ mic or something (never bought a Tuya doorbell)?

**Comment by felipecrs** [comment]
Right, so there are a couple of problems:

1. The current HA Tuya integration provides access to the Tuya Doorbell, but only to its camera (including its audio). There is no even button pressed sensor as of now.
2. The HA in general does not provide support for doorbells. At most there are camera support, and the rest someone needs to hack around to have something similar.

The big miss right now is a calling UI. When someone rings the doorbell, the Tuya Smart app presents a calling UI similar to a video call on duo.

But anyway, I could live without the calling UI if there was a way to achieve 2-way audio from HA directly. But there isn't, this is not supported yet as it seems.

**Comment by felipecrs** [comment]
For the lack of button press sensor, I created an automation inside of the Tuya app which turns on a fake switch when someone rings the bell, and then I capture the event of the switch turning on.

That's how I'm doing currently, and then I send some adb commands to the tablet to show de Tuya app. But the Fully Remote Admin API has an endpoint for opening an app as well.

I wanted to stop using ADB because its connection is very unreliable.

**Comment by KTibow** [comment]
Oh, I understand. How are you viewing HA again?

**Comment by felipecrs** [comment]
On Fully Kiosk Browser, I configured the Universal Launcher. I then configured the universal launcher with both the Tuya Smart app and the HA URL.

I don't programmatically go back to HA after entering Tuya as of now, but one can simply press the Home button in the tablet, and then the universal launcher with both Tuya and HA are displayed.

However, I'm thinking about switching back to HA programmatically somehow, maybe after a couple of minutes of inactivity or something like that.

**Comment by felipecrs** [comment]
Thinking more about it, I believe it may not be a good fit for browser_mod. As the own name says, it's meant for turning a browser in a controllable device. Switching out of the browser (such as switching to another app) seems out of the scope for browser_mod.

Not to mention, it's very likely that this is only doable with Fully Remote API, which is not yet being used by browser_mod.

Also, for achieving the same goal, there is https://github.com/cgarwood/homeassistant-fullykiosk, which uses the Fully Remote Admin API and provides a [service just for that purpose of switching apps](https://github.com/cgarwood/homeassistant-fullykiosk/blob/29cee22d98ca300703c2fa8cbbe16c6668dc1b5f/custom_components/fullykiosk/services.yaml#L127).

If the maintainers think differently, feel free to reopen the issue.
