### ISSUE TITLE
Received invalid command: browser_mod/update

### ISSUE THREAD

**Issue by vdiogo** [thomasloven/hass-browser_mod#278]
My Home Assistant version: 2021.12.0

I've removed browser_mod by doing the following:
- removed configuration from config.yaml
- deleted integration in Home Assistant configuration
- deleted integration in HACS
- Restarted Home Assistant

**What I expected to happen:**
Would expect that no additional reference to browser_mod would remain in my installation

**What happened instead:**
Get error in log about "Received invalid command: browser_mod/update"

**Minimal** steps to reproduce:
Checking the logs

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by philder** [comment]
same here

**Comment by mikael-andersson** [comment]
Same here.

**Comment by mikael-andersson** [comment]
Core Version
core-2021.12.10

**Comment by merdely** [comment]
I had the same problem.  Then I went and looked under Integrations in the GUI of Home Assistant and there was a browser_mod card.  I removed it.  Hopefully it will stop  with the error messages now.

**Comment by gulli1986** [comment]
Same here running core-2022.3
