### ISSUE TITLE
Feature Request - Improve toast to support buttons and option to display time remaining.

### ISSUE THREAD

**Issue by skynet01** [thomasloven/hass-browser_mod#28]
Love the new toast feature. Its the notification system that HA is missing. Would be great if there was an option to include a button that could call a script.  This would allow user to act upon different notifications. You can also have toast display time remaining before it's dismissed.

For example I can have it come up when house alarm is being activated with an option to cancel.

**Comment by thomasloven** [comment]
Sounds like html5 notifications would be better for this. https://www.home-assistant.io/integrations/html5/

**Comment by jazzyisj** [comment]
A dismiss button would actually be a nice addition.   I have a few toast messages with long durations that I wouldn't mind having the option to dismiss.

Like this one...

![image](https://user-images.githubusercontent.com/44064559/105570530-063a1480-5d18-11eb-8744-2baaadb8d27b.png)
