### ISSUE TITLE
Browser mod floods my log file

### ISSUE THREAD

**Issue by Pirol62** [thomasloven/hass-browser_mod#282]
My Home Assistant version: 2021.11.5

**What I am doing:**
Nothing

**What I expected to happen:**
no log entries

**What happened instead:**
The component floods my logfile

**Minimal** steps to reproduce:

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:**

```
Logger: homeassistant.components.websocket_api.http.connection
Source: helpers/entity.py:610
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 09:11:02 (11 occurrences)
Last logged: 09:12:39

[281473402171552] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 100, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 44, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 94, in update
    self.sensor.data = data.get("browser")
  File "/config/custom_components/browser_mod/helpers.py", line 106, in data
    self.updated()
  File "/config/custom_components/browser_mod/sensor.py", line 27, in updated
    self.schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 610, in schedule_update_ha_state
    self.hass.add_job(self.async_update_ha_state(force_refresh))  # type: ignore
AttributeError: 'NoneType' object has no attribute 'add_job'
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x ] Have made sure I am using the latest version of the plugin.

- [x ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by maretodoric** [comment]
You have a disabled browser_mod device or entity of that device which is active and trying to talk to browser mod, then it errors out and throws an exception.

**Comment by Pirol62** [comment]
ok, thank you
