### ISSUE TITLE
Photo album Screensaver! Scale image to fit?

### ISSUE THREAD

**Issue by brayStorm** [thomasloven/hass-browser_mod#285]
I'm almost there! I want a screensaver photo album slideshow on the touchscreen kiosk in my kitchen.
Using a python script to randomly pick a photo from a folder every 30 seconds and stick it in www/slide.jpg.
Then using the `local_file` camera platform, I have a 'camera' of whatever that photo currently is. (This gets around browser cache problems). Pop-up card is working wonderful, however I'm having an impossible time getting it to max the screen, and also scale the image. They're almost all iPhone vertical photos. I would also want the background of the card to be blacked out.

    service: browser_mod.popup
    data:
      hide_header: true
      deviceID:
        - kiosk_kitchen
      title: ' '
      auto_close: true
      style: |
          :host .content {        
            height: 100vh !important;      
            width: auto !important;
           }
      card:
        type: picture-entity
        entity: camera.screensaver #Using local_file camera platform!
        show_name: false
        show_state: false
        camera_view: live
        tap_action:
          action: toggle
          entity_id: automation.kiosk_screensaver #Automation toggles itself off when it runs, this puts it back on

![image](https://user-images.githubusercontent.com/20567279/148112665-1afcdb02-5205-47c5-94b7-ef30650693fd.png)

How do I get the card to fit the max height of the window, scale the image to fit, and black out anything else behind it? Maybe I just have square eyeballs from staring at this for a week!

**Comment by thomasloven** [comment]
`size: fullscreen`
