### ISSUE TITLE
Browser Mod and player not working on Google Nest Hub

### ISSUE THREAD

**Issue by jtonk** [thomasloven/hass-browser_mod#288]
My Home Assistant version: 2021.12.8

**What I am doing:**
cast to google nest hub

**What I expected to happen:**
ha to create browser mod entities for my nest hub

**What happened instead:**
nothing

**Minimal** steps to reproduce:
basic install, as described in repo added  /browser_mod.js to resources using UI as a module.

using ha service to cast lovelace
```
  - service: cast.show_lovelace_view
    data:
      entity_id: media_player.kitchen_display
      dashboard_path: lovelace
      view_path: home
```
media player works fine on desktop browsers, but give error:
`Custom Element doesn't exist: browser-player`
other custom cards work fine on google nest hub

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it
HOW CAN I ACCESS THE CONSOLE OF A NEST HUB???
// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x ] Have made sure I am using the latest version of the plugin.

- [x ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by KTibow** [comment]
In general, a lot of things don't work when casting. (Yes, this isn't helpful, just an FYI.)

**Comment by jtonk** [comment]
haha, I know, but I have almost all of it working. By the way, browser_mod works fine with CATT, but the big plus of CAST (over CATT) is that the 30seconds timeout issue is resolved.
I don't understand how cast works, and why some elements are not available while other custom cards are fine.

**Comment by KTibow** [comment]
I'd blame it on some cards/browser_mod using modern JS features. When you cast Home Assistant to a Nest Hub using regular casting, the Nest Hub renders the site. It might have an outdated browser. It sounds like CATT renders the site on its side, which might be up to date.

**Comment by DanDixon** [comment]
I'm having this exact problem.

browser_mod - 1.5.3
Home Assistant - 2022.8.4

@krunkel Is it still working for you?

**Comment by krunkel** [comment]
It was working this morning (Home Assistant 2022.8.2).  I will install the update and try again...

**Comment by DanDixon** [comment]
@krunkel Thanks so much for your reply.

Turns out the music example you shared also works for me, but what doesn't work for me is:

1 - showing the browser-player (where you scan see the name of the device
`Custom Element doesn't exist: browser-player`
2 - Using the popup command
`show_name: true
show_icon: true
type: button
tap_action:
  action: fire-dom-event
  browser_mod:
    command: popup
    title: Climate
    card:
      type: grid
      square: false
      columns: 2
      cards:
        - entity: climate.bedroom_air_conditioner
          name: Bedroom
          type: thermostat
        - entity: climate.living_room_air_conditioner
          name: Living Room
          type: thermostat
        - entity: climate.office_air_conditioner
          name: Living Room
          type: thermostat
        - entity: climate.basement_air_conditioner
          name: Living Room
          type: thermostat
name: Climate Popup Example
`

Do either of those work for you?

**Comment by abigdeel** [comment]
Exact same problem here.  

Browser mod doesn't load at all when I cast to my Nest Hub 2.
The browser player card also says not found.
