### ISSUE TITLE
debug service does not work

### ISSUE THREAD

**Issue by swa72** [thomasloven/hass-browser_mod#290]
## System Health

version | core-2021.12.9
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.19.3
Stage | running
Available Repositories | 934
Downloaded Repositories | 17

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 11

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.5
-- | --
update_channel | stable
supervisor_version | supervisor-2021.12.2
docker_version | 20.10.7
disk_total | 109.3 GB
disk_used | 16.0 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | deCONZ (6.11.1), Duck DNS (1.14.0), SSH & Web Terminal (10.0.1), Samba share (9.5.1), AdGuard Home (4.4.2), motionEye (0.16.0), NGINX Home Assistant SSL proxy (3.1.0), MariaDB (2.4.0), InfluxDB (4.3.0), Grafana (7.4.0), Mosquitto broker (6.0.1), Check Home Assistant configuration (3.9.0), ESPHome (2021.9.1), DSS VoIP Notifier (3.5.7), Home Assistant Google Drive Backup (0.105.2), phpMyAdmin (0.6.0), FTP (4.2.1), Studio Code Server (3.7.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 12
views | 35
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**What I am doing:**
Call debug service

**What I expected to happen:**
Pop-up on all browsers

**What happened instead:**

Nothing :-/ Instead ...

```
Logger: homeassistant.components.http.ban
Source: components/http/ban.py:124
Integration: HTTP (documentation, issues)
First occurred: 15:01:54 (6 occurrences)
Last logged: 15:03:10

Login attempt or request with invalid authentication from iPhone.fritz.box (192.168.178.36). (HomeAssistant-Extensions-PushProvider/2021.12.1 (io.robbie.HomeAssistant.PushProvider; build:2021.327; iOS 15.1.0) Alamofire/5.4.4)
```
and 
```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/http.py:254
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 15:02:14 (2 occurrences)
Last logged: 15:03:14

[547957890736] Disconnected: Did not receive auth message within 10 seconds
[547793475856] Disconnected: Did not receive auth message within 10 seconds
```
**Minimal** steps to reproduce:
Call the debug service on the particular HA version.

**Error messages from the browser console:**

see above.

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [ X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [ X] Have made sure I am using the latest version of the plugin.

- [ X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [ X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by PsyonicOne** [comment]
I to am seeing this. But only on devices connecting to HA via my internal network, both in the companion app and via Firefox, I have not tried any other browsers.
If I change the connection to use my duckDNS service it works as expected, both in the companion app and Firefox.
