### ISSUE TITLE
popup calls stop working. only works sometimes (right after loading the page)

### ISSUE THREAD

**Issue by aaamoeder** [thomasloven/hass-browser_mod#292]
My Home Assistant version: 2021.12.10
browser_mod version: 1.5.1

**What I am doing:**
calling a popup on a dashboard screen (like I have been for over a year)

**What I expected to happen:**
the popup to show

**What happened instead:**
after a fresh load of the screen the popup shows but after x amount of time the popup (or other calls like navigate) do nothing without any error logs or traceback.

I'm sorry for not being able to be more precise but I have no idea of what is happening or causing this at all...

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thoompje** [comment]
Same issue here.

**Comment by bennyb0i** [comment]
Getting the same issue with browser_mod 1.5.3 and HA core 2022.4.6.

**Comment by Harro65** [comment]
Same with me, it seems to be something with custom:button-card as when i changed one of my cards to a standard HA button card the pop-up worked. No errors in the logs,. 

I'm using fire-dom-event to trigger the popup also.

**Comment by tboyce021** [comment]
I'm having the same issue even with a standard button card. If I leave the page or app for some time and then come back, popups don't work. If I refresh on any page  (even the configuration page) they start working again.

**Comment by Jan-Fenkhuber** [comment]
> 

Same issue here. It just stopped working in April and I didn't get it back on track.
Just tried the normal button instead of the custom:button-card - and it works. 

browser_mod 1.5.3
Home Assistant Core 2022.5.4
Home Assistant Supervisor 2022.05.1
Home Assistant OS 7.6

Firefox, Edge and Chrome - all caches cleared.
A backup from before core 2022.4 works; only updating the core to 2022,5 busts the browser_mod again.

**Comment by Harro65** [comment]
> 

That must be it! I also installed Mushroom recently to use as my mobile dashboard.  Damn, i don't want to remove mushroom as i have it set nicely for that purpose.

Wonder if there is a work around for it. Thanks for following up on the thread!
