### ISSUE TITLE
Log details (ERROR)

### ISSUE THREAD

**Issue by romtram** [thomasloven/hass-browser_mod#293]
Home Assistant 2021.12.10
Home Assistant OS
browser_mod

The problem
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:89
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 27 gennaio 2022, 20:14:38 (2 occurrences)
Last logged: 27 gennaio 2022, 20:14:38

[547564692624] Received invalid command: browser_mod/connect
[547564692624] Received invalid command: browser_mod/update

**Comment by aladin2000** [comment]
Same error here
 Received invalid command: browser_mod/connect

**Comment by Wyren** [comment]
I'm getting a lot of those here as well. Even after removing the integration.

**Comment by mmschoe** [comment]
I get these too. The only way I've found to get rid of them is to ensure there are no web browser sessions running HA at all while the server is rebooting and browser_mod is starting up. 
After it boots, you can open your browser again and browser_mod seems to work fine.
