### ISSUE TITLE
Alert

### ISSUE THREAD

**Issue by romtram** [thomasloven/hass-browser_mod#295]
My Home Assistant version: core-2021.12.10

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 1 febbraio 2022, 16:46:34 (6 occurrences)
Last logged: 08:05:49

Entity media_player.71626333_87bd9d3b (<class 'custom_components.browser_mod.media_player.BrowserModPlayer'>) implements device_state_attributes. Please report it to the custom component author.
Entity light.71626333_87bd9d3b (<class 'custom_components.browser_mod.light.BrowserModLight'>) implements device_state_attributes. Please report it to the custom component author.
Entity media_player.5b0995ce_2c0f2b6e (<class 'custom_components.browser_mod.media_player.BrowserModPlayer'>) implements device_state_attributes. Please report it to the custom component author.
Entity light.5b0995ce_2c0f2b6e (<class 'custom_components.browser_mod.light.BrowserModLight'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.5b0995ce_2c0f2b6e (<class 'custom_components.browser_mod.sensor.BrowserModSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by silviudc** [comment]
I am also seeing the same warnings in my logs after the 2022.2 updates
