### ISSUE TITLE
Popup two live camera streams

### ISSUE THREAD

**Issue by mag999DK** [thomasloven/hass-browser_mod#297]
When my surveillance camera detects motion, it popup with a live camera stream from WebRTC.

Is it possible to make a popup with two live streams, from different cameras?
![live](https://user-images.githubusercontent.com/82704073/152701328-c72dde37-0006-49c9-9add-40d64a8eb96c.png)
![yaml](https://user-images.githubusercontent.com/82704073/152701343-3f622e88-805c-43e3-a8a8-5990c785a9f6.PNG)

**Comment by thundergreen** [comment]
just make a horizontal stack card and put webrtc card inside :)
