### ISSUE TITLE
unable to "Displaying a popup via a script" if i use "this" as the deviceID in the scrip, but it is working fine if i use the browser's deviceID directly.

### ISSUE THREAD

**Issue by horacecar** [thomasloven/hass-browser_mod#30]
i use the same sample in the Cookbook.

i was unable to "Displaying a popup via a script" if i use "deviceID: this" as the deviceID in the script, even i run the script directly. But it is working fine if i use the browser's deviceID directly ,
 for example" deviceID: 3ads72oj-3jf87rdm"

May be HA cannot recognize "this" of the deviceID in the script???

test_popup:
  sequence:
    - service: browser_mod.popup
      data_template:
        deviceID: this                              <<<< cannot
        deviceID: 3ads72oj-3jf87rdm      <<<< can
        title: Testing script
        card:
          type: entities
          entities:
            - light.bed_light

**Comment by thomasloven** [comment]
The script runs on your server and can't know which browser you are currently using.
https://github.com/thomasloven/hass-browser_mod/wiki/Cookbook#displaying-a-popup-via-a-script
