### ISSUE TITLE
browser_mod.js:145 Uncaught (in promise) 3

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/hass-browser_mod#309]
My Home Assistant version: 2022.4.0.dev20220327

**What I am doing:**

no idea what causes this yet
must follow up this and investigate, though maybe this is a generic error that is already clear for the dev of the resource
**What I expected to happen:**

no error in the console
**What happened instead:**

**Minimal** steps to reproduce:

As said, I dont have a lead yet on why this happens, it seems to have started on the latest 2022.4 dev's

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:**

```

browser_mod.js:145 Uncaught (in promise) 3

```
<img width="688" alt="Schermafbeelding 2022-03-27 om 22 43 32" src="https://user-images.githubusercontent.com/33354141/160300339-197f4c27-1fe0-4aa2-8d53-5afa4f76153e.png">

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [ X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X ] Have made sure I am using the latest version of the plugin.

- [X ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by michaelcarvalho86** [comment]
Have you found a solution?

**Comment by linsvensson** [comment]
I'm having the same problem, would love to know if anyone has a solution.
