### ISSUE TITLE
No attributes on sensor

### ISSUE THREAD

**Issue by diveschumi** [thomasloven/hass-browser_mod#312]
Hi,

since the last update to 2022.4.0 I don't see any attributes at the sensor and so I my automations don't work any more.

**Comment by KixMan28** [comment]
I have the same issue:

![2022-04-07 10_27_11-Search](https://user-images.githubusercontent.com/33165356/162156025-9fea3aaf-c472-4dab-81c0-f4d25e68bfce.jpg)

**Comment by mjuliani** [comment]
I have the same
<img width="337" alt="Captura de Tela 2022-04-07 às 16 28 31" src="https://user-images.githubusercontent.com/818284/162281611-6a5c560d-c4a1-4ca9-99fd-2f99abab5356.png">

<img width="892" alt="Captura de Tela 2022-04-07 às 16 27 05" src="https://user-images.githubusercontent.com/818284/162281596-d1ad73ac-d5ba-4332-9a3a-214bff64857e.png">

**Comment by janfajessen** [comment]
Yes, and without it it's impossible to know the battery of the tablets to charge control.. please fix it when you can and update. Thanks in advance and for your amazing work

**Comment by pixeye33** [comment]
Hello,

While digging a bit i've found that two PR were made for this : https://github.com/thomasloven/hass-browser_mod/issues/281#issuecomment-1011337611 but they are not merged to this day (project seems stale).

In order to fix this for myself until the PR is merged here is what i did :
`find /custom_components/browser_mod/ -name "*.py" -type f -exec sed -i "s/device_state_attributes/extra_state_attributes/g" {} \;`

**Comment by KixMan28** [comment]
@pixeye33 thank you for this hint, but could you please elaborate on this as I don't know what to do with this?

**Comment by KentuckyMC** [comment]
Got the same issue, hopefully @thomasloven can find some time to merge the open PR's.

**Comment by diveschumi** [comment]
@pixeye33: Cool, thank you very much. It's work.

**Comment by MiBe17** [comment]
@pixeye33 Also worked for me, thank you so much!
For all who won't know how to apply the command: download "Terminal & SSH" add-on and connect via putty or use the build-in web ui!

**Comment by KixMan28** [comment]
@MiBe17 Thank you, but it doesn't work at my end. I use SSH & Web Terminal add-on and when I run the above mentioned command I get a "Folder not found" error. See screenshot.

What am I doing wrong?
![2022-04-11 09_52_14-Start](https://user-images.githubusercontent.com/33165356/162690537-c9ca68e8-c621-45ec-ad97-ff9c90319641.jpg)

**Comment by KentuckyMC** [comment]
> @MiBe17 Thank you, but it doesn't work at my end. I use SSH & Web Terminal add-on and when I run the above mentioned command I get a "Folder not found" error. See screenshot.
> 
> What am I doing wrong? ![2022-04-11 09_52_14-Start](https://user-images.githubusercontent.com/33165356/162690537-c9ca68e8-c621-45ec-ad97-ff9c90319641.jpg)

If you type: `ls` you can see in which folder you are currently. Best is to navigate to the 'configuration' folder. So if you see the folder, you can navigate there with: `cd configuration`, if you're to high in the structure, you can always navigate 1 folder back by: `cd ..`. Once you are in the configuration folder. You will see the 'custom components' folder when you type ls there.

If you then use the code that is mentioned above (without the first slash), it'll work:

`find custom_components/browser_mod/ -name "*.py" -type f -exec sed -i "s/device_state_attributes/extra_state_attributes/g" {} \;`

**Comment by MiBe17** [comment]
@KixMan28 try navigating into the "config" folder (using "cd config") and then put a dot in front of the first /:
find **.**/custom_components/browser_mod/ -name "*.py" -type f -exec sed -i "s/device_state_attributes/extra_state_attributes/g" {} \;

**Comment by KixMan28** [comment]
@KentuckyMC and @MiBe17  thank you for your quick replies. I fired the command in the config folder and it executed without error. I am restarting my HA right now.

**Comment by KixMan28** [comment]
@pixeye33 @MiBe17 @KentuckyMC Thank you all for your help! It works now.

**Comment by mjuliani** [comment]
@pixeye33 @KentuckyMC Works for me too. Thanks.

**Comment by supersebbo** [comment]
Same problem.  Fix by @pixeye33 works.  Hopefully @thomasloven can merge into the codebase ASAP!

**Comment by fraintt** [comment]
I do not know what I´m doing wrong but after the command, and also an ha restart I still do not have any attributes on the sensor. Should I change something else? Command does not return any error, the FIles are really changed. 

When starting HA I only see this error: 

_
Logger: homeassistant.helpers.integration_platform
Source: loader.py:620
First occurred: 15:08:10 (8 occurrences)
Last logged: 15:08:34

Unexpected error importing browser_mod/group.py
Unexpected error importing browser_mod/logbook.py
Unexpected error importing browser_mod/system_health.py
Unexpected error importing browser_mod/cast.py
Unexpected error importing browser_mod/significant_change.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 34, in _process
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 603, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 620, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.bm.recorder'
_

**Comment by mattbrad2** [comment]
Thats what I'm getting as well - same as @fraintt 
No sensors even after executing the above commands (with no errors)

**Comment by rarroyo6** [comment]
Having the same issue.
Can no longer access the "path" attribute, so my automations no longer work.
Tried the command above, but it had no effect.

**Comment by thomasloven** [comment]
Closed because of Browser Mod 2.0 release.
Please see #354.
