### ISSUE TITLE
Cannot read properties of null (reading 'location_name')     at Function.generateDashboard

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/hass-browser_mod#318]
My Home Assistant version: 2022.5.0.dev20220420
Browser-mod version: 1.5.3

**What I am doing:**
Nothing in particular..
'location_name' is not used in my cinfig

Not sure if this is caused by Browser_mod or if Browser_mod is merely the messenger

**What I expected to happen:**
 no error

**What happened instead:**
error in inspector about location_name
'location_name' is not in any of may config, frontend or backend

**Minimal** steps to reproduce:

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```
No yaml to post here, as its happening on most pages Chrome And Safari on Mac

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here

ha-app-layout.js:101 TypeError: Cannot read properties of null (reading 'location_name')
    at Function.generateDashboard (14f311db.js:1:12122)
    at o (ha-app-layout.js:101:1)
    at async r.value (ha-panel-lovelace.ts:144:1)
```

<img width="690" alt="Schermafbeelding 2022-04-20 om 12 56 51" src="https://user-images.githubusercontent.com/33354141/164216860-64b52cf2-40d0-4291-bfa3-a8ed5782cd47.png">

---

**By replacing the space in the checkboxes ([ X]) with an X below, I indicate that I:**

- [X ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X ] Have made sure I am using the latest version of the plugin.

- [X ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by Mariusthvdb** [comment]
adding another screenshot of the inspector error, hope that gives more feedback win a cause:

<img width="1029" alt="Schermafbeelding 2022-05-25 om 15 18 03" src="https://user-images.githubusercontent.com/33354141/170271400-68bd5335-fd48-4ccc-a8f6-f4226cfe5a1e.png">

**Comment by CKranebitter** [comment]
+1 Got the same console-error.

**Comment by CKranebitter** [comment]
Seems to be an error of browser_mod.js and related to the call stack.
If a breakpoint is set on line 1115 which delays the execution of the async-functions below, no error occurs.
So it seems that `await he()` or `await e._fetchConfig(!1)` are problematic as the dashboard-panel is not loaded yet.
Hence the config value `location_name` is not assigned.
This is a browser_mod-issue and should be fixed as it affects everyone.
Can the ticket be reopened?
 
<img width="562" alt="Screenshot 2022-12-13 at 10 00 02" src="https://user-images.githubusercontent.com/63287042/207274604-079436a3-ac87-4252-a31a-062c3066e58b.png">

**Comment by rwunsch** [comment]
Same issue for me:
![image](https://user-images.githubusercontent.com/662448/211893045-f674ba7f-6901-4b30-9ac2-e8966afa30f6.png)

**Comment by fpfp** [comment]
+1 same error

**Comment by holdestmade** [comment]
Same error here

**Comment by rsumilang** [comment]
is this issue followed somewhere?

**Comment by tanushshukla** [comment]
im also getting same error.

**Comment by eliorerz** [comment]
Getting the same error

**Comment by epj3** [comment]
Error still exists, this shouldn't be closed?
