### ISSUE TITLE
Is HACS sufficient for installation

### ISSUE THREAD

**Issue by RichardUUU** [thomasloven/hass-browser_mod#33]
Found this in HACS, but HACS is not mentioned in the installation instructions. 

After install by HACS, I added this to configuration.yaml
```
browser_mod:
  prefix: "browser_"

```
After several restarts, and visiting my site from several browsers on different machines, the Entity Registry still doesn't show any entities that include "browser"

I'm running the Nginx reverse proxy with a custom HTTPS domain to my site.

Cheers, Richard

**Comment by thomasloven** [comment]
What does your home assistant log files say?

**Comment by RichardUUU** [comment]
Only message related to browser_mod says:
`2019-11-11 16:37:34 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for browser_mod which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.`

browser_ entries don't show up in the Entity Registry, but I now see that Developer Tools / States does show them. I don't know why that would be. 

Thanks, Richard

**Comment by thomasloven** [comment]
They are not supposed to show up in the entity registry.
