### ISSUE TITLE
Fully Kiosk Browser deviceid resets at each login

### ISSUE THREAD

**Issue by GitHubGoody** [thomasloven/hass-browser_mod#334]
My Home Assistant version: 2022.6.3

**What I am doing:** N/A

**What I expected to happen:** deviceid should stay the same for each device (in my case Fire tablets) running Fully Kiosk Browser

**What happened instead:** The deviceid resets to another random string when I log out/clear cache and log back in

**Minimal** steps to reproduce:

1. On a device running FKB, take note of deviceid
2. Log out
3. Log in
4. Check deviceid

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
Closed because of Browser Mod 2.0 release.
Please see #354.
