### ISSUE TITLE
Scrollbar in popups with history graph

### ISSUE THREAD

**Issue by VDRainer** [thomasloven/hass-browser_mod#34]
In default more-info popups when hovering over a graph, the value overlaps the popup.
![20191112_11:51:57_001](https://user-images.githubusercontent.com/26381449/68666088-832e0380-0543-11ea-8515-f47a67774b58.png)
In browser_mod popups the value is half invisible and a scrollbar comes up.
![20191112_11:52:34_001](https://user-images.githubusercontent.com/26381449/68666162-a9ec3a00-0543-11ea-982d-275057796351.png)

**Comment by ovid-io** [comment]
This is an issue with 107 as well

**Comment by thomasloven** [comment]
Please open a new issue if this is still a problem.
