### ISSUE TITLE
android tablet unavailable even with workarounds

### ISSUE THREAD

**Issue by jouster1974** [thomasloven/hass-browser_mod#346]
My Home Assistant version: 2022.7.7

running browser_mod integration with FKB on two Android (Amazon Fire) tablets

using the "force_stay_awake: true" or "screensaver: true" commands in configuration.,yaml is supposed to stop these devices from becoming unavailable

after roughly 5 minutes, the devices are becoming unavailable

**Minimal** steps to reproduce:  This happens after 5 or so minutes each time

This can be fixed by refreshing FKB on the tablet in question but once again becomes unavailable after the same time again

**Comment by thomasloven** [comment]
Closed because of Browser Mod 2.0 release.
Please see #354.
