### ISSUE TITLE
Browser_mod Not Loaded

### ISSUE THREAD

**Issue by abwino** [thomasloven/hass-browser_mod#348]
<img width="271" alt="Screenshot 2022-08-04 at 13 22 09" src="https://user-images.githubusercontent.com/22999854/182887449-077f3266-d1f4-41fe-8207-7bdb375c2412.png">

Hi! Sorry to be a pain but something has happened to my browser_mod installation. On the integrations page it shows as not loaded. The log says: 

`This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/browser_mod/__init__.py:40 
Integration: browser_mod (documentation) 
First occurred: 15:09:55 (1 occurrences) 
Last logged: 15:09:55

Error during setup of component browser_mod
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/browser_mod/__init__.py", line 40, in async_setup
    name = config[DOMAIN][CONFIG_DEVICES][d].get("name", None)
TypeError: string indices must be integers

`
I have tried copying the latest files from the repo to my custom_components/browser_mod but that made no change. I can't see a way to uninstall and start again. Any help gratefully received! Thanks.

**Comment by thomasloven** [comment]
Closed because of Browser Mod 2.0 release.
Please see #354.
