### ISSUE TITLE
browser_mod will not re-add a device after calling browser_mod.clean_devices

### ISSUE THREAD

**Issue by okets** [thomasloven/hass-browser_mod#350]
My Home Assistant version: 2022.8.0

**What I am doing:**
I called `browser_mod.clean_devices` service.
some devices got cleaned, but among them my iphone app that wasn't on at the moment.

**What I expected to happen:**
I expected every "unavailable" device to be deleted, but if the device opens Home Assistant again it should be re-added.

**What happened instead:**
once a device is removed by `browser_mod.clean_devices,` the only way to add it back is by re installing card-mod and home assistant restart

**Minimal** steps to reproduce:
call `browser_mod.clean_devices `and then open a browser that was deleted.

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
Closed because of Browser Mod 2.0 release.
Please see #354.
