### ISSUE TITLE
Only register new deviceID when specified explicitly

### ISSUE THREAD

**Issue by ekutner** [thomasloven/hass-browser_mod#352]
I really like browser_mod, however there is one thing very annoying about it and that's constantly having to deal with the new entities being created when a new browser connects to HA.
I think it would be great if browser_mod and an "explicit" mode in which it wouldn't auto generate random deviceIDs for every new browser but instead require the user to explicitly set it using the existing methods, either using the query string or the browser player card.

**Comment by thomasloven** [comment]
Closed because of Browser Mod 2.0 release.
Please see #354.
