### ISSUE TITLE
Popup with picture-entity RTSP camera stream doesn't unload when closing popup

### ISSUE THREAD

**Issue by abigdeel** [thomasloven/hass-browser_mod#353]
My Home Assistant version: 2022.8.7

**What I am doing:**
Using browser_mod to replace more_info for camera entities
Use a popup with a picture entity or picture glance card, with a live RTSP link and using webRTC to stream camera
When I close the popup, there is still network traffic.
Re-opening the popup, the stream doesn't start until I kill the webRTC addon or restart HA.

**What I expected to happen:**
Using custom:frigate-card, there is the option to load/unload cameras lazily. 

**What happened instead:**
Don't seem to have that default behaviour here. Can't stop the stream when pop-up closes.

**Minimal** steps to reproduce:
Use browser_mod more_info popup with picture entity/picture glance card and using RTSPtoWeb

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:**
No errors, RTSP stream doesn't end.
```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
Closed because of Browser Mod 2.0 release.
Please see #354.
