### ISSUE TITLE
Unable to load Browser Mod due to missing "Migration Handler"

### ISSUE THREAD

**Issue by thomasmaxson** [thomasloven/hass-browser_mod#356]
When upgrading to the latest version (2.0), with the latest version of Home Assistant (2022.8.7), I am getting the following error upon restart.

Error in log:
Migration handler not found for entry Browser Mod for browser_mod

Not seeing anything in the documentation regarding this. Any pointers as to how to resolve this so that Browser Mod loads?

**Comment by zang74** [comment]
Remove Browser Mod from your integrations panel and re-add it. All will be happy.

**Comment by thomasloven** [comment]
> Not seeing anything in the documentation regarding this

It's there. First line in the installation instructions:

> - **First make sure you have completely removed any installation of Browser Mod 1**
