### ISSUE TITLE
New devices are not automatically added since version 2.0

### ISSUE THREAD

**Issue by n00bcodr** [thomasloven/hass-browser_mod#357]
My Home Assistant version: [2022.9.0b3]

**What I am doing:**

Clearing Cache and logging in to devices through browser and apps.

**What I expected to happen:**

A new device to be added to browser mod integration.

**What happened instead:**

A new device is not being added.

**Minimal** steps to reproduce:

Login to your homeassistant instance from a new browser or incognito window.

**Error messages from the browser console:**

```
n/a
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by n00bcodr** [comment]
an example where this is a problem is 

I have a couple of dashboards around the house running fully kiosk browser, I have their start URLs set http://192.168.0.168:8123/lovelace-wallmount/0?deviceID=tablet.. etc, with the preferred deviceID. 

With the latest update, I have to make the user logged in to the dashboard as admin and go to the Browser Mod configuration panel and register the browser for each device. 

<img width="558" alt="image" src="https://user-images.githubusercontent.com/49611451/188271956-6546f278-1ee0-49a3-bd3f-617dd0cb714d.png">


I am not sure if I am missing something obvious here. Apologies if I am.

**Comment by thomasmaxson** [comment]
I have noticed the same thing here. My current work around is to set the global as hidden, and then the computer that I edit it on as shown. Another way would be to make specific users for the tablets, and hide/shown for the user. But I am having getting anything user specific to save properly. So I am doing everything with global and browser settings.

**Comment by thomasloven** [comment]
You're not missing anything. That's how it works now and what the documentation tells you you must do.
