### ISSUE TITLE
Migration handler not found for entry Browser Mod for browser_mod

### ISSUE THREAD

**Issue by maury77** [thomasloven/hass-browser_mod#359]
My Home Assistant version: 2022.8.6

Logger: homeassistant.config_entries
Source: config_entries.py:349
First occurred: 17:19:38 (1 occurrences)
Last logged: 17:19:38

Migration handler not found for entry Browser Mod for browser_mod

**Comment by thomasmaxson** [comment]
Delete from integrations, restart system, and re-add. I had the SAME problem earlier this morning.

**Comment by kaizersoje** [comment]
Thx @thomasmaxson. Got the same error, followed your steps and error gone.

**Comment by maury77** [comment]
Thanks all ok
