### ISSUE TITLE
add user setting in sidebar order does not work?

### ISSUE THREAD

**Issue by jatgm1** [thomasloven/hass-browser_mod#363]
so i tried on my android phone, using the app after uninstalling and reinstalling it. and on a laptop i havew not used with home assistant in incognito mode, and i cannot get add user setting in sidebar order to work. i click on the user name, and it just makes the box disappear and doesnt do anything or add anything. i assumed i was going to have to hit next and then change the order as desired but it didnt actually work. i have only restarted the core so far, and not the whole odroid n2+, i will restart it when i next can in a few hours. (not home, necessary for climate control for temperature sensitive animal, paranoid person.) 

p.s. seriously this is an amazing improvement that has so many frekin awesome features and helps with administrive control so much its awesome.

**Comment by thomasloven** [comment]
Please try 2.0.1

**Comment by jatgm1** [comment]
So I tried restarting after upgrading, the core then the whole system, and tried with the app, chrome on Android, chrome on windows and whatever internet explorer is called now that's based on chrome. Also Firefox on windows. I'll restart it again and try again but it disappears when I click the user. Doesn't let me click next

**Comment by jatgm1** [comment]
It actually looks like even if I don't select a user, if the drop box closes it goes away but it lets me continue without a user and just doesn't do anything. I'll try a clean install

**Comment by jatgm1** [comment]
Ok so I removed the integration, restarted core, restarted system, removed from hacs store, restarted core, restarted system, added back in hacs, restarted core, restarted system, added integration, restarted core, restarted system. Still doesn't let me add users. Sorry. I think that's like a reasonable attempt to see if that was what's wrong but idk what to do from here. Anyone else with this issue or just me?

**Comment by jatgm1** [comment]
Odroid n2+ most up to date version of everything as far as I can tell

**Comment by thomasloven** [comment]
I found the problem. It will be fixed in 2.0.2

**Comment by jatgm1** [comment]
You are fantastic. This changes so much about what I can do with home assistant it's frekin sweet. Any interest in adding the features of authenticated to this so it covers all my administrative needs?

**Comment by jatgm1** [comment]
hey, just checking if the last update was supposed to fix it because i am still having the issue of not being able to add users. i will try again with other browsers and restart the hardware again and clear caches again.

**Comment by jatgm1** [comment]
It's fixed thank you :)
