### ISSUE TITLE
Toast service missing from 2.0?

### ISSUE THREAD

**Issue by shogun168** [thomasloven/hass-browser_mod#369]
I updated to the new 2.0 version and reinstalled browser_mod from scratch. What happened to the toast service? I really hope it wasn't taken away because it was the only thing I used this mod for (having a discreet 2000ms toast message pop up from the bottom to confirm that actions were done when I tapped on a button). 

Couldn't find reference to it on the services page aside from pop up which isn't the same thing?

**Comment by thomasloven** [comment]
It's back.
