### ISSUE TITLE
Popup card I can't get it to work

### ISSUE THREAD

**Issue by EMP83** [thomasloven/hass-browser_mod#371]
Hello, this is my old browser mod configuration and I can't get it to work with the browser mod. 
I noticed that as long as I didn't have a registered browser id it worked. 

Can someone guide me how to fix this?

![Captură de ecran 2022-09-04 090825](https://user-images.githubusercontent.com/36104474/188301816-877a0410-c5ec-4ba8-8279-4e48a9c629f0.jpg)

`type: vertical-stack
title: TV
cards:
  - type: custom:mini-media-player
    entity: media_player.tv_lg_oled
    tap_action:
      action: fire-dom-event
      browser_mod:
        command: popup
        style:
          border-radius: 20px
          '--ha-card-border-radius': 0px
        title: LG 55B9PLA
        card:
          type: custom:tv-card
          entity: media_player.tv_lg_oled`

**Comment by browetd** [comment]
If you are using BROWSER_MOD version 1, this should be the right format (despite the fact that indentation is not correctly displayed)... If you are using version 2, the format has totally changed and this code will  not work anymore...  See documentation...

**Comment by darkkatarsis** [comment]
I also have a problem with bringing the popup back to work after switching to 2.0. Referring to the updated documentation - the code seems to be correct

`
- type: 'custom:mini-media-player'
            entity: media_player.projector
            toggle_power: false
            artwork: default
            group: true
            icon: custom:projector
            hide:
              icon_state: false
            hold_action:
              action: more-info
            tap_action:
              action: fire-dom-event
              browser_mod:
                service: browser_mod.popup
                data:
                  title: Popup
                  content:
                    entities:
                      - entity: light.hue_outdoor_pedestal_2
                    type: entities
`

**Comment by EMP83** [comment]
> If you are using BROWSER_MOD version 1, this should be the right format (despite the fact that indentation is not correctly displayed)... If you are using version 2, the format has totally changed and this code will not work anymore... See documentation...

That's the problem, I can't get it to work...

**Comment by browetd** [comment]
@darkkatarsis I had one of my browser not working for pop-up windows because that browser was not enabled in BROWSER_MOD... Check that the option "Enable this browser as a Device in Home Assistant" is enabled in browser mod settings...

**Comment by browetd** [comment]
@EMP83 the code in version 2 should be:

`
    type: custom:mini-media-player
    entity: media_player.tv_lg_oled
    tap_action:
      action: fire-dom-event
      browser_mod:
        service: browser_mod.popup
        style:
          border-radius: 20px
          '--ha-card-border-radius': 0px
        title: LG 55B9PLA
        content:
          type: custom:tv-card
          entity: media_player.tv_lg_oled`

**Comment by EMP83** [comment]
Thank you for help. 
I just tried this configuration but unfortunately it still doesn't work.

**Comment by thomasloven** [comment]
You're missing `data:`
https://github.com/thomasloven/hass-browser_mod#how-do-i-update-a-popup-from-the-browser-mod-15

**Comment by browetd** [comment]
@EMP83  Correct, I missed the data filed but make sure your browser_id is enabled in browser_mod parameters.
 So it should be:

type: custom:mini-media-player
entity: media_player.tv_lg_oled
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      style:
        border-radius: 20px
        '--ha-card-border-radius': 0px
      title: LG 55B9PLA
      content:
        type: custom:tv-card
        entity: media_player.tv_lg_oled

**Comment by EMP83** [comment]
I did it, thank you all for your help,
Here is the final configuration, it may help someone:

```
type: vertical-stack
title: TV
cards:
  - type: custom:mini-media-player
    entity: media_player.tv_lg_oled
    tap_action:
      action: fire-dom-event
      browser_mod:
        service: browser_mod.popup
        style:
          border-radius: 20px
          '--ha-card-border-radius': 0px
        data:
          title: LG 55B9PLA
          content:
            type: custom:tv-card
            entity: media_player.tv_lg_oled
            mac: XX:XX:XX:XX:XX:XX
            name: TV LG
            tv: true
            power:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.lg_on_off
            back:
              service: webostv.button
              service_data:
                entity_id: media_player.tv_lg_oled
                button: BACK
            source:
              action: call-service
              service: input_boolean.toggle
              service_data:
                entity_id: input_boolean.lg_audio_remote
            home:
              service: webostv.button
              service_data:
                entity_id: media_player.tv_lg_oled
                button: HOME
            channelup:
              service: webostv.button
              service_data:
                entity_id: media_player.tv_lg_oled
                button: CHANNELUP
            info:
              service: media_player.select_source
              service_data:
                entity_id: media_player.tv_lg_oled
                source: Live TV
            channeldown:
              service: webostv.button
              service_data:
                entity_id: media_player.tv_lg_oled
                button: CHANNELDOWN
            up:
              service: webostv.button
              service_data:
                entity_id: media_player.tv_lg_oled
                button: UP
            left:
              service: webostv.button
              service_data:
                entity_id: media_player.tv_lg_oled
                button: LEFT
            select:
              service: webostv.button
              service_data:
                entity_id: media_player.tv_lg_oled
                button: ENTER
            right:
              service: webostv.button
              service_data:
                entity_id: media_player.tv_lg_oled
              button: RIGHT
            down:
              service: webostv.button
              service_data:
                entity_id: media_player.tv_lg_oled
                button: DOWN
            volume_mute:
              service: webostv.button
              service_data:
                entity_id: media_player.tv_lg_oled
                button: MUTE
            volume_up:
              service: webostv.button
              service_data:
                entity_id: media_player.tv_lg_oled
                button: VOLUMEUP
            volume_down:
              service: webostv.button
              service_data:
                entity_id: media_player.tv_lg_oled
                button: VOLUMEDOWN
      icon: mdi:television
      name: TV LG
```
