### ISSUE TITLE
Browser_mod 2.0 removed the set_theme service. is it complicated to add it back?

### ISSUE THREAD

**Issue by okets** [thomasloven/hass-browser_mod#372]
Well, my request is simple:
Browser_mod 2.0 removed the `set_theme `service. is there a way to add it back?
I was relaying on this feature in my custom cards but I guess I will reverse engineer the old code to do it now.
hopefully you can add it back in the future.

**Comment by robsonke** [comment]
Isn't the standard frontend.set_theme an alternative?

**Comment by okets** [comment]
Not if you try to change a theme for a specific browser.
I am writing a custom card that displays tabs, each tab can be assigned a theme.
so when a user changes tabs, the theme changes too.
In my example: I created a smart "room-card" that has 3 tabs: Room-Control, Media, Security.
each one changes the whole theme for the user interface.
If I use ` frontend.set_theme`, all browsers, for all users, will change themes when a user presses a tab, not just the device that was used.

**Comment by okets** [comment]
I planned to release my `custom:tabs-card` as a HACS frontend card.
unless this feature will be re-added, I will try to change themes without browser_mod before publishing it.

**Comment by okets** [comment]
**I got it working again using the following sections of code I found in the previous version: (sorry for the lost indentations)**
I will be using this code in my custom-card, It will remove the dependency for browser_mod and make my card easier to use.
however, this is such a small fix and I hope it will be added again for other users of this awesome integration.

export function fireEvent(ev, detail, entity=null) {
  ev = new Event(ev, {
    bubbles: true,
    cancelable: false,
    composed: true,
  });
  ev.detail = detail || {};
  if(entity) {
    entity.dispatchEvent(ev);
  } else {
    var root = lovelace_view();
    if (root) root.dispatchEvent(ev);
  }
}

export function lovelace_view() {
  var root = document.querySelector("hc-main");
  if(root) {
    root = root && root.shadowRoot;
    root = root && root.querySelector("hc-lovelace");
    root = root && root.shadowRoot;
    root = root && root.querySelector("hui-view") || root.querySelector("hui-panel-view");
    return root;
  }

  root = document.querySelector("home-assistant");
  root = root && root.shadowRoot;
  root = root && root.querySelector("home-assistant-main");
  root = root && root.shadowRoot;
  root = root && root.querySelector("app-drawer-layout partial-panel-resolver");
  root = root && root.shadowRoot || root;
  root = root && root.querySelector("ha-panel-lovelace");
  root = root && root.shadowRoot;
  root = root && root.querySelector("hui-root");
  root = root && root.shadowRoot;
  root = root && root.querySelector("ha-app-layout")
  root = root && root.querySelector("#view");
  root = root && root.firstElementChild;
  return root;
}

**this is how I call it now (commented the old code for reference):**
function setTheme(theme){
    //const _deviceID=localStorage.getItem("lovelace-player-device-id");
    // hass.callService('browser_mod','set_theme',{
    // 										theme: theme,
    // 										deviceID:[_deviceID]});
    fireEvent(
		    "settheme",
		    { theme: theme },
		    document.querySelector("home-assistant")
    );
}

**Comment by thomasloven** [comment]
It's back, and better!
