### ISSUE TITLE
Browser Mod does not appear in Integrations

### ISSUE THREAD

**Issue by abwino** [thomasloven/hass-browser_mod#373]
My Home Assistant version: 2022.8.6

**What I am doing:**
Trying to update from BM 1 to BM 2.1

**What I expected to happen:**
BM to appear in when trying to add the integration (Devices/Services)

**What happened instead:**
Browser Mod not listed in integrations

**Minimal** steps to reproduce:
Commented out browser_mod mentions in configuration.yaml
Deleted all browser mod 1 files and folders from custom_components
Downloaded latest files and copied to config/custom_components/browser_mod
Restarted HA
Tried to add integration as per the install instruction for 2.1, Browser Mod was not listed

Triple checked all files and folders present and correct, restarted several times

n/a
```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:**
None
```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [ X] Have made sure I am using the latest version of the plugin.

- [ X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [ X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

<img width="471" alt="Screenshot 2022-09-04 at 11 11 40" src="https://user-images.githubusercontent.com/22999854/188308381-a600d892-67b6-45a3-ab4e-7bf52d6cd47b.png">

**Comment by thomasloven** [comment]
Anything about browser_mod in your Home Assistant logs?

**Comment by abwino** [comment]
Hi, happy Sunday!
Unfortunately there's nothing.
One thing I did notice was that after I had removed all the version 1 files and folders, HACS thought that browser_mod was still installed.
I'm not sure what to try next.
Thanks.

**Comment by thomasloven** [comment]
Why didn't you just update through HACS?

**Comment by abwino** [comment]
I did. But I hadn't read the instructions about removing all traces of v1, so I thought I'd better start from scratch. Even after the HACS update the integration didn't appear in the list.

**Comment by plats98** [comment]
i have now solved the issuse :) 
A complete browser refresh was needed, and then all was as it should. (got help on another site)

**Comment by mattbrad2** [comment]
Still not working for me, even after reloading cache, new browser, etc.
