### ISSUE TITLE
Popup style from 1.x to 2.x

### ISSUE THREAD

**Issue by Ameglialuna** [thomasloven/hass-browser_mod#374]
I had a popup in 1.x with some applied style (less rounded borders):

`

    action: fire-dom-event
    browser_mod:
      command: popup
      title: Room
      style:
        $: |
          .mdc-dialog 
          .mdc-dialog__container 
          .mdc-dialog__surface {
            border-radius: 8px;
          }
          .mdc-dialog 
          .mdc-dialog__content {
             padding: 40px 40px !important;
          }
      card:
        type: vertical-stack
        cards:
`
now I upgraded to 2.0 changing syntax as suggested:

`

    action: fire-dom-event
    browser_mod:
       service: browser_mod.popup
       data:
          title: Room
          style:
            $: |
              .mdc-dialog 
              .mdc-dialog__container 
              .mdc-dialog__surface {
                border-radius: 8px;
              }
             .mdc-dialog 
              .mdc-dialog__content {
                 padding: 40px 40px !important;
              }
         content:
            type: vertical-stack
            cards:
`

The popup card works but the style is not longer applicated.
What's wrong?

**Comment by chertvl** [comment]
Now we have ```style:``` key that required ```string``` of the style variables. You can look --popup variables in F12 Dev menu of Chrome, then write them in ```style:``` key of ```data:```.
Please take a look in my issue https://github.com/thomasloven/hass-browser_mod/issues/375 , you need to write styles as string,

**Comment by Ameglialuna** [comment]
I take a look, thanks!

**Comment by Ameglialuna** [comment]
Now with string:

style: "--ha-dialog-border-radius: 8px; --padding-x: 40px; --padding-y: 40px;"

the border radius works again but not the padding and I don't understand why

**Comment by Herbs851** [comment]
@Ameglialuna 


> the border radius works again but not the padding and I don't understand why

If you find the solution, I'm interested ;)

**Comment by thomasloven** [comment]
Because the `--padding` variables aren't meant to be user facing.
Add margins to the card itself with card-mod instead.

**Comment by pickonedev** [comment]
Can someone please tell me how can I remove the header of the popup?

Thanks

**Comment by thomasloven** [comment]
Don't give it a title.

**Comment by pickonedev** [comment]
Thank you!!!

**Comment by ElRubio17** [comment]
I should move all style from outside to inside the card.  It's not comfortable.  I chose the style out because it was cleaner and faster to read.  can you get it back?
Why “card-mod-more-info-yaml” in themes doesn't work?
In release 1.53 work and in v2 doesn’t work. 
I tried to go back and when I have reinstalled v1.53 it worked again.
I tried to copy your example and that doesn't work too. 
Any ideas?

**Comment by Ameglialuna** [comment]
> Because the `--padding` variables aren't meant to be user facing. Add margins to the card itself with card-mod instead.

I tried to use card_mod on the card and it works but the popup remains of the orginal size

. ![popup1](https://i.postimg.cc/P5JTRFQs/popup.png)

**Comment by thomasloven** [comment]
The border radius variable was broken.
Some things have changed in the Home Assistant dialogs since I started working at this months ago...

I also added --popup-padding-x and --popup-padding-y in 2.1.1.
Also card-mod support.

**Comment by Ameglialuna** [comment]
thanks!
