### ISSUE TITLE
popup background

### ISSUE THREAD

**Issue by herveaurel** [thomasloven/hass-browser_mod#378]
Amazing and thanks for the v2!
I see that the popup background depends on ha-card-background. On V1 the background depended on card-background-color.
As a result, my beautiful gradient HA background does not work on popups and causes a transparent, unreadable background.

Is it possible to change this parameter?

**Comment by chertvl** [comment]
Try to use

in themes.yaml:
```
  popup-background-color: var(--card-background-color)
```

or

```
service: browser_mod.popup
data:
  style: |-
    --popup-background-color: var(--card-background-color);
  content: []
```

**Comment by herveaurel** [comment]
Thank you you are a genius!!
