### ISSUE TITLE
Dismiss popup on "back" pressed - when using Android mobile app.

### ISSUE THREAD

**Issue by kulmegil** [thomasloven/hass-browser_mod#386]
My Home Assistant version: 2022.8.7

**What I am doing:**
I want to dismiss popup on mobile app.

**What I expected to happen:**
Popup is dismissed when phone "back" button is pressed.
This is standard for mostly any HA popup.

**What happened instead:**
Nothing

**Minimal** steps to reproduce:

```yaml
1) Create any popup
2) Login using mobile app
3) Attempt to dismiss popup using phone "back" navbar button (or gesture if you use that).
```

**Error messages from the browser console:**

```
none
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by chertvl** [comment]
Yup, same. Looks like 'back' action causes Companion closing instead of closing pop-up. I think pop-up dont catch this action.

**Comment by slovdahl** [comment]
With browser mod 1 this worked fine, the popup was closed when the 'back' action was initiated.

**Comment by Vansmak** [comment]
Ah so i am not alone. However I don't remember it happening on 2.0. After i changed all of mine to the new formst they were working. It's after the last update 2.1?

**Comment by kulmegil** [comment]
I can confirm the issue looks resolved to me as well.
I guess we can close this one.
