### ISSUE TITLE
Option to choose to hide header or sidebar on mobile devices only

### ISSUE THREAD

**Issue by nikrays** [thomasloven/hass-browser_mod#387]
Add Option to choose to hide header or sidebar on mobile devices only

**Comment by thomasloven** [comment]
- Register your mobile device browser
- Hide the hearder for that browser

**Comment by nikrays** [comment]
This is extremely inconvenient, since you will have to register the browser id of a local connection and through a remote connection, and objects are also created that clog the log with unnecessary events and states.  I would like to, since it is implemented approximately in a kiosk mode, the "mobile" key solves all these problems, I will be grateful ..

**Comment by thomasloven** [comment]
Then set the Browser ID of all your mobile devices to "mobile"
