### ISSUE TITLE
Stuck on "Loading data" after upgrading to release 14

### ISSUE THREAD

**Issue by IDmedia** [thomasloven/hass-browser_mod#39]
I have two wall-mounted Android tablets that are unable to access Home-Assistant after upgrading to release 14. Everything works as intended once I downgrade back to 13.2. I have no issues on my Android phone or any other devices (PCs).

I have two wall-mounted Lenovo Tab2-X30F with Android 6.0.1 running the latest version of Chrome/Webview. After upgrading they are stuck on "Loading data..." without ever finishing. I've tried to remove all cache/webstorage data and reboot the two devices without any luck. Downgrading to version 13.2 of browser_mod solves the loading issue. Any ideas?

**Comment by pollinolas** [comment]
Same problem here, I'm pending of downgrade to confirm this

**Comment by groenmarsmannetje** [comment]
Same here. Version 14 breaks the loading of the front end and makes HA totally unusable. Took me a while to pinpoint this to this update.

**Comment by jysaloma** [comment]
Same here and if you end up this situation. Open webconsole and block the url with this file browser_mod.js. Downgrade to 13.2 from HACS.

**Comment by thomasloven** [comment]
14.1 should fix this.

**Comment by pollinolas** [comment]
Hi, im having troubles yet when access by cloud, look likes go all fine but after a while don't load the tabs(hass io, development tools, etc) I need to reload the page to show that info, 
I'm using version 15
Regards and sorry for my english
