### ISSUE TITLE
Binary_sensor motion time

### ISSUE THREAD

**Issue by pickonedev** [thomasloven/hass-browser_mod#394]
I think that binary_sensor show as motion (which detects the screen touches), could open many other functionalities if it will go off instantly every time. Should have 1 ms delay till gets off again, after a touch of the screen

I think that this could add many other things to this feature. At least, if not everyone needs it, should have an input time config, to set the time of binary_sensor to go off.

Imagine that the sensor will go off instantly after when on:
- You could count how many screen touches you done and make some automations
- You can add a sound media for that device, having some custom touch sounds of the screen

**Comment by thomasloven** [comment]
That would send two events every millisecond and likely bring Home Assistant and possibly your entire network to a screeching halt.
