### ISSUE TITLE
Non admins can delete browser registrations

### ISSUE THREAD

**Issue by henriklund** [thomasloven/hass-browser_mod#398]
My Home Assistant version: 2022.8.7

**What I am doing:**
Accessing the Browser_mod (2.1.0) in the sidebar with a non admin user.

**What I expected to happen:**
'Registered Browsers' section should be inaccessible to non admin users or at the very least reduced to only view the current device.
Prior functionality (requiring user to temporary being upgraded to admin) worked fine. This is a step forward, however, maybe consider a global toggle enabling / disabling the Browser_mod so that this functionality only is accessible when desired (for instance during a setup). 

**What happened instead:**
Any non admin user can see and remove browser registrations.

**Minimal** steps to reproduce:
- Add a non (non admin) user to Home Assistant
- Log in with user
- Remove another Browser registration from Browser Mod (this is possible, yet should not be)

**Error messages from the browser console:**
N/A

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
Please check the release notes for new versions.

> - Browser registration can be locked so non-admin users can't unregister their browsers.

There's a lock in the Registered Browsers card.

**Comment by henriklund** [comment]
It seems as if you go from v2.0.x to v2.1.0, the lock will not suffice. You need to (and this is on me for not doing so before reporting) clear the cache on _all_ devices when going to v2.1. This goes for both browser as well as (Home Assistant) app. Otherwise non admins will retain the ability to delete other (even locked) Browser IDs.
