### ISSUE TITLE
Multiple Google Cast devices?

### ISSUE THREAD

**Issue by wormiedk** [thomasloven/hass-browser_mod#404]
How would I go about setting up multiple Google Cast devices? I have two Google Nest devices but am unsure how to register number two?

**Comment by thomasloven** [comment]
You can't. They will look like the same Browser and all react to the same services. It's impossible to uniquely identify a cast device.

**Comment by wormiedk** [comment]
Is that also the reason that pop up card did not work on the old version? It seems to work on version 2...

**Comment by swiergot** [comment]
@wormiedk I suggest to use CATT. That way your Cast device will get a unique ID.
