### ISSUE TITLE
Registered Device "List" have something strange

### ISSUE THREAD

**Issue by SiriosDev** [thomasloven/hass-browser_mod#410]
My Home Assistant version: 2022.8.7
Browser Mod Version 2.12
the picture describes better, so:
![image](https://user-images.githubusercontent.com/26876994/188913420-824ff4a7-657c-4feb-b225-9280aa554c4f.png)
Note:
If you visit the browser mod page after visiting the user page, the issue fix automatically

**Comment by thomasloven** [comment]
Should be fixed in 2.1.3
