### ISSUE TITLE
Register new browser by default on

### ISSUE THREAD

**Issue by glienart** [thomasloven/hass-browser_mod#414]
I sometimes use another computer to access HA, but the dashboard will not show the popup as the new browser is not registered. I always use the call service from a scrip don't know if that matters.
Would it be possible to register all new browsers automatically and remove them after a certain period of unactivity?

**Comment by alexschwantes** [comment]
I second this. The fact that we now have to manually register devices basically kills this for me. How is everyone who uses it supposed to know to do this..

**Comment by jatgm1** [comment]
Agreed. This was super useful. Also being able to manually turn on the camera and everything else for another browser instance would be useful. Everything else about the addon is an awesome improvement.

**Comment by prbtt** [comment]
BM 2.0 should have been better than 1.0 in every way, but this missing feature makes it worse for a lot of users out there. I created my dashboard so anyone who decides to use home assistant from any device will have it working out of the box. Part of the functionalities of my dashboards include calling browser mod from a script, which can't be done anymore unless your browser is registered.

**Comment by jatgm1** [comment]
Yeah I mean can this just be added in now? Or can you just make version 1.0 work with 2.0 so that you can use 1.0 to automatically register the browser and 2.0 for everything else? I mean that was an important feature, administrative controls basically.

**Comment by jatgm1** [comment]
It sux because everything else is like perfect but I can't use it because it doesn't automatically register and turn everything on, or allow you too, so like I'm kinda just waiting hoping eventually I can. 🤷‍♂️
