### ISSUE TITLE
browser_mod 2.x - settings moved to different location [if possible]

### ISSUE THREAD

**Issue by pejotigrek** [thomasloven/hass-browser_mod#416]
seeing how my sidebar grows with "important" things - is it possible to move **Browser Mod** settings to different location? the perfect place would be general Home Assistant settings panel, but an option on integrations dashboard would be good too.

_I'm afraid that I'm asking too much and it's not that easy, but I had to ask ;)_

**Comment by marrobHD** [comment]
Actually, you can!

1. Open the sidebar
2. hold & tap on the "H" from Home Assistant
3. Choose your Action (x -> remove; + -> add)

**Comment by pejotigrek** [comment]
> Actually, you can!

you're talking about editing the sidebar menu, right?
this method only hides from sidebar - and that's not the complete solution. if I want to change something then I need to add it again.

I was thinking more like a "CONFIGURE" button like with other integrations:

![image](https://user-images.githubusercontent.com/10796588/189592129-62ba5528-fcbd-4bbe-9807-a1fd0bf103fa.png)

just to get the configuration panel without blowing up the sidebar.

**Comment by pejotigrek** [comment]
right, this should be enough for temporary by-pass/workaround, in the meantime I'll keep my fingers crossed for UI solution :)

**Comment by thomasloven** [comment]
Even if removed, you can always access the configuration panel through `https://<your HA URL>/browser-mod/`
