### ISSUE TITLE
Wow, Ultra Scary! But Bravo!

### ISSUE THREAD

**Issue by LordNex** [thomasloven/hass-browser_mod#419]
If I ever needed a piece of software to back door someone’s phone so I can keep an eye on their camera and such. I now know where to turn. 

I guess this post is more of a statement or conversation more than anything else. Thank god our parents didn’t have this level of ability to snoop into our lives. For us was “if the street lights are off, you better be home or the phone has better be ringing from the closest pay phone you could find. 

I initially installed this in hopes of tieing it in with Music Assistant so that I can play all of my library of music and such through my trucks Bluetooth connection. But MA only sees local google devices, which this fits in perfectly for then being turned into a browser media player and cast to it. 

But all the other features and the ability to activate the camera, and I’m guessing, mic on the device makes this so much more. All of which can be hidden from whoever you setup Home Assistant for? Scary days we live in! Glad I studied computers as much as I did.

**Comment by LordNex** [comment]
LOL someone 👆

This could so be used as a device to spy on people us all I was pointing out. Not like I'm doing it. If that was the case I'd keep it to myself and not say anything about it now wouldn't I. Plus my son is over 18 and has his rights. But dam there isn't any privacy in the world anymore.

**Comment by thomasloven** [comment]
A valid concern.
For privacy this relies on the functionality built into the browser which often comprises
- A prompt before a website may activate the camera
- An indication in the browser tab or window header when the camera is active
- The requirement to interact with the page before the camera can be activated

The camera will not work on e.g. a smartphone unless it is unlocked and the Home Assistant app is open.

Personally, I'd be more worried of the GPS device tracking in the Home Assistant Companion apps.
