### ISSUE TITLE
[FR] Bluetooth Support

### ISSUE THREAD

**Issue by LordNex** [thomasloven/hass-browser_mod#420]
Now that Home Assistant supports BT and also Bluetooth Proxies, is there any possibility of utilizing the Bluetooth on the device for control? Such as being able to connect to the browser mod on a device and then be able to access any Bluetooth devices that are around it.

**Comment by thomasloven** [comment]
That's way outside the scope of this integration.

**Comment by LordNex** [comment]
Why would it be so hard to add BY support? I would guess most of the logic for the communication is already baked into HA? Maybe I just don't understand why you feel it's outside the scope of this integration. Wouldn't it just improve it as a feature request does?

**Comment by FrnchFrgg** [comment]
Arbitrary access to Bluetooth from a browser is at best frowned upon and locked behind permission settings, at worst outright not supported. It would be more realistic to hope for another integration supporting that feature and dedicated to the companion apps and only them. Or a feature directly integrated in these apps.
