### ISSUE TITLE
Sidebar Settings menu not working in Kiosk Pro browsers at all

### ISSUE THREAD

**Issue by chheiss** [thomasloven/hass-browser_mod#421]
In Kiosk Pro browsers, the browser_mod settings page is displayed as empty. It is thus not possible to register that browser with browser_mod, making it unusable.
https://www.kioskgroup.com/pages/kiosk-pro-software

Worked fine with 1.x before upgrading to 2.x version.

**Comment by Juggler00** [comment]
I’m seeing the same thing. I’ve tried the different settings available in Kiosk Pro, but cannot get the browser_mod settings to display.

**Comment by Juggler00** [comment]
I’ve updated to the latest version and still see a blank page when I navigate to the browser_mod settings.
