### ISSUE TITLE
option to automatically add browser instead of registering?

### ISSUE THREAD

**Issue by jatgm1** [thomasloven/hass-browser_mod#425]
Is there a way to automatically add anything that logs in that has not been registered yet? and allow an admin to charge the name and lock it? And make a state that contains the username of the last user that logged in, name of browser (browsermod name?) and ip address?

**Comment by alexschwantes** [comment]
see the feature request #414

**Comment by jatgm1** [comment]
Oh u did it? Awesome:) Idk how it works I don't think I got an update available from hacs.
