### ISSUE TITLE
Stream radio channel problem

### ISSUE THREAD

**Issue by poudenes** [thomasloven/hass-browser_mod#43]
Hi All,

GREAT creation !!! now my tablet at the wall is a media player as well!!
I created something to stream radio channels to tablet but after 30 seconds it stop.
Everything work correct on my iMac browser (media player now as well) without any problem.

Im using Fully Kiosk on my tablet.
open the link directly in Chrome on Tablet everything is ok.

**Comment by poudenes** [comment]
In fully Kiosk I did follow:

Settings > Advanced Web Settings > Fake User Agent String:

Chrome 74 on Windows

And now the 30 seconds stop problem is gone…

**Comment by poudenes** [comment]
Hi @thomasloven  can you reopen this. I have problems when I change this with all the tabs of HA, site is so slow I must change back to default User Agent., HA is working perfect now. Only the 30 sec stop issue is back.

**Comment by poudenes** [comment]
Is there something I can do? To see why I have those issues?

**Comment by niccolobusato** [comment]
@poudenes  how can you be able to play the radio? can't play any sound... only tts works right now. can u share your code? thanks!!

**Comment by drthanwho** [comment]
Hey, are you still having the issue. Stumbled upon this and was having a look at your set up (looks amazing by the way. I will definitely be having a better look for inspiration for mine :smile: ) 

But I wanted to say I  quickly tried one of your radio links on mine and they worked without any stops (no 30s stops)

**Comment by thomasloven** [comment]
This issue has grown too old. If this is still a problem, please open a new issue.
