### ISSUE TITLE
Re-introduce blackout

### ISSUE THREAD

**Issue by pvmil** [thomasloven/hass-browser_mod#431]
Thanks for the great makeover of browser_mod
I got one question: can you re-introduce (as in the previous version of browser_mod) the blackout service? This would be really nice to save my screen

**Comment by FrnchFrgg** [comment]
I think you can do a similar thing with an automation: in 2.x registered browsers have a `binary_sensor` with `device_class: motion` which actually detects whether the browser was touched/used recently. Just trigger on that `binary_sensor` being `off` for five minutes and turn off the browser light.

In that automation I also send a `browser_mod.navigate` to get back to the main screen, which helps my Amazon Fire 5 (used as a wall panel) not to grind to a halt when my children last selected a cpu and memory hungry page (like a camera preview or similar).

**Comment by pvmil** [comment]
Thanks, I wasn't aware there's a binary switch for this now (replaceing the old service call). Nice implementation. I found the switch when looking at all entities for my specific browser/device

**Comment by pvmil** [comment]
Possibly this can be clarified by a screen shot in the documentation, something like 
![image](https://user-images.githubusercontent.com/14914859/190613593-3ad8556c-50ec-4254-9620-fb8580ba448a.png)
