### ISSUE TITLE
2 Cards on Popup

### ISSUE THREAD

**Issue by AxDevl** [thomasloven/hass-browser_mod#432]
Hi, so basically I’m trying to achieve something like this.

![](https://raw.githubusercontent.com/matt8707/hass-config/master/www/img/vacuum.png)

however because I’m not so strong at Yaml code I tried to replicate it in cards. I’ve successfully got the cards ready however cannot get them on that the vacuum map is on the right and the card with entities is on the left. I’ve tried the vertical and horizontal cards however always forces to have them vertical. 

Would appreciate some ideas how to do this. 

Thanks!

**Comment by FrnchFrgg** [comment]
I think you can use the [grid card](https://www.home-assistant.io/dashboards/grid/) for that effect. At least that's what I use and it accepts to put two cards sideways in a popup.
