### ISSUE TITLE
browser_mod 2.0 missing battery status of device

### ISSUE THREAD

**Issue by skycryer** [thomasloven/hass-browser_mod#435]
Maybe I can not find it but the devices in browser_mod 2.0 seem missing the battery status of the device. In old version it was available. Can you please add that again. Or where can I find it if it is there.

**Comment by rlowens** [comment]
Same question. Can't find battery level or charging status (both of which I used to pull out with template sensors so I could monitor my tablets' power level since some of them have poor power connections).

**Comment by janfajessen** [comment]
Same for me, I need It because I use a old tablet that its not available the HA companion app to know the battery percent for automation like charge it automatically. It was perfect in browser mod 1. Can you please have this attribute in next updates. Thanks in advance

**Comment by thomasloven** [comment]
It's not an attribute. It's a separate entity.

**Comment by janfajessen** [comment]
Ok, but I can't find it.  There are directly 9 sensors such as motion sensor, screen size, light/dark Mode, User agent... but no battery level.  Could you explain how to find it please?  It is the only way to know the battery because I use it on an old tablet that does not accept the HA app or fully kiosk.  Thanks in advance

**Comment by thomasloven** [comment]
I see the problem now.

**Comment by janfajessen** [comment]
Thanks for the update!  Now I can use the battery sensor so I don't have to charge the tablet all day.  You have done a wonderful job again

**Comment by skycryer** [comment]
I did an update to browser_mod but still do not see any battery info. Is that an attribute, extra sensor? Where should I see it?

**Comment by rarroyo6** [comment]
Same issue here. I have 3 tablets set up, the battery level shows up on 1 tablet, but not on the other 2.
It used to show up on all 3 with version 1.
Is there anything that should be enabled or set-up on the tablets?
