### ISSUE TITLE
No popups when screen is off ('unavailable sensors')

### ISSUE THREAD

**Issue by KentuckyMC** [thomasloven/hass-browser_mod#437]
My Home Assistant version: 2022.9.4

**What I am doing:**
I've an automation that sets a popup when doorbell is ringed (with camera feed), or when I have to set the trash bins outside. Before this worked as well when my screen is off. So when my screen popped on, I saw the popup immediately. 

**What I expected to happen:**
To see popups being put on the screen, even if the screen is off. 

**What happened instead:**
No popups where set.

**Minimal** steps to reproduce:
Set popups when screen is off (fully kiosk off). Then set it on so you can see the popup. 

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by jazzyisj** [comment]
Both of your use cases seem like instances where you would want your kiosk screen to be on anyway.  Have you thought about adding a command in your script/automation to turn the screen on before instantiating the popup?  That would likely resolve your issue.

**Comment by KentuckyMC** [comment]
Hey @jazzyisj, thanks for the response. 

Actually, I just want to set the popup on the screen, and the next time when I walk by (motion sensor) the screen will go on with the popup. That's how it worked in 1.x, it popped the dialog onto the screen, even if the screen was off. Your thought is more like a workaround for this issue. But when I'm not home, I don't have the need to set the screen from the tablet on to set a dialog (for waste collection for example). I just want it to put it in the background (with screen off), and when I come home and walk by, I see the dialog. Any thoughts why this worked in V1 and not in V2?

**Comment by KentuckyMC** [comment]
@jazzyisj No worries. That the popup is triggering is not the issue. The issue is that it's not rendering when the tablet goes screen on again. Weird part here is, that my 'screen on/off' is working fine with the new V2. So that switch seems to work even if the tablets screen is off. Weird that the popup itself can't be 'thrown on the screen' when the screen is off.

**Comment by KentuckyMC** [comment]
Still nobody that has an idea for this issue? I see the other issue with the 5 minutes bug is open as well. Can't find a solution to fix this. I've switched from the Fully Kiosk Browser to the Fully Kiosk Single App, to try if that is fixing it. But unfortunately it isn't. I see that my tablet still is online and responds to pinging, so it's not the wi-fi part. Something is weird since the 2.0 update with the 5 minutes timeout of browser mod.

**Comment by jasongabler** [comment]
> Still nobody that has an idea for this issue? I see the other issue with the 5 minutes bug is open as well. Can't find a solution to fix this. I've switched from the Fully Kiosk Browser to the Fully Kiosk Single App, to try if that is fixing it. But unfortunately it isn't. I see that my tablet still is online and responds to pinging, so it's not the wi-fi part. Something is weird since the 2.0 update with the 5 minutes timeout of browser mod.

I believe I am experiencing the same issue a similar setup.  Browser_mod is automated to pop up when I have motion from my Reolink WiFi doorbell. Using motion gives me a jump on the activity and people also have to wait less for me to realize whose outside once they ring the bell. I believe that extra time since being triggered contributes to the problem, as when I am coming home and step inside the house, the screen comes on and browser_mod is already up and counting down to pop down.

I'm going to change the trigger to be a button press for easier and more accurate testing and report back here.
