### ISSUE TITLE
Popups can not be used on dashboard tabs with View Type: Panel (1 card)

### ISSUE THREAD

**Issue by mkuhnke71** [thomasloven/hass-browser_mod#442]
My Home Assistant version: 2022.9.4

**What I am doing:**
Creating popups on a dashboard that shows a picture element in panel view mode.  Since it only allows 1 card it wont load the popup cards

**What I expected to happen:**

**What happened instead:**
popups are not loaded

**Minimal** steps to reproduce:
Create a dashboard
Set the View Type of the dashboard to "Panel (1 card)"
you wont be able to add more that one card, so add the popup card in the raw yaml.
you can add them but then you get an error on the screen

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x ] Have made sure I am using the latest version of the plugin.

- [x ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
![Screenshot 2022-09-16 105203](https://user-images.githubusercontent.com/58753339/190679731-d406e0d0-9c35-41fa-8928-150969e12291.JPG)

**Comment by Alfiegerner** [comment]
@mkuhnke71 - did you find a solution to this?  It looks like I have the same setup of you with floorplan on a panel.  I'm thinking of using card-mod css as a workaround but haven't worked out the css yet. Cheers!
