### ISSUE TITLE
Browser_mod panel is empty cant do anything : Uncaught SyntaxError: Identifier 't' has already been declared (at browser_mod_panel.js:1:1)

### ISSUE THREAD

**Issue by Electronlibre2012** [thomasloven/hass-browser_mod#448]
My Home Assistant version: 2022.9.5

**What I am doing:**
i install with HACS, restart, no panel "Browser_mod". then Integration add, restart. Clic on Browser_mod side panel is empty

**What I expected to happen:**
that see options to register the browser

**What happened instead:**
side panel is empty

**Minimal** steps to reproduce:
delete integration, restart. Delete Browser_mod, restart. Réinstall Browser_mod, restart. Reinstall integration, restart. Browser_mode side panel still empty. Restart host, same result.

**Error messages from the browser console:**

```
browser_mod_panel.js:1 Uncaught SyntaxError: Identifier 't' has already been declared (at browser_mod_panel.js:1:1)
```

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by Electronlibre2012** [comment]
find a glitch : 
 right click on the panel -> open in a new window, and the panel display!!! and i can check the register box! 4 hours for that lol

SOLVED

**Comment by sstratoti** [comment]
Hi @thomasloven - I experienced this issue as well and figured out how to resolve it by following your https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins guide, but I do think this may be a bug still.

When installed via HACS, this is added as a lovelace resource. I kept seeing this error described above:
`Uncaught SyntaxError: Identifier 't' has already been declared (at browser_mod_panel.js:1:1)`

In your troubleshooting steps, you wrote:

> Uncaught SyntaxError: Unexpected identifier
> You may have specified the resource as type: js when it's supposed to be type: module. Read the docs again to make sure.
https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins#uncaught-syntaxerror-unexpected-identifier

So what I did to resolve this was in my configuration.yaml I added an extra_module_url to /browser_mod.js and then removed the resource link under dashboards. Once this was done and I restarted, I was able to view the browser_mod panel in my dashboard.

Does something need to be changed with the install or with the instructions? Thanks!

**Comment by pergolafabio** [comment]
I also have it defined like below, but when i open browser mod in sidepanel, its always blank, i need to hard refresh it.... On chome its not an issue, but on companion thats not possible

```
frontend:
  themes: !include_dir_merge_named themes 
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
    - /browser_mod.js
```

**Comment by daniele-athome** [comment]
I can confirm this bug happening on Chromium version 132.0.6834.110 (Linux) and on the latest Home Assistant Android app (on Android 5 so really old WebView, but the issue happens on latest Chromium too and on my Pixel 8 running Android 15, so latest WebView).

Force refreshing (Ctrl+Shift+R) on Chromium does fix it, however any other way of refreshing isn't as effective (`location.reload(true)`, unregistering the service worker + disabling cache from devtools). What could be the difference between those really escapes me. Does anybody know any other way to refresh?

I'm stuck at this point, can't make it work at all from the Android 😭
