### ISSUE TITLE
Feature Request: Fully Kiosk Screensaver commands

### ISSUE THREAD

**Issue by cgarwood** [thomasloven/hass-browser_mod#45]
I have a few Kindle Fire tablets mounted to the wall. Instead of turning the screen off completely, I'm using Fully Kiosk Browser's Screensaver feature to set the screen to all black and set the brightness to 0. This way I can just tap the screen to wake it back up, instead of needing to hit the lock button.

Could you add an option to either customize what the blackout services do, or add a separate service for fully to start and end the screensaver?

**Comment by fourtrax01** [comment]
I don't now if they are ever going to reply to you but I got around this by using device vibration detection from within fully kiosk settings: device movement detection: turn on screen on movement and enable it that way the screen can be fully off but if I knock on the screen it wakes it back up you can also have it wake up if it hears sound. I have my screen turn off in darkness and I can either knock on the screen or with the sound one I just have to make some noise and the screen turns on.

**Comment by thomasloven** [comment]
The screensaver in FKB can be activated via rest commands. Use those instead.
