### ISSUE TITLE
Browsermod Nodered Service Calls

### ISSUE THREAD

**Issue by sumur1au** [thomasloven/hass-browser_mod#450]
I am having issues with Nodered automations using the browser mod navigate service. If one of my tablets goes into screensaver mode and the current page on the tablet isn't the designated home page of the tablet, an automation is used to navigate the tablet back to the home page. 

I have converted the automation to Browser Mod 2.0+ and the service now navigates all registered broswermod devices to navigate to the home page rather than the specific device assigned to in nodered. 

I believe there is an issue with the way the service call is formatted in Nodered vs the service call in the  developer tools UI. 

UI: 
![image](https://user-images.githubusercontent.com/65957586/191862482-49b88a36-c5df-47a1-ab06-fe1d58e9b0cd.png)

Nodered: 
![image](https://user-images.githubusercontent.com/65957586/191862520-ad0b2fd2-9774-4a9d-915e-44d162a9b6c2.png)

I am not sure if the target parameter is causing an incorrect service call using node red and applying it across all registered browsers. Any help would be appreciated.  There are no issues when calling this service from the Developers UI.

**Comment by aaamoeder** [comment]
Did you find a solution to this ? 

I'm currently having issues using nodered to call a popup on a specific device.
Even if I set the device correctly it still displays on all registered browser mod devices ...
Have not found how to pass on the target device_id correctly.
