### ISSUE TITLE
browser_mod.popup,  data_template and registered devices

### ISSUE THREAD

**Issue by mikaelhertzman** [thomasloven/hass-browser_mod#455]
Can anyone please explain how I achieve the following, or should I report a bug?

I want to display a dynamic popup when a button is pressed. Before 2.0 I was able to send data (like device_ID) to a script which showed the correct information.

Now I can't seem to show a popup without a browser_id in the backend (from a script), and I can't use data_template to handle this from the frontend.

I realize I could register the device to allow for popups from the backend but I don't see why I should register all devices just to show a popup. It would be another thing entirely if I wanted to use this for tablets or other displays, but I am just trying to show a dynamic popup here on any device at any time.

I can of course provide examples of my code if it helps, please let me know if that is required.

**Comment by alexschwantes** [comment]
dosen't seem like its supported. see feature request #414
