### ISSUE TITLE
browser_mod not generating unique IDs on restart (according to HA logs)

### ISSUE THREAD

**Issue by carlos-sarmiento** [thomasloven/hass-browser_mod#459]
My Home Assistant version: 2022.9.7

**What I am doing:**
Restarting Home Assistant

**What I expected to happen:**
Entities get created correctly.

**What happened instead:**
From Logs:
```
Platform browser_mod does not generate unique IDs. ID living-room-dashboard-Browser_visibility already exists - ignoring sensor.living_room_dashboard_browser_visibility
Platform browser_mod does not generate unique IDs. ID living-room-dashboard-Browser_userAgent already exists - ignoring sensor.living_room_dashboard_browser_useragent
Platform browser_mod does not generate unique IDs. ID living-room-dashboard-Browser_user already exists - ignoring sensor.living_room_dashboard_browser_user
Platform browser_mod does not generate unique IDs. ID living-room-dashboard-Browser_width already exists - ignoring sensor.living_room_dashboard_browser_width
Platform browser_mod does not generate unique IDs. ID living-room-dashboard-Browser_height already exists - ignoring sensor.living_room_dashboard_browser_height
```

**Minimal** steps to reproduce:

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by gffa325** [comment]
I have the same issue on version 2023.4.1. Any solution?

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:554
Integration: Sensor (documentation, issues)
First occurred: 18:35:27 (4 occurrences)
Last logged: 18:35:27

Platform browser_mod does not generate unique IDs. ID tablet-Browser_path already exists - ignoring sensor.tablet_browser_path
Platform browser_mod does not generate unique IDs. ID tablet-Browser_visibility already exists - ignoring sensor.tablet_browser_visibility
Platform browser_mod does not generate unique IDs. ID tablet-Browser_userAgent already exists - ignoring sensor.tablet_browser_useragent
Platform browser_mod does not generate unique IDs. ID tablet-Browser_user already exists - ignoring sensor.tablet_browser_user
