### ISSUE TITLE
Issue with large: true on pop-up

### ISSUE THREAD

**Issue by ha14937** [thomasloven/hass-browser_mod#46]
I would like  a large weather radar card to pop up when rain is expected within the hour. The normal pop-up is too small, and when it is set to large: true, the card displays large, but halfway down the screen. Can the pop up be made to clamp to the top of the display?
![20200102_203214](https://user-images.githubusercontent.com/56581105/71702754-27dbfd00-2d9f-11ea-8081-451c7e12000d.jpg)

**Comment by thomasloven** [comment]
Yes, with 

```yaml
style:
  left: 0
  top: 0
```
or something like that. You'll have to experiment a bit.

**Comment by georgbachmann** [comment]
May I also ask a question about the `large: true` option. I'd love my popup to be somewhere in-between large and small. Is there a way to define a custom width of the popup?

**Comment by thomasloven** [comment]
`style:`

Google "CSS"
