### ISSUE TITLE
Create entity that contains username of the last login?

### ISSUE THREAD

**Issue by jatgm1** [thomasloven/hass-browser_mod#466]
Is there a way to create an entity with the name of the last user that has logged into the home assistant as a state, and the name of the browser instance, the ip address, and other identifiably information as attributes?

**Comment by thomasloven** [comment]
You could probably do something with a triggered template sensor https://www.home-assistant.io/integrations/template/#trigger-based-template-binary-sensors-buttons-numbers-selects-and-sensors.
