### ISSUE TITLE
Add "browser_id:" to the service definition so the it can be filled in script Visual Editor

### ISSUE THREAD

**Issue by dziadeck47** [thomasloven/hass-browser_mod#467]
Currently adding e.g. "browser_id: "{{browser_id}}" results in whole script falling back to yaml 
(without it, it can be filled beatifully in the UI)

**Comment by thomasloven** [comment]
You mean target?
![bild](https://user-images.githubusercontent.com/1299821/210014514-87fb5006-6652-4f3e-a44c-222dd649d0c8.png)
