### ISSUE TITLE
Feature request: Current Device IDs sensor

### ISSUE THREAD

**Issue by xMrVizzy** [thomasloven/hass-browser_mod#47]
It would be useful in backend automation development if you add sensor, which will show current device ids as List!

**Comment by xMrVizzy** [comment]
Like a: sensor.online_browsers
and list in attributes or state: ['89dag-24...', 'alexey_iphone']

**Comment by thomasloven** [comment]
You could do that with a template sensor.

Something like:
```
{{
  states.light
  | selectattr("attributes.type", "==", "browser_mod")
  | selectattr("state", "!=", "unavailable")
  | list
  | map(attribute="attributes.deviceID")
  | list
}}
```

**Comment by xMrVizzy** [comment]
Thank you!
