### ISSUE TITLE
More info service does not work in node red 

### ISSUE THREAD

**Issue by shifuoogway** [thomasloven/hass-browser_mod#472]
The browser mod more info service works from developer tools - services - call service, but does not work in node red. The service is called with the same parameters but nothing happens.

**Comment by matthewharrington** [comment]
Same here. I thought I was going mad....

**Comment by WeterPeter** [comment]
me too, cant get it to work.

**Comment by matthewharrington** [comment]
I have built a script to get around the issue. Works fine calling the script

**Comment by WeterPeter** [comment]
> I have built a script to get around the issue. Works fine calling the script

Can you share the script?
