### ISSUE TITLE
Playback on AppleWebkit doesn't work

### ISSUE THREAD

**Issue by 1337Misom** [thomasloven/hass-browser_mod#478]
My Home Assistant version: 2022.10.5

**What I am doing:**
Trying to use this addon in combination with the Home Assistant App on iPadOS 16. But nothing plays. With Firefox on Linux it works without any problem.
I'am on IPadOS 16

**What I expected to happen:**
Hear the music playing.

**What happened instead:**
Nothing Played.

**Minimal** steps to reproduce:
Play Music through this addon.

```yaml
# The least amount of code or steps possible to reproduce my error
Nothing configured
# Put your code/steps here
```

**Error messages from the browser console:**
```
// Select everything from the browser console and copy it
Haven't got one
// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.(javascript_version is no longer supported)

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by 1337Misom** [comment]
I now have tried it also on MacOS and Safari same problem here. I now also have a Error:
´´´
[Error] Unhandled Promise Rejection: NotSupportedError: The operation is not supported.
	(anonyme Funktion)
	rejectPromise
	play
	(anonyme Funktion) (browser_mod.js:66:32520)
	dispatchEvent
	fireEvent (browser_mod.js:66:25519)
	incoming_message (browser_mod.js:66:25636)
	(anonyme Funktion) (core.8b15dd5b.js:1:7310)
	forEach
	(anonyme Funktion) (core.8b15dd5b.js:1:7233)
```

**Comment by FrnchFrgg** [comment]
I think this is a duplicate of #439.

**Comment by 1337Misom** [comment]
I will still leave this open since i only saw this error with Apple Webkit based browsers. On Firefox (Gecko) and Chrome/Chromium (Blink) it worked as expected.
