### ISSUE TITLE
lost device sensor

### ISSUE THREAD

**Issue by ppurice** [thomasloven/hass-browser_mod#479]
Home Assistant 2022.10.5
Supervisor 2022.10.0
Operating System 9.3
Frontend 20221010.0 - latest

Hello Thomas,
i use this module from 2 years , i have succesfully update at new versione , i can register the device, but when the touchscreen go in standby Home assistant lost the sensors.
If the device exit from standby (screensaver of full kiosk) after 5 seconds the sensors came back live.

thanks for your reply and support on this
Paolo

**Comment by thomasloven** [comment]
Duplicate of #452
