### ISSUE TITLE
Page misformatted after page error and page reload

### ISSUE THREAD

**Issue by ercsey** [thomasloven/hass-browser_mod#48]
I don't now if it's an error, a bug and I don't know even if it's the browser-mod's fault or not so sorry if it's false alarm.

I'm using Hass.io on an Intel NUC with Ubuntu on docker.
HA version 0.103.6
Browser Mod version 15 via HACS
The problem occurs on different browsers: Chrome, Firefox, Fully Kiosk Browser.

Description:
Basically on a page error (I have a camera stream and when the camera disconnects the page gets an error, but not only on camera error.) in developer tools I see this log:

> connection-mixin.ts:82 Uncaught (in promise) {type: "result", success: false, error: {…}}
> callService @ connection-mixin.ts:82
> async function (async)
> callService @ connection-mixin.ts:57
> e.callService @ browser_mod.js:56
> Et @ button-card.js:801
> _handleTap @ button-card.js:1720
> handleEvent @ button-card.js:243
> N.__boundHandleEvent @ button-card.js:232
> n @ button-card.js:824

As a result the Custom Header not reloads correctly the header and the whole page is miss formatted. Already submitted this error to Custom Header with the response that probably it's not a Custom Header related error. (see attached file. Sorry for the cut out... sensitive information.)
![Screenshot 2020-01-08 20 07 02](https://user-images.githubusercontent.com/11696531/72048502-98b27600-32c5-11ea-991b-fd53b72ef6c7.png)

**Comment by thomasloven** [comment]
> I don't know even if it's the browser-mod's fault

That would be an excellent thing to find out before opening a bug report, for example by removing browser_mod and seeing if the problem persists.
