### ISSUE TITLE
Adding "/browser-mod" to the end of URL not working

### ISSUE THREAD

**Issue by dmatik** [thomasloven/hass-browser_mod#483]
My Home Assistant version: 2022.10.5

**What I am doing:**
I have registered a browser on my wall panel tablet and configured to hide sidebar for that browser in Browser_mod Configuration Panel settings. So far so good, work perfectly.
I am replacing the URL by appending "/browser-mod" to the end of it, to temporary disable hiding sidebar. Doing with Fully Koisk Browser rest API.

**What I expected to happen:**
The sidebar should appear.

**What happened instead:**
The page is still loaded without a sidebar.

**Minimal** steps to reproduce:

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- X Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- X Have made sure I am using the latest version of the plugin.

- X Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- X Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
That's expected. You'll have to turn off the hiding in the settings on the `browser-mod` page.
