### ISSUE TITLE
Cannot disable browser mod entities.

### ISSUE THREAD

**Issue by jazzyisj** [thomasloven/hass-browser_mod#484]
My Home Assistant version: 2022.11.0b7

**What I am doing:**

Attempting to disable various browser mod entities.

**What I expected to happen:**

Entities become disabled.

**What happened instead:**

Not able to disable entities.  Entity settings radio buttons are greyed out.

![image](https://user-images.githubusercontent.com/44064559/199599432-1be258be-fc78-47b6-b5fb-740b22dc2da8.png)

**Minimal** steps to reproduce:

Attempt to disable any browser mod entity.

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by diginfo** [comment]
Me also, I have 2 home assistant systems, I cannot remove the integration and then remove it from HACS.

Browser javascript console errors trying to load the browser mod, have cleared cache makes no difference.

I am getting very frustrated, cannot even restart HA !

```
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:696
Integration: Home Assistant Supervisor ([documentation](https://www.home-assistant.io/integrations/hassio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
First occurred: 20:34:06 (1 occurrences)
Last logged: 20:34:06

The system cannot restart because the configuration is not valid: Integration error: browser_mod - Integration 'browser_mod' not found.

Logger: homeassistant.setup
Source: setup.py:168
First occurred: 17:16:43 (1 occurrences)
Last logged: 17:16:43

Setup failed for browser_mod: Integration not found.
```
Can someone please tell me how to completely remove this from my system ?
