### ISSUE TITLE
close_popup from automations?

### ISSUE THREAD

**Issue by pickonedev** [thomasloven/hass-browser_mod#486]
Hi!

There is any way to close a popup from within the automations or scripts?

**Comment by majdzik84** [comment]
Hello.
You can trigger the service with automation or script.
![image](https://user-images.githubusercontent.com/31352476/201132074-9b5b3972-4949-4853-9ad7-c50d0da9906d.png)

**Comment by pickonedev** [comment]
Hi!

Yes, you can do that, I tried already, but it doesn't do anything... 
I tried with device_id and with browser_id, nothing works.

Have you tested and it is working for you? If yes, can you please share an example?

Thank you in advance!

**Comment by pickonedev** [comment]
> I played around with this for some time. The scenario I have is when someone is detected on our drive I trigger a `browser_mod.popup` on all registered devices. This includes a card with a camera feed.
> 
> Calling the `browser_mod.close_popup` from the dismiss action would not cause the popup to close on all devices. After much trial and error, I was able to get this to work by calling a script from the dismiss action. The script included the close service call. Then when the camera popup is closed on one device it is closed everywhere.
> 
> I've installed [Android Panels](https://twitter.com/jamescallaghan/status/1611746777782423553) on the wall in multiple rooms so it was important to me that closing the popup on one would close it everywhere.
> 
> Script
> 
> ```yaml
> clear_browser_mod_popups:
>   alias: Clear Browser Mod Popups
>   sequence:
> 
>     - service: browser_mod.close_popup
> ```
> 
> Action
> 
> ```yaml
>   - service: browser_mod.popup
>     data:
>       title: Doorbell
>       content:
>         type: picture-entity
>         camera_view: live
>         camera_image: camera.doorbell
>         entity: camera.doorbell
>         show_state: false
>         show_name: false
>       dismiss_action:
>         action: call-service
>         service: script.clear_browser_mod_popups
>       timeout: 180000
> ```
> 
> Note: I have noticed that my browser (Win11/Edge) locks up and crashes when I do close the popup. I need to troubleshoot what is causing this as it is the only thing holding me off leveraging this. I came here to research if anyone else was seeing was seeing a similar issue.

What do you mean about "Android Panels"? It's just a device where you can put a browser or companion app of home assistant, or it is about the software as well?
I use android tablets, on the wall, in my rooms, I will show you a pic in the and of this comment. 

About the closing popups, I don't know what to say... In the past, with the older browsre_mod version, I could close the popup from automations, from which tablet I wanted. Now... with this new version, only from lovelace I can do this. I will try again from scripts, maybe with the updates of browser_mod, it will work.

My tablets on the wall, are like this, with an animated background
![image](https://user-images.githubusercontent.com/34201387/212024500-dd049b34-c6c5-40e3-b77c-5dd20824362e.png)
