### ISSUE TITLE
Use Deviceid and user to show/hide cards in Lovelace?

### ISSUE THREAD

**Issue by wendan20** [thomasloven/hass-browser_mod#49]
Hi, I'm experimenting with Browser_mod. Made some nice things in Lovelace. Thanks for that!

I was wondering if it possible to use items from the browser_mod to show or hide cards in Lovelace. For example show card X on ipadY. Or hide card X with user Z.

I have been puzzeling with the condition card, but I didnt figure it out.

Hope you can help. Grtz, Daniel

**Comment by thomasloven** [comment]
[state-switch](https://github.com/thomasloven/lovelace-state-switch) can be used to display different cards in different *devices*.
