### ISSUE TITLE
Expand the data object for browser_mod.javascript

### ISSUE THREAD

**Issue by Sian-Lee-SA** [thomasloven/hass-browser_mod#491]
Would it be possible to add a couple of elements to the data object. I find that the calling card from a tap action etc would be benificial to access easily as to allow the Javascript code to be easily accessable to the card that called it. 

For example right now I have a popup for a picture-glance card which holds a video stream. I've added a custom entity button to execute the javascript code to either toggle mute or go fullscreen. As of now I have to hunt for the element but would prefer to be able to access the element via data.card or even data.popup (for the popup).

To get the element I'm after, I have to do code like below... Yet alot of that can be so much more shorter and stable with just referencing the card the service was called from. Any changes the the Home Assistant layout would also require modifying the code each time also.
```js
  let video = window.document.querySelector('browser-mod-popup').shadowRoot;
  if( data.multi_view ) {
      video = video.querySelector('hui-grid-card').shadowRoot;
      video.querySelectorAll('hui-picture-glance-card').forEach(ele => {
          if( ele._config.camera_image == data.entity )
          {
            video = ele.shadowRoot;
          }
      });
  } else {
      video = video.querySelector('hui-picture-glance-card').shadowRoot;
  }
  video = video.querySelector('hui-image')
              .shadowRoot.querySelector('ha-camera-stream')
              .shadowRoot.querySelector('ha-web-rtc-player')
              .shadowRoot.querySelector('video');
  if (video.requestFullscreen) {
    video.requestFullscreen();
  } else if (video.mozRequestFullScreen) {
    video.mozRequestFullScreen();
  } else if (video.webkitRequestFullscreen) {
    video.webkitRequestFullscreen();
  } else if (video.msRequestFullscreen) { 
    video.msRequestFullscreen();
  }

```

I also have a popup which shows multiple picture-entities so I have to loop to find the right one that the button that called the service is attached to.

**Comment by thomasloven** [comment]
`fire-dom-event` doesn't present a source, so this is not possible.
