### ISSUE TITLE
Entities unavailable, services but still connected. 

### ISSUE THREAD

**Issue by webbson** [thomasloven/hass-browser_mod#492]
My Home Assistant version: 2022.11.3

I have 25 displays running on Raspberry PI 3s for information in my office. 

Suddenly 12 of them have lost all their entities to unavailable state.  It doesn't matter if I reload the screens they wont appear again.

They are however updated in the Registered Browsers tab and services can be called on them. But their entities are unavailable.

**Comment by thomasloven** [comment]
Duplicate of #452
Duplicate of #479
