### ISSUE TITLE
Media Player Not Working

### ISSUE THREAD

**Issue by Iceman248** [thomasloven/hass-browser_mod#493]
My Home Assistant version: 11.3

What I am doing: Trying to play audio, TTS, videos through the Media Player entity.

What I expected to happen: To see and hear relevant audio/video playback.

What happened instead: Nothing, although the entity acts as if it is playing, but I see and hear nothing.

I can use the Browser media player to play things built into HA and that works. I can show live video feeds through pop-up feature, but I couldn't hear any audio that I would expect to.

Error messages from the browser console: Below

```
Logger: aiohttp.server
Source: /usr/lib/python3.10/site-packages/aiohttp/web_protocol.py:405
First occurred: 11:06:33 AM (6 occurrences)
Last logged: 11:06:43 AM

Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"

```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X ] Have made sure I am using the latest version of the plugin.

- [X ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
Are you saing that video playback works but there's no audio?
That's using the same web browser media element, so I'd say the problem is with your device - like it being muted.

**Comment by Iceman248** [comment]
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/16282747/210081411-9c8a8273-93f4-4bed-b663-207bf4072964.png">
I hadn't been trying to play video, but if I do, it doesn't do anything if I am trying to use Browser Mod media player. Nothing is muted. I can hear audio using the regular browser option. Still getting the same error, also saw this one. Happens on both Windows and Linux computers. I don't recall exactly what I saw before that made it look like anything was playing, maybe progress bar going cross, but that might have been on Linux machine. Either way, it doesn't ever play anything and that slash icon goes back and forth between being there and not in the picture, also when trying to play, get the blue scrolling wheel in the middle where power icon would be for the media player.

```
https://hassdomain/lovelace/default_view?homescreen=1:0:0 Uncaught
https://hassdomain/developer-tools/yaml:0:0 Uncaught
https://hassdomain/media-browser/media_player.browser_mod_device/app%2Cmedia-source%3A%2F%2Fmedia_source:0:0 Uncaught
https://hassdomain/browser-mod:0:0 Uncaught
https://hassdomain/config/dashboard:0:0 Uncaught
```

**Comment by thomasloven** [comment]
Did you setup your URL correctly in `/config/network` and does sending media to other media players work?

**Comment by Iceman248** [comment]
In HA, pretty sure it is correct. I've never had a problem playing to any other media players I've had, nor many of the other things that I use that rely on all of this type of communication being correct.

**Comment by curtisdr** [comment]
I've also had problems. Was working a couple of weeks ago. No idea what changed.  Tried clearing cache & storage from the two Fire HD 10 tablets.  Also tried creating new Browser Mod device names.  Still nothing.  notify.alexa_media works to these devices.  Pop-up and Navigate continue to work properly.  What's this "config/network" you speak of? BTW, amazing add-on.
```
service: media_player.play_media
data:
  media_content_id: /local/alarm.mp3
  media_content_type: music
target:
  device_id: ecf21e94e582e981e1450381e46050ed
enabled: false
```

**Comment by curtisdr** [comment]
I've also had problems. Was working a couple of weeks ago. No idea what changed.  Tried clearing cache & storage from the two Fire HD 10 tablets.  Also tried creating new Browser Mod device names.  Still nothing.  notify.alexa_media works to these devices.  Pop-up and Navigate continue to work properly.  What's this "config/network" you speak of? BTW, amazing add-on.
```
service: media_player.play_media
data:
  media_content_id: /local/alarm.mp3
  media_content_type: music
target:
  device_id: ecf21e94e582e981e1450381e46050ed
enabled: false
```

**Comment by Iceman248** [comment]
I even tried on a third computer, same thing. It doesn't even look like I can turn the media player on. In the Device page, it says off and hitting the power icon never turns it on.

**Comment by virtusas** [comment]
I have same issue with my fire tablet 8. Media plays locally on tablet fine. But nothing happens via Browser Mod. Mod is freshly installed. And I cant get my head around where issue is. Works fine as Alexa notifier etc....
