### ISSUE TITLE
Sensor FullyKiosk ist not on

### ISSUE THREAD

**Issue by Danit2** [thomasloven/hass-browser_mod#494]
My Home Assistant version: 2022.11.1

**What I am doing:**
I have set up a Wallpanel with FullyKiosk 1.49.1 and Browser Mod.
The sensor in Browser Mod for the FullyKiosk is off all the time.
![image](https://user-images.githubusercontent.com/71522810/203328482-e9180789-ff0e-4292-9754-3d661b0aa526.png)

**What I expected to happen:**
The Sensor for FullyKiosk must go on

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by Danit2** [comment]
https://smarthomescene.com/guides/how-to-setup-browser-mod-2-0-in-home-assistant/

**Comment by pessorrusso** [comment]
This is also happening to me and I can't play tts to my tablet (using FullyKiosk) if I don't touch the screen first (not sure if this is a consequence of the hidden kiosk flag not being enabled). This (not being able to play tts if I don't touch the screen) was not happening with browser_mod 1.x. (no change or update to the OS or the Fully kiosk was made as the tablet has no internet connection)

**Comment by thomasloven** [comment]
Have you activated the [Javascript Interface](https://www.fully-kiosk.com/en/#websiteintegration)?

**Comment by Danit2** [comment]
Ahh thanks. That was it. 

But is this somewhere writen that this must be activatet?

**Comment by thomasloven** [comment]
I just added it to the readme. It was there in the old version, but somehome got missed in this one.
