### ISSUE TITLE
Cant get new version of browser mod to work with templates

### ISSUE THREAD

**Issue by miannelli516** [thomasloven/hass-browser_mod#495]
Hello ive been trying for days to figure out why i cant get the new version of browser mod to work. the old version worked no problem. i was using it in the old version with templates. i made changes as the documentation states so that it would work with V2 however, nothing im trying seems to work. any assistance anyone can provide is extreamly appricated!
[cod.txt](https://github.com/thomasloven/hass-browser_mod/files/10124483/cod.txt)

**Comment by thomasloven** [comment]
There are no templates in that example
![bild](https://user-images.githubusercontent.com/1299821/210013618-7489b0c1-6573-4702-a69a-a7da74ac3a07.png)
