### ISSUE TITLE
Browser Mod page is Blank, with no Register button

### ISSUE THREAD

**Issue by GreyGnome** [thomasloven/hass-browser_mod#497]
My Home Assistant version: 2022.11.2

**What I am doing:**
I am trying to follow the Quickstart in the README.md, and it says,
Go to the Browser Mod panel in your sidebar
Make sure the "Register" toggle is checked.

But when I click on Browser Mod in the panel on the left, the pane on the right is completely empty.

**What I expected to happen:**
I should see something in there, like a Register button.

**What happened instead:**
The page was empty.

**Minimal** steps to reproduce:
Follow the Quickstart until step 4.

...Oh, but if I reload the page AFTER I click the Browser Mod panel, the GUI shows up!

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by mfabiani53** [comment]
Same here, i am unable to use browser_mod options having a blank screen. And more cannot register the app as new device for HA.

**Comment by thomasloven** [comment]
Please provide a browser console log.

**Comment by vk2jnc** [comment]
[mfabiani53](https://github.com/mfabiani53) this also worked for me too. click it then refreshed.

Browser log shows - Failed to load resource: net::ERR_FILE_NOT_FOUND   Roboto-Regular.ttf:1

**Comment by evgparen** [comment]
Same here.
Sidebar page is empty. 
When I load browser_mod URL manually, I get 404: Not found

Reloading doesnt help here!

**Comment by wessi86** [comment]
> Same here. Sidebar page is empty. When I load browser_mod URL manually, I get 404: Not found
> 
> Reloading doesnt help here!

Same for me.

**Comment by lafite64** [comment]
> > Same here. Sidebar page is empty. When I load browser_mod URL manually, I get 404: Not found
> > Reloading doesnt help here!
> 
> Same for me.

Same for me. Testing a popup in browser mod just generates an empty thin box at the top of the screen. Simply doesn't work according to the instructions

**Comment by patrickc999** [comment]
I'm having the same issue. No amount of cache clearing or refreshing across multiple devices has an effect. Companion app is the same.

**Comment by gberl001** [comment]
I just went to put up a PR for this and found the repo currently has an open PR from 2 days ago that someone already put up for the fix. I'm not sure what the merge process is so I have no idea when they'll accept this PR but if you're familiar enough with github and editing HA local files you can download the files changed in this PR and overwrite what is in your custom_components/browser_mod/ directory.

https://github.com/thomasloven/hass-browser_mod/pull/779

You'll have to restart HA and clear browser cache to apply the fix.

**Comment by tshan1229** [comment]
Its not working for me either

**Comment by Goochp72** [comment]
It's not working for me either

**Comment by dcapslock** [comment]
> It's not working for me either

Best to submit an issue filling in all relevant details. Commenting on a closed issue with no details is not going to get any review of what your issue may be.
