### ISSUE TITLE
Camera picture stays black 

### ISSUE THREAD

**Issue by PulsarFX** [thomasloven/hass-browser_mod#499]
My Home Assistant version: 2022.11.2

**What I am doing:**
Register browser mod in the mobile Android App with camera support.
Done so with two different samsung tablets and also via Fully Kiosk Browser.
Result is always the same. 

**What I expected to happen:**
The front/back/any camera picture is available in HA.

**What happened instead:**
Only a black frame or no frame at all is shown.
Sometimes however a video stream is shown. But I was not able to find out under which circumstances.

**Minimal** steps to reproduce:
Register Android Mobile App with Browser_mod
 
**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by cadwizzard** [comment]
I'm also seeing this on the 2.1.3 version on a windows tablet using chrome. Everything else works for control (changing pages and screen off etc. The tablet (surface pro 3) has a front camera and when i enable the camera feature in BrowserMod the entity appears. I also click the orange finger popup to allow it on the tablet, but it will not display on the glance cards. It just has a broken icon
![camera entity](https://user-images.githubusercontent.com/7688705/211532494-7ea5e0e1-6eb3-4829-9a55-0b2d01a08f02.png)

**Comment by barrelltitor** [comment]
Also seeing this with different samsung and lenovo tablets. Same issue, either black or like the image cadwizzard posted

**Comment by tbrasser** [comment]
I had cameras working with fully kiosk browser & browser_mod, but since a week or more they suddenly all stopped working. Just posting here in case it's fully broken recently or something.

**Comment by cadwizzard** [comment]
This is definitely still an issue

**Comment by barrelltitor** [comment]
This is still an issue, please do not close it mister bot

**Comment by cadwizzard** [comment]
I agree,
I still see the broken image with status 'idle' too

**Comment by barrelltitor** [comment]
This is still an issue mister bot

**Comment by barrelltitor** [comment]
This is unfortunately not completed, still happens

**Comment by PhilippeP62** [comment]
Let's add me to the list of not working cameras

**Comment by bthornton191** [comment]
I'm experiencing this as well. Is it possible camera only works with https?

**Comment by barrelltitor** [comment]
Would be nice to get this reopened
