### ISSUE TITLE
not working via Internet

### ISSUE THREAD

**Issue by thundergreen** [thomasloven/hass-browser_mod#5]
hello I tried you awesome mod but nfortunately it won't play any sound if device is called via internet. local network works 1a . My hass instance is available and reachable via domain:8123. Is there anything I can do to debug? there's no error in the logs :/

**Comment by thomasloven** [comment]
This is most likely a problem with your base_url setting: https://www.home-assistant.io/components/http/#base_url

TTS messages will be served from your base_url. If that's not `domain:8123` it will not be reachable from outside your network.
