### ISSUE TITLE
Fully kiosk is not recognised

### ISSUE THREAD

**Issue by vandalon** [thomasloven/hass-browser_mod#50]
I'm using fully kiosk on a huawei mediapad t5 and fully kiosk is not recognised:

type: browser_mod last_seen: 2020-01-17T12:45:53.601838 
deviceID: a016c808-d5f31950
path: /lovelace/beneden 
visibility: visible 
userAgent: Mozilla/5.0 (Linux; Android 8.0.0; AGS2-W09 Build/HUAWEIAGS2-W09; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/79.0.3945.116 Safari/537.36
currentUser: home 
width: 1054 height: 659

On my previous tablet fully was recognised. Is there anything I can check?

**Comment by lancelon** [comment]
You've remembered to turn on advanced javascript?

**Comment by vandalon** [comment]
Damn, that was it.... sorry about that.

**Comment by lancelon** [comment]
I'm elated I was able to help someone. At last.
