### ISSUE TITLE
Target current browser_id from a server call

### ISSUE THREAD

**Issue by prbtt** [thomasloven/hass-browser_mod#511]
Before browser mod 2.0 I was able to call a browser mod popup service from a script that would only target the current browser.

According to the guide:
```

- A server call will perform the service on ALL REGISTERED BROWSERS.

- A browser call will perform the service on THE CURRENT BROWSER, i.e. the browser it was called from.

```
I am unable to do do that. It does indeed target every registered browser. This is very inconvenient since I'm mainly usinig browser mod for the mobile companion app. I wan't everyone that logs into my home assistant from their phones to have an individual experience. For example, I do not want someone to trigger my popup script that turns on the tv and shows the remote control while someone else is using the app to control the lights or whatever.

Is there any way that I can make it work like this with BM 2 or do I have to go back to the old version?

**Comment by xZetsubou** [comment]
Use fire-dom-event this the best method at least for me to use popup service .
It will only popup for the person who called the service.
``show_name: true
show_icon: true
type: button
entity: switch.aplug
show_state: false
icon: mdi:button-cursor
name: Button
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Title
      content:
        type: markdown
        content: Hello world
        style: |
          ha-card  {
            background-color: transparent;
            border: none;
          }
      right_button: Yes!
      style: |
        --margin-left: -68px !important;
        --mdc-theme-surface: #000000;
        --popup-min-width: 600px;
        --popup-max-width: 900px;
        --popup-border-width: var(--ha-card-border-width, 1px);
        --popup-border-color: rgba(23,23,23,1);
        --popup-border-radius: 0px ;
        --popup-background-color: rgba(25,56,77,0.4);
        --popup-padding-x: 0px;
        --popup-padding-y: 0px; 
```

**Comment by prbtt** [comment]
> Use fire-dom-event this the best method at least for me to use popup service . It will only popup for the person who called the service.
> 
> ```
> show_icon: true
> type: button
> entity: switch.aplug
> show_state: false
> icon: mdi:button-cursor
> name: Button
> tap_action:
>   action: fire-dom-event
>   browser_mod:
>     service: browser_mod.popup
>     data:
>       title: Title
>       content:
>         type: markdown
>         content: Hello world
>         style: |
>           ha-card  {
>             background-color: transparent;
>             border: none;
>           }
>       right_button: Yes!
>       style: |
>         --margin-left: -68px !important;
>         --mdc-theme-surface: #000000;
>         --popup-min-width: 600px;
>         --popup-max-width: 900px;
>         --popup-border-width: var(--ha-card-border-width, 1px);
>         --popup-border-color: rgba(23,23,23,1);
>         --popup-border-radius: 0px ;
>         --popup-background-color: rgba(25,56,77,0.4);
>         --popup-padding-x: 0px;
>         --popup-padding-y: 0px; 
> ```

Afaik, fire Dom event does not work from backend. I already use it from the front end and it works. But my issue here is executing a script from the frontend that calls a pop up from the backend. This triggers to all registered browsers instead of only the current one.

**Comment by thomasloven** [comment]
How?

A server call is originated from your home assistant server machine. It doesn't know where you are.
What if the call is made by an automation triggered by you opening your front door? Which browser should that popup be displayed on?

**Comment by prbtt** [comment]
> How?
> 
> A server call is originated from your home assistant server machine. It doesn't know where you are. What if the call is made by an automation triggered by you opening your front door? Which browser should that popup be displayed on?

I was using browser mod just as a pop up that was displaying a card and then executing a service call in sequence. Since you cannot chain service calls from the front end, I had to do this using a script. Previously it was working on the older version of BM and then it stopped working after that. I didn't have to target a specific browser, it was a script that executed when anyone pressed the button. I've since moved on from trying to make this work, it's no longer important for me, particularly.

**Comment by thomasloven** [comment]
>Since you cannot chain service calls from the front end,

https://github.com/thomasloven/hass-browser_mod/blob/master/documentation/services.md#browser_modsequence


The way it worked previously was an incredibly dirty hack, and I was told by @balloob himself to "Just don't do that". Publicly. It's in one of the first few monthly release parties on youtube...
