### ISSUE TITLE
Hide inactive Icon in App

### ISSUE THREAD

**Issue by direx1** [thomasloven/hass-browser_mod#513]
My Home Assistant version: 2023.1

Trying to use the hide active icon in the companion app using BM  2.2.0

Works fine on chrome browser for registered devices by ID or by username but doesn't hide in registered app by either method using Android 2022.12.0-full

**Comment by pickonedev** [comment]
Same here, I use Huawei tablets with Fully Kiosk Browser, I still see the Icon...
