### ISSUE TITLE
How do we automate a browser if the ID keeps changing?

### ISSUE THREAD

**Issue by arretx** [thomasloven/hass-browser_mod#522]
I see that you've written that there's no way around the ID of the browser changing, which begs the question, what's the purpose of the entire project if we can't build automations around static ID's for each permanently mounted device?  

Not sure I get it.

**Comment by thomasloven** [comment]
Perhaps you missed the other part of that line of text:

>  I've used every trick in the book and invented a handful of new ones in order to save the Browser ID as far as possible. It should be much better in Browser Mod 2.0 than earlier

Most of the time it works. But sometimes it doesn't.
