### ISSUE TITLE
Stops working after HA restart.

### ISSUE THREAD

**Issue by Rudd-O** [thomasloven/hass-browser_mod#527]
My Home Assistant version: 2023.1.1

Also latest HA Companion app.

**What I am doing:**

Restarting HA.

**What I expected to happen:**

browser_mod on my iPad Companion app to continue to work.

**What happened instead:**

All browser_mod entities from the app appear unavailable.

**Minimal** steps to reproduce:

Restart HA.

Go to Devices & Services -> Entities.

Filter by browser_mod.

Note all entities don't work anymore.

**Error messages from the browser console:**

I haven't seen any error messages.  This is an iPad running in the Companion app.  No way to get to a browser console.

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

-----------

I also have made a report here asking people about a workaround for this issue: https://community.home-assistant.io/t/need-to-refresh-my-ipad-companion-app-reconnect-it-to-browser-mod-when-ha-restarts/525051

Ideally, instead of refreshing anything, browser_mod just tries to reconnect to whatever API endpoint was being used to provide its services.  Since I can see my dashboard changing in realtime after a restart, at least the WebSocket endpoint seems to be reconnecting fine.

**Comment by dylanpedro** [comment]
I've also noticed a similar issue on my browser and looking for a workaroud

**Comment by pedolsky** [comment]
+1

**Comment by apadua** [comment]
This is clearly an issue. Navigating to /browser-mod on an "unavailable" device shows the connection as off. Clicking ON reeenables the connection from that specific device.

**Comment by pedolsky** [comment]
Not solved.

**Comment by Rudd-O** [comment]
Not solved.

**Comment by Rudd-O** [comment]
Will test after release.

**Comment by thomasloven** [comment]
Also duplicate of #405
