### ISSUE TITLE
FR: Tap background to close popup on mobile

### ISSUE THREAD

**Issue by conorlap** [thomasloven/hass-browser_mod#528]
Tap background to close popup on mobile. Currently this doesn't work on mobile.
It works fine on desktop with a mouse click.

https://user-images.githubusercontent.com/57415184/214822000-c7106558-cbff-4e85-9c6e-d5a667cbf2ec.mp4

**Comment by thomasloven** [comment]
This behavior is the same as the default more-info dialog.
