### ISSUE TITLE
How do you remove devices that are no longer in use

### ISSUE THREAD

**Issue by dylanpedro** [thomasloven/hass-browser_mod#533]
I've removed any browsers that are no longer in user via the Browser Mod tab but these devices are still visible in the setting > integrations section and I cannot see how to remove them as there is no delete option?

**Comment by skandalfo** [comment]
What worked for me was registering a browser under the leftover name and then unregistering it again.

**Comment by mvanlijden** [comment]
Still an issue for me. I have been able to remove all entities, as they are correctly seen as inactive.
However the devices cannot be removed. Is there a trick or workaround?

**Comment by Phoenix-DH** [comment]
I have the same ask:
I deleted all devices via the menu which I do not need anymore. Now I got 9 left.
But when having a look to the integration I still have 27.

Is there a current "automated" solution?

**Comment by Noob25930** [comment]
> What worked for me was registering a browser under the leftover name and then unregistering it again.

THANK YOU

**Comment by thomasloven** [comment]
Are you saying the trash can button in the Browser Mod panel is not working?

**Comment by Phoenix-DH** [comment]
Yes it seems to be the case.
In the panel I deleted all old ones and habe only 7:
![IMG_5965](https://github.com/thomasloven/hass-browser_mod/assets/44058592/78fb532d-91b4-45c0-96bb-2f17bfc589e8)

in the integration 28:
![IMG_5966](https://github.com/thomasloven/hass-browser_mod/assets/44058592/aede7abd-f3f0-4b34-81e3-0792dc6f579d)

I deleted them as mentioned in the integration.

**Comment by Phoenix-DH** [comment]
@thomasloven 
Is there a chance to reoown this issue?
I still have the issue.

I want to aboid to remove and reintegrate it again because then I have to adapt a lot of things.

Thanks

**Comment by xbmcnut** [comment]
This is how you do it.
Grab the name of the 'stuck' device and using the browser mod settings in any browser, paste in the name of the retired device and register it using the toggle.
![image](https://github.com/user-attachments/assets/1ff5c2d4-374e-4288-a062-f3764f1e10c6)

Once registered, slide the toggle to off, to unregister.
![image](https://github.com/user-attachments/assets/f7bfeea4-c5c6-44ea-901d-a80cd92616b8)
That device will now be gone from Devices and services > Brwoser mod.

**Comment by Phoenix-DH** [comment]
Will test and give feedback, thanks.

**Comment by markfrancisonly** [comment]
Didn't work for me, unregister browser using the trash icon leaves undeletable devices behind. Aggravating manual json device and entity registry editing ensues...

wishing home assistant had a device nuke function, do not like being forced to be unable to delete a device/entity provided by an integration

**Comment by xbmcnut** [comment]
> Didn't work for me, unregister browser using the trash icon leaves undeletable devices behind. Aggravating manual json device and entity registry editing ensues...
> 
> wishing home assistant had a device nuke function, do not like being forced to be unable to delete a device/entity provided by an integration

Did you re-register the dead device first?

**Comment by gio-dot** [comment]
> > Didn't work for me, unregister browser using the trash icon leaves undeletable devices behind. Aggravating manual json device and entity registry editing ensues...
> > wishing home assistant had a device nuke function, do not like being forced to be unable to delete a device/entity provided by an integration
> 
> Did you re-register the dead device first?

Didn't work for me too. I followed your suggested steps

**Comment by GregoryWest501** [comment]
Yes this is a big issue.   I have something like 100 browser mod entries (working with AI and speakers on my tablet devices).   To delete one entity takes 5 clicks.   That is over 500 clicks to clear the list. 

Even being able to delete a block of entries by 'Area' would work.

Greg

**Comment by dcapslock** [comment]
> Even being able to delete a block of entries by 'Area' would work.

This is indeed available :-) Use [`browser_mod.deregister_browser` ](https://github.com/thomasloven/hass-browser_mod/blob/master/documentation/services.md#browser_modderegister_browser)introduced in 2.3.8 (2.3.5). Either use an exclude area to keep what you wish (recommended) or include area to include browsers to deregister. While you are at it, you may wish to make sure you are following [best practices](https://github.com/thomasloven/hass-browser_mod/blob/master/documentation/configuration-panel.md#browser-id-updates) which was added to the documentation recently.

**Comment by GregoryWest501** [comment]
This is said Entirely in jest...  "You have to stop hiding features under simple menus like you do.   Hide things where no one would ever look, you know like MicroSoft does."

Seriously though, found what you were talking about and deleted 100 entries in about 5 minutes.   Turned off auto-register.   Life is good!    Thanks for an awesome add-on.

Greg
