### ISSUE TITLE
New version of Browser_mod unreliable

### ISSUE THREAD

**Issue by 26tajeen** [thomasloven/hass-browser_mod#535]
My Home Assistant version: 2022.11.5

**What I am doing:** Trying to use the new version of Browser_mod

**What I expected to happen:** That it would work reliably like the previous version

**What happened instead:** It wasn't reliable - screen no longer responding to commands to turn on reliably. Sometimes does, sometimes doesn't. The issue is possibly that telemetry back to Home Assistant isn't reliable - I think HA thought the tablet was still on (the 'light' sensor for whether the tablet is turned on or not) was showing as 'on' even though it wasn't. Never an issue with the older version. https://community.home-assistant.io/t/browser-mod-turn-your-browser-into-a-controllable-device-and-a-media-player/123806/1988

Anyway I've downgraded to v2 and it's not working perfectly again.

**Minimal** steps to reproduce: Have a browser_mod instance running on a Fully Kiosk tablet

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:** N/A

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [ ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by pedolsky** [comment]
The issue persists.
