### ISSUE TITLE
Media player not working on Windows tablet

### ISSUE THREAD

**Issue by leprechaun17** [thomasloven/hass-browser_mod#538]
My Home Assistant version: 2023.2.5

**What I am doing:**
I registered 2 different Windows tablet using Edge as the browser on Browser Mod and my iPhone through HA App.

**What I expected to happen:**
When I manually play a sound file through the browser mod media player function, the sound works on the iPhone.

**What happened instead:**
No sound from both of the Windows tablet. No error code provided.

**Comment by PsyonicOne** [comment]
I also have this issue on Android devices using the HA app. If I choose "Browser" in the bottom right corner in the Media tab I get sound on the device I'm on, if I select any other device from there, including my XBox no sound can be heard although the devices say they are playing and that the device "changed to Playing triggered by service media_player.play_media"

**Comment by dmiales** [comment]
@PsyonicOne @leprechaun17 did you solve the problem somehow? Maybe he used some other method?

**Comment by PsyonicOne** [comment]
@leprechaun17 Afraid not, I can't even get media player to work at all at the moment

**Comment by mfabiani53** [comment]
> @leprechaun17 Afraid not, I can't even get media player to work at all at the moment

Same here, all browser media players are in unavailable state....
Did you discovered something?

**Comment by PsyonicOne** [comment]
> > @leprechaun17 Afraid not, I can't even get media player to work at all at the moment
> 
> Same here, all browser media players are in unavailable state.... Did you discovered something?

Not yet... hoping for a contributor to help us out

**Comment by Mygrille** [comment]
Hello everyone I need help I can't get it to play a sound the player is addressed and shows that it is playing but no sound output Brauser Mod 2.3 tested on different tab's and windows devices
