### ISSUE TITLE
Battery Sensor not available

### ISSUE THREAD

**Issue by skycryer** [thomasloven/hass-browser_mod#544]
I added a ticket about the battery info missing some time ago where it was fixed, I thought. But I can not see any battery info. How can I see the info? I have no extra sensor or extra data on any item. I am using latest version 2.2.0.

**Comment by rarroyo6** [comment]
Issue is still happening as of ver. 2.3.0.
I have 3 tablets running browser-mod 2.3.0, with fully-kiosk (free version).
One of the tablets does reports the battery level, and battery charging status, on Android 6. The other 2 tablets running Android 9, do not report battery level, or charging status. Don't know if the Android version has anything to do with it, but it's the only difference I can see between them.
