### ISSUE TITLE
camera sensor not present

### ISSUE THREAD

**Issue by ggocsei** [thomasloven/hass-browser_mod#55]
Hi,

 I'm using Hass.io with browser_mod on a Huawei tablet with Fully (PLUS) with enabled camera access, javascript frontend, and almost everything what i can. In the configuration.yaml:

browser_mod:
    prefix: "browser_"
    devices:
        mydeviceid:
            name: my terminal device 
            camera: true

On the brwoser terminal there is no error, and I can reach every other sensor, binary sensor from this device. Even motion detection! 
I have several other generic cameras and those are configured and present in system. Only the camera.my_terminal_device is not showing. 
Of course I rebboted the Hass.io, the terminal device after evrey settings change.

 In the Fully, (or even in Chrome) the HomeAssistant website is not asking permission for the webcam and/or the microphone. I use it on http. 

 What am I missing? 

Thanks,
 Gabor

**Comment by thomasloven** [comment]
The camera function is meant as a last-resort workaround for people who can't use FKB and it's built-in camera which is better in every way.
