### ISSUE TITLE
Browser Mod became unknown/unavailable after reboot HA or refresh screen

### ISSUE THREAD

**Issue by SBerg1980** [thomasloven/hass-browser_mod#551]
Android 11
Fully Kiosk (latest version)
Home Assistant 2023.3.4
Supervisor 2023.03.1
Operating System 9.5
Frontend 20230309.0 - latest

When i reboot or refresh my tablet screen Browser mode became unknown/unavailable, i have to touch my screen one time and then its activated, if i refresh my tablet screen again it became unknown/unavailable if i then touch my screen again it's activated.

If i reboot my home assistant machine browser mode became unknown/unavailable and if i touch my screen its activated.

Please help

**Comment by thomasmaxson** [comment]
Same problem. This is SUPER annoying.

**Comment by Loic691** [comment]
Javascript Interface (PLUS) is already enabled for me.
I get the issue of browser_mod entity became unvailable...
