### ISSUE TITLE
Blackout on Windows Chrome

### ISSUE THREAD

**Issue by k1ng440** [thomasloven/hass-browser_mod#552]
My Home Assistant version: 2023.3.4

**What I am doing:**
Nothing.

**What I expected to happen:**
Blackout should not be turned on automatically on desktop browser.

**What happened instead:**
blackout div is denying access to home assistant UI

**Minimal** steps to reproduce:
I do not know. 

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by pedolsky** [comment]
Same on IOS.
