### ISSUE TITLE
Registered Browsers can NOT be selected as targets

### ISSUE THREAD

**Issue by haempy** [thomasloven/hass-browser_mod#554]
My Home Assistant version: 2023.3.5

**What I am doing:**
Calling any Browsermodservice and would select a target

**What I expected to happen:**
My Registered Browsers are selectable

**What happened instead:**
No Browser selectable

**Minimal** steps to reproduce:

<img width="914" alt="msedge_qoBNRZ8vDm" src="https://user-images.githubusercontent.com/39195281/226173663-256e5d4f-2095-41af-aedf-ef9c95cc98b4.png">

<img width="473" alt="msedge_gngWH4Yequ" src="https://user-images.githubusercontent.com/39195281/226173721-89472130-3fbc-45c1-a1fb-c8b0970a8950.png">

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by DanielGroot** [comment]
Same here

**Comment by DanielGroot** [comment]
There is a little work around tho. 

1. Make a media player service.
2. Select the browser mod media player for the target.
3. Go into YAML mode.
4. Copy the `device_id`
5. Make the desired browser mod script and add these lines:
`target:`
`device_id: <id that you just copied>`

**Comment by claytonium13** [comment]
> 

Same thing happens to me. I'm assuming it happened after one of the last few core updates.

**Comment by criticallimit** [comment]
use:

browser_id:

instead of:

deviceID:


that´s working for me

**Comment by danielyc** [comment]
> use:
> 
> browser_id: ff519x05-bdfb65a5
> 
> instead of:
> 
> deviceID: ...
> 
> that´s working for me (copy your browser ID instead of mine. ;-) )

Had the same issue and this works, thx!

**Comment by loryanstrant** [comment]
I'm finding this problem exists with trying to use the navigate service.
Would the workaround suit this requirement?

**Comment by DanielGroot** [comment]
@loryanstrant I just tried it, yes it works

**Comment by ronluna** [comment]
> I have the same issue as well. @DanielGroot, thanks for sharing the workaround... Are you able to target a single device_id with your method? For some reason, even when I put just one, when I call the service, it shows a popup on all registered browsers. Even those not included in the target > device_id.

I can confirm this behavior. it does not allow to call popup service from within a script and to pop just in the browser that triggered the script (by using browser_id: "{{ browser_id }}"

**Comment by saschaludwig** [comment]
Same problem here, can't select any of my browser devices

**Comment by jazzyisj** [comment]
> browser_id: ff519x05-bdfb65a5

This is the old deviceID.   Unfortunately state-switch doesn't work with the "hass" deviceID, but it still does with the browser mod deviceID?  You can get from the console on a computer, but I can't figure out how to get this for a browser on mobile (android)?

**Comment by Kampfkissen** [comment]
Good evening, 

i'm really a newbie... where i can find the browser_id? I want a pop-up on my ipad...
