### ISSUE TITLE
browser mod: popup dismiss when Mouse is moved

### ISSUE THREAD

**Issue by criticallimit** [thomasloven/hass-browser_mod#557]
Today I discovered that Browser mod: popup is dismissing when Mouse is moved.
No matter if it is on time autoclose or not. Popup is not staying to close it at the "cross" in the popup, it autocloses on mouse movement. 

I´m on Mac with Safari.

      - service: browser_mod.popup
        data:
          dismissable: true
          autoclose: true
          title: Eva
          content: OFFLINE
          timeout: 30000
          browser_id: ff519d05-bdfb65a5

Anybody can confirm?

**Comment by howi42** [comment]
Yes, that is correct.
According to the readme, this is what is expected.
But it makes autoclose unusable on a mouse-driven interface, it is only usable on touchscreens.

**Comment by thomasloven** [comment]
The *only* point of autoclose is to close the popup if the mouse is moved. If you don't want that, don't use it.
