### ISSUE TITLE
more-info does not work after browser mod pop up

### ISSUE THREAD

**Issue by deluxestyle** [thomasloven/hass-browser_mod#56]
When I open a popup card with browser mod I cannot open a standard more-info dialog anymore.
I have to refresh before it works again

Hass.io Version: 0.104.3
Browser Mod: 22

See attached gif
![Home Assistant 2020-02-02 16-38-04](https://user-images.githubusercontent.com/662779/73610753-1e7ec400-45db-11ea-92b5-2c002d41dbb6.gif)

**Comment by stmrocket** [comment]
I just updated my system (to the same versions) and I am experiencing the exact same issue.

**Comment by plw4** [comment]
Me too, just installed browser_mod yesterday and have observed this in the iOS app and Firefox on Windows.

**Comment by ASNNetworks** [comment]
I can confirm this happens to me as well since the latest browser mod and card tools update.

**Comment by jsnyde30** [comment]
I just recently started using this feature too and I get the same results on Android and chrome for Mac/windows.  I haven't had my wife test it on her iPhone because that's instant -10waf points😁

**Comment by afxefx** [comment]
I think it has to do with the change pushed to be compatible with 105, which will be out soon.  In the interim, rolling back to 16 resolves it for me with 104.3.

**Comment by Photo64** [comment]
Rolled back to 16 on 104.3 and it appears to be resolved. I was seeing this behavior using Firefox, Chrome and Brave.

**Comment by thomasloven** [comment]
Sorry about that. I thought the change was backwards compatible.

# Version 22 requires Home Assistant 0.105.
# Use version 16 for Home Assistant 0.104 and earlier

**Comment by deluxestyle** [comment]
With ha 0.105.1 it’s working again
