### ISSUE TITLE
HA 2023.4: sidebar changes no longer work

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/hass-browser_mod#561]
My Home Assistant version: 2023.4.0b0
browser-mod: 2.2.0

**What I am doing:**
<img width="612" alt="Scherm­afbeelding 2023-03-30 om 16 28 33" src="https://user-images.githubusercontent.com/33354141/228869247-c0cf9109-e263-4922-89db-fa62ceef0777.png">

**What I expected to happen:**
![Scherm­afbeelding 2023-03-07 om 13 38 11](https://user-images.githubusercontent.com/33354141/228869312-4b9aa4c2-2f24-4263-9512-dc3de1953c5d.png)

in HA 2023.3.x

**What happened instead:**

in HA 2023.4.0b0

<img width="255" alt="Scherm­afbeelding 2023-03-30 om 16 26 39" src="https://user-images.githubusercontent.com/33354141/228869374-de2427b1-8df0-4855-b2dd-df604116d4ae.png">

**Minimal** steps to reproduce:

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here

No code change, all in UI
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X ] Have made sure I am using the latest version of the plugin.

- [X ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by holdestmade** [comment]
Same here, sidebar hide doesn't work either

**Comment by maverik80** [comment]
Also for me same problem no longer hide sidebar and header

**Comment by anthonyrdg42** [comment]
Pareil pour moi, ne fonctionne plus ... 
Je suis donc en repassé en 2023.3.6.

**Comment by Mariusthvdb** [comment]
dear Thomas,

this is to thank you for updating and releasing a new version!

Installed BM 2.2.1 and HA 2023.4.1

also, and here's the catch: changing the header title still does not work. Ive cleared it first, restarted and etc etc. then added a new title.

It remains the default Home Assistant unfortunately.

Hope you can fix it,
thanks

**Comment by skylarv** [comment]
@thomasloven I've updated to latest, browser still isn't hiding side bar on my Echo Show android tablet. It's hiding properly in Chrome/Firefox though. I applied it to a particular user, and also tried applying to the tablet's browser, no change. Any suggestions? Thanks!

**Comment by fsedarkalex** [comment]
I can confirm this

**Comment by mirkin-pixel** [comment]
Same issue as @Mariusthvdb

**Comment by thomasloven** [comment]
Ah yes. I forgot to test that... will issue a fix shortly (i.e. between a couple of hours and a few days, have some things to do)

**Comment by bencollinz** [comment]
just adding onto the 'header no longer hides' for me, as well

**Comment by thomasloven** [comment]
Thanks for reminding me.
Try now.

**Comment by mirkin-pixel** [comment]
@thomasloven title changes works again, the sidebar order unfortunately not yet

**Comment by Mariusthvdb** [comment]
there is progress in Browser-mod 2.2.2:

the menu title change nows sticks again, it seems very robust.
<img width="342" alt="Scherm­afbeelding 2023-05-25 om 07 39 04" src="https://github.com/thomasloven/hass-browser_mod/assets/33354141/d29f8977-c1c0-4d0c-aa0a-c0f3afad9c5f">

however, some regression also seems to have occurred, and made the side bare card_mod_theme changes even harder to show. As you can see, none of the icon changes, or the counter to the right of the menu items appear upon reloading the page.

As a matter of fact, I can not get them to show on Safari at all any longer, even after refreshing cache repeatedly (which was the thing we had to do after HA 2023.4 arrived)

only Chrome shows the mods after some effort:

<img width="367" alt="Scherm­afbeelding 2023-05-25 om 07 40 28" src="https://github.com/thomasloven/hass-browser_mod/assets/33354141/eddff397-1864-4826-97a6-5a9ce2531b68">

I would have believed this to be a card-mod 'issue', but, since the behavior changed with this Browser-mod update, it seems a valid point to make here too.

Anyways, thanks for developing, and hoping this could be fixed sometime too...

**Comment by Lux315** [comment]
The recent update fixed the sidebar title for me. I hope for everybody else too, thanks a lot @thomasloven
