### ISSUE TITLE
Browser mod is not displayed in siedebar 

### ISSUE THREAD

**Issue by Nico08dl** [thomasloven/hass-browser_mod#563]
This readme.md is completly bullshit for begginers 
Theres no Browser mod in the Service tab to toggle it on an also no Browser mod in the sidebar

**Comment by esw148** [comment]
Make sure you did this part:   Add the "Browser Mod" integration in Settings -> Devices & Services -> Add Integration  ->  Browser Mod

**Comment by lunarose23** [comment]
I ran into the same thing - I brought it in via HACS, then went to add the integration and it wasn't there.
