### ISSUE TITLE
HA 2023.4 Hide header not working

### ISSUE THREAD

**Issue by limitless00net** [thomasloven/hass-browser_mod#566]
My Home Assistant version: 2023.4

**What I am doing:**
I updated to HA 2023.4

**What I expected to happen:**
Header should be hidden.

**What happened instead:**
Header are not hidden.

**Minimal** steps to reproduce:
I just updated.

**Error messages from the browser console:**
Nothing

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by mdb17** [comment]
I am seeing this as well

**Comment by jcbshw** [comment]
Also seeing the same with hiding the sidebar

**Comment by mkcologne** [comment]
Put me on the list. For Sidebar as well.

**Comment by w1tw0lf** [comment]
Sidebar and header not hiding this side

**Comment by radoprajitno** [comment]
I found the same issue. It also affect the HACS kioskmode hide header functions.

**Comment by guirem** [comment]
Same here

**Comment by pergolafabio** [comment]
ah, ok, yeah, i was using kiosk mode, but it was broken, wanted to try out this one instead, but it doesnt work indeed, now i know its not me
The beta kiosk mode is working tough, the one from the gist , for people want to use it:
https://gist.github.com/elchininet/9a2648ea0016d3194072712c745c5ad2

**Comment by TheBassfly** [comment]
Samen for me.

Tha whole Lovelace seemed top be changed, as all my themes don't have any background anymore.

**Comment by laczynskik** [comment]
with ['wallpanel lovelace'](https://github.com/j-a-n/lovelace-wallpanel) work well, hiding by CSS..

**Comment by MackoMici** [comment]
same here!
sidebar and header

**Comment by filippo196302** [comment]
same here!
sidebar and header

**Comment by pklijzing** [comment]
Instead of all saying "Same", just thumbs up the first post to keep this thread clean. 
Pretty please 😁

**Comment by olibos** [comment]
Hello, if this issue is blocking, you can try my workaround:
https://github.com/olibos/hass-browser_mod/blob/feature/2023.4-workaround/custom_components/browser_mod/browser_mod.js

Just replace the one in your config folder:
/config/custom_components/browser_mod/browser_mod.js

and delete the gzip version: /config/custom_components/browser_mod/browser_mod.js.gz

Then restart your HomeAssistant: Developer Tools > Check and Restart > Restart
And select "Restart Home Assistant":
![image](https://user-images.githubusercontent.com/6031263/230388914-5d1e1db9-947b-4ae0-be25-fa991fd22bfb.png)

**Attention:** this workaround works only in 2023.4+

Let me know if it works for you!

![image](https://user-images.githubusercontent.com/6031263/230389450-1df94548-5bea-4d30-9505-41ca1746331a.png)

**Comment by TheBassfly** [comment]
> Hello, if this issue is blocking, you can try my workaround: https://github.com/olibos/hass-browser_mod/blob/feature/2023.4-workaround/custom_components/browser_mod/browser_mod.js
> 
> Just replace the one in your config folder: /config/custom_components/browser_mod/browser_mod.js
> 
> and delete the gzip version: /config/custom_components/browser_mod/browser_mod.js.gz
> 
> Then restart your HomeAssistant: Developer Tools > Check and Restart > Restart And select "Restart Home Assistant": ![image](https://user-images.githubusercontent.com/6031263/230388914-5d1e1db9-947b-4ae0-be25-fa991fd22bfb.png)
> 
> **Attention:** this workaround works only in 2023.4+
> 
> Let me know if it works for you!
> 
> ![image](https://user-images.githubusercontent.com/6031263/230389450-1df94548-5bea-4d30-9505-41ca1746331a.png)

Nope

Doesn't work here.

**Comment by wattsy74** [comment]
> Hello, if this issue is blocking, you can try my workaround: https://github.com/olibos/hass-browser_mod/blob/feature/2023.4-workaround/custom_components/browser_mod/browser_mod.js
> 
> Just replace the one in your config folder: /config/custom_components/browser_mod/browser_mod.js
> 
> and delete the gzip version: /config/custom_components/browser_mod/browser_mod.js.gz
> 
> Then restart your HomeAssistant: Developer Tools > Check and Restart > Restart And select "Restart Home Assistant": ![image](https://user-images.githubusercontent.com/6031263/230388914-5d1e1db9-947b-4ae0-be25-fa991fd22bfb.png)
> 
> **Attention:** this workaround works only in 2023.4+
> 
> Let me know if it works for you!
> 
> ![image](https://user-images.githubusercontent.com/6031263/230389450-1df94548-5bea-4d30-9505-41ca1746331a.png)

Didn't work for me either

**Comment by olibos** [comment]
No worries, I hope we will soon have an official release with the fix 😉

**Comment by Tanjohnson99** [comment]
Same issue here. Sidebar is not hide.

**Comment by aldor443** [comment]
> Hello, if this issue is blocking, you can try my workaround: https://github.com/olibos/hass-browser_mod/blob/feature/2023.4-workaround/custom_components/browser_mod/browser_mod.js
> 
> Just replace the one in your config folder: /config/custom_components/browser_mod/browser_mod.js
> 
> and delete the gzip version: /config/custom_components/browser_mod/browser_mod.js.gz
> 
> Then restart your HomeAssistant: Developer Tools > Check and Restart > Restart And select "Restart Home Assistant": ![image](https://user-images.githubusercontent.com/6031263/230388914-5d1e1db9-947b-4ae0-be25-fa991fd22bfb.png)
> 
> **Attention:** this workaround works only in 2023.4+
> 
> Let me know if it works for you!
> 
> ![image](https://user-images.githubusercontent.com/6031263/230389450-1df94548-5bea-4d30-9505-41ca1746331a.png)

This solution only works in browser, not in apk ???

**Comment by grssll** [comment]
Not working!

**Comment by jcbshw** [comment]
> Hello, if this issue is blocking, you can try my workaround: https://github.com/olibos/hass-browser_mod/blob/feature/2023.4-workaround/custom_components/browser_mod/browser_mod.js
> 
> Just replace the one in your config folder: /config/custom_components/browser_mod/browser_mod.js
> 
> and delete the gzip version: /config/custom_components/browser_mod/browser_mod.js.gz
> 
> Then restart your HomeAssistant: Developer Tools > Check and Restart > Restart And select "Restart Home Assistant": ![image](https://user-images.githubusercontent.com/6031263/230388914-5d1e1db9-947b-4ae0-be25-fa991fd22bfb.png)
> 
> **Attention:** this workaround works only in 2023.4+
> 
> Let me know if it works for you!
> 
> ![image](https://user-images.githubusercontent.com/6031263/230389450-1df94548-5bea-4d30-9505-41ca1746331a.png)

Thanks I can confirm this works for me on iOS and Desktop after clearing cache.

**Comment by terriblefox** [comment]
seems kiosk mode integration fixed it.

**Comment by vhardono** [comment]
@olibos I followed your workaround and refreshed my browser. The header background is now gone, however a small portion (bottom half) of the header title is visible/protruding from the top of screen. Is there any other configuration I need to adjust for removing the header title completely?

![Untitled](https://user-images.githubusercontent.com/47447466/230569352-7f502f25-71e2-485c-9511-67ab10c1c34c.png)

**Comment by olibos** [comment]
Hello @vhardono , 
Thank you for your feedback.

I think it's a limitation of my workaround.
My personal use case hide both the sidebar and header.
If no official solution come on tuesday, I will have some time to check that use case and update my PR + link of the workaround.

**Comment by vhardono** [comment]
thanks for your effort anyway! :)
I just deleted the header title - "Dashboard" so it's not visible anymore, but for sidebar it's not possible. So i will temporarily hide the sidebar first until official fix is released

**Comment by dselzle** [comment]
This still seems to be broken for me after your fix. HA 2023.4.1

**Comment by drjjr2** [comment]
> This still seems to be broken for me after your fix. HA 2023.4.1

Not sure if this applies to you but I thought it wasn't working with FullyKiosk but then I cleared the cache (in FullyKiosk) and all was well.

**Comment by Zeunas** [comment]
Def clear cache, that should work.

**Comment by dselzle** [comment]
> > This still seems to be broken for me after your fix. HA 2023.4.1
> 
> Not sure if this applies to you but I thought it wasn't working with FullyKiosk but then I cleared the cache (in FullyKiosk) and all was well.

Clearing the Fully Kiosk cache worked thanks! Though restarting the app would be enough, but I guess not.

**Comment by juan11perez** [comment]
The fix is not working correctly. 
The title bar is indeed hidden, but I can not access the side panel.
I've cleared cache and restarted the app various times.

**Comment by thomasloven** [comment]
Do you mean the button to reveal the sidebar - which is in the header - is not vissible when you've chosen to hide the header?

**Comment by limitless00net** [comment]
> The fix is not working correctly.
> The title bar is indeed hidden, but I can not access the side panel.
> I've cleared cache and restarted the app various times.

Same here.

**Comment by juan11perez** [comment]
@thomasloven 
Thank you.
In my case that side panel button has always been hidden if I choose the hide title option.

However, I was always able to see the side panel by swiping right on the screen. The side panel will momentarily appear and then hide again.

Right now that's not possible. I.e. the side panel is fully locked and can't be accessed. The only way is to disable the 'hide title' option

**Comment by pergolafabio** [comment]
This is not related to Browser mod, they changed something in frontend:

https://github.com/home-assistant/android/issues/3460
