### ISSUE TITLE
Sidebar order EDIT button KO

### ISSUE THREAD

**Issue by Sanch0ous** [thomasloven/hass-browser_mod#570]
My Home Assistant version: 2023.4.2

**What I am doing:**
Trying to reorder sidebar items with BrowserMod.
In Frontend Settings -> Sidebar order -> Click on EDIT button

**What I expected to happen:**
Items in sidebar can be reordered or deleted

**What happened instead:**
Nothing

**Error messages from the browser console:**

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'editMode')
    at he.toggleEditSidebar (browser_mod_panel.js:252:1545)
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by bobslaede** [comment]
:+1:   
I think all the different sidebar editing HACS have stopped working, after the latest update.

**Comment by oneseventhree** [comment]
> 👍 I think all the different sidebar editing HACS have stopped working, after the latest update.

hopefully we get an update soon!

**Comment by oneseventhree** [comment]
Did the new version fix this for anyone? Mine still not working

**Comment by pkscout** [comment]
It doesn't look like the fix for this issue has been merged, so the newest version still has this issue.  Either the proposed fix is only a partial fix and the author is working on something else, or they haven't had time to merge it.

**Comment by SiriosDev** [comment]
any workaround
