### ISSUE TITLE
Entity state language change to English 

### ISSUE THREAD

**Issue by sasukebinbin** [thomasloven/hass-browser_mod#575]
Just installed browser mod 2. It works well. 
But just realized all states changed back to English. 
However system config language is correct. 
Not sure if everyone is same?

**Comment by ratunee-me** [comment]
The same is here. All state has English states instead of chosen language of HA user.

**Comment by thomasloven** [comment]
Which entity states? The entities made by Browser Mod or entities displayed in e.g. a Browser Mod popup?
All of them? Just a few? Only the ones displaying the userAgent string?
