### ISSUE TITLE
Browser Mod and HA 2023.5

### ISSUE THREAD

**Issue by jouster1974** [thomasloven/hass-browser_mod#578]
Iknow there was a fix put in place for the sidebar/header hiding issues that came with 2023.4

but as I was away for the release I reverted back to 2023.3 which still worked fine

I saw a new BM was released to 2.2.1 saying that it fixed issues with the above on 2.23.4 an onwards

However, today, when finally getting around to updating (and only to 2023.5), and with Browser Mod updated to 2.21., I can confirm that the sidebar/header issue is still present. and cannot be hidden on the two prior devices it worked fine on 2.2.0 and 2023.3

In fact, If I try to make any changes to Browser MOd from its sidebar entry... none of them actually save...so whether change the sidebar setting for an individual device  or delete it totally...the change doesnt stick...can't even delete a registered browser in case I wanted to go nuclear

Also, the ability to drag in from the left of the screen to get to the sidebar....rather than clicking the menu icon, still doesn't work either

If there is anything you'd like me to try, that would be great, but for now Ill be winding back again

**Comment by formatBCE** [comment]
+1, top bar became visible in 2023.5
In my theme there's nothing there (i use minimalist-mobile), but empty space eats screen height.

BTW, thank you for your continuous work on this @thomasloven
