### ISSUE TITLE
Tablet Media Player becomes "Unavailable" after 12 hours

### ISSUE THREAD

**Issue by tictactommy** [thomasloven/hass-browser_mod#583]
Home Assistant 2023.3.6

**What I am doing:**

Firstly loving the mod, appreciate the work that has gone into it.

I have been using a tablet as an announcement speaker for home assistant.  A Samsung tablet, using fully kiosk browser, works great until its been connected for 12 hours and then it becomes unavailable.

**What I expected to happen:**
The media player entity that is created for that browser/device to remain connected whilst HAOS is up and running.

**What happened instead:**
after 12 hours of staying connected and not being used the device becomes unavailable.

**Minimal steps to reproduce:**
Install browser_mod
Setup using the tablet and kiosk browser

Any insight in to the issue would be most appreciated as I'll continue to find a solution / workaround my end

**Comment by Emilef22** [comment]
i have the same problem here, thanks!

**Comment by Cha40s** [comment]
Same Problem with a Lenovo Clock. My workaround is to restart the clock in the morning with a smart switch.
