### ISSUE TITLE
HA Core 2023.6 and Python 3.11 Compatibility

### ISSUE THREAD

**Issue by GitHubGoody** [thomasloven/hass-browser_mod#590]
Is this integration compatible with HA Core 2023.6 since it now uses Python 3.11?

https://www.home-assistant.io/blog/2023/06/07/release-20236/#breaking-changes

**Comment by ThatTallGuy21** [comment]
I updated to 2023.6 last weekend and since then I've had one annoying issue where the header names of the pop-ups are now left aligned and no longer in bold. Otherwise it seems to work fine.
