### ISSUE TITLE
Request: persistent popup (not user dismissable)

### ISSUE THREAD

**Issue by snickers2k** [thomasloven/hass-browser_mod#591]
Would be great to have the ability to have a persistent popup, not user dismissable at all (instead of "only after action"). 
in my use case for an alarm-card popup - only auto-close through HA after disarmed.

**Comment by thomasloven** [comment]
Try reading the documentation again: https://github.com/thomasloven/hass-browser_mod/blob/master/documentation/services.md#browser_modpopup

> `dismissable`: If false the dialog cannot be closed by the user without clicking an action button.
