### ISSUE TITLE
Issues with media player on NS panel pro

### ISSUE THREAD

**Issue by hastime** [thomasloven/hass-browser_mod#594]
My Home Assistant version: 2023.06.2

**What I am doing:**
I am running browser mod on several devices already and it is working brilliantly. I have just set it up on an ns panel pro running fully kiosk and I am struggling to get the media player working.

**What I expected to happen:**
I thought that it would just work like the other android tablets I have setup with fully kiosk but it seems to be very unreliable, I have managed to get audio a couple of times, I have checked and the device isn't muted, I can use the same browser on the device to play audio from other websites and the screen on off control on browser mod and the navigation is working correctly.

**What happened instead:**
When I first turn on the panel the media player is shown as unavailable in HA when I send audio to the panel it shows the media player going into a 'paused' state, never plays and then stays like that until I manually turn off the media player. I have also set the never disconnect setting in the user preferences, restarted home assistant, deleted and readded the browser with a different id/name and I am still getting the issue.

**Minimal** steps to reproduce:
I am unable to reproduce on any other device although I don't have another nspanel pro to test with. I guess someone could test with the same device.

**Error messages from the browser console:**
I am receiving no error messages, only; 

changed to Paused triggered by service media_player.play_media

When I send audio to the media player

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [ x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x ] Have made sure I am using the latest version of the plugin.

- [ x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by hastime** [comment]
Hi,

As an update I have managed to get it to behave as the others, and 100% reliably by changing the android system WebView from bromite WebView 108.x.x to android system WebView 71.x.x - hopefully this can help someone else if they get stuck with the same issue! Thanks for making such awesome integrations! BrowserMod is so powerful! Thanks.

**Comment by drschnalli** [comment]
My audio player came unavailable after i installed bromite WebView 108.xxx and 137.0.7151.89-715108901 with AnyWebView Module..... i switched back to the original Web View Delivered with Firmware Version 3.10 but i cannot get it working again... it was working with the stock WebView... which is now active again ... but it does not work anymore... i cleared all caches and data from webview... companion app and browsers... since i had changed the WebView things... its not working in browsers (like fully kiosk... WebView Tester) and Companion App Anymore... only things working is detecting motion and disable screen. Maybe i have to enter rescue mode and start from beginning :S

**Comment by dcapslock** [comment]
FYI - new beta available that has fixes to `media_player` and interaction requirements. See [v2.4.1-beta.3](https://github.com/thomasloven/hass-browser_mod/releases/tag/v2.4.1-beta.3)

@drschnalli it is very difficult to know what may be going on with the different versions of webview. Generally, it has to do with whether the Browser allows video and audio to play without further user interaction. The latest beta release of Browser Mod has more information availbale as attributes of the Browser media player entity so you are not guessing what Browser Mod knows about what it can play.

**Comment by drschnalli** [comment]
2.4.1-beta3 works insanely good! Thank you very much.. you saved me so much time... searching the problem at the "end device".
