### ISSUE TITLE
Unable to download *search

### ISSUE THREAD

**Issue by NAAAAAAAAA1212** [thomasloven/hass-browser_mod#596]
My Home Assistant version: latest

**What I am doing:**
Trying to search repo from HACS

**What I expected to happen:**
Found this repo on HACS

**What happened instead:**
It is not on there

**Minimal** steps to reproduce:
Search it

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it

// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [Y] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [Y] Have made sure I am using the latest version of the plugin.

- [Y] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [Y] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
It's there. The readme tells you to search under "Integrations", and also provides a handy link which works.
