### ISSUE TITLE
Incompatable with hass-action / mushroom cards v3

### ISSUE THREAD

**Issue by lichenophile** [thomasloven/hass-browser_mod#598]
My Home Assistant version: 2023.07.1

**What I am doing:**
Attempting to use a mushroom card `action` from within a browser mod popup

**What I expected to happen:**
Response to `action`

**What happened instead:**
Nothing

**Minimal** steps to reproduce:
1 Create a browsermod popup with a mushroom card within it
2 Attempt to perform an action of the mushroom card

The cause:
Mushroom v3.0.0 uses the new `hass-action` which seems to be causing an incompatibility with browser_mod 
https://github.com/piitaya/lovelace-mushroom/issues/1193

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by baerenmarke90** [comment]
+1 I've got the same issue with browser mod and mushroom cards

**Comment by andrey170183** [comment]
+1 I've got the same issue with browser mod and mushroom cards

**Comment by ErikT80** [comment]
+1 I've got the same issue with browser mod and mushroom cards

**Comment by blackvrs** [comment]
> +1 I've got the same issue with browser mod and mushroom cards

**Comment by themaartenz** [comment]
+1, same here. Controlling a device within a Mushroom card in general works, unless it's configured within a popup (browser mod), then it's unresponsive.

**Comment by limitless00net** [comment]
same here..

**Comment by daanwa** [comment]
Yup. Facing the same problem. Can confirm Mushroom works in general just not within a popup browser.

**Comment by ivandelhoyo** [comment]
+1 urgent!! :(

**Comment by igiannakas** [comment]
+1 same here.

**Comment by Schlichi83** [comment]
Same issue. Hope there‘s a fix soon.

**Comment by oxymoron1629** [comment]
+1 So happy I found this thread. I was losing my mind.

**Comment by douglasfl** [comment]
+1 Same issue

**Comment by maygoo23** [comment]
+1 Same issue here as well!

**Comment by realNF** [comment]
+1 popups with mushroom not working

**Comment by little-better** [comment]
+1 not only mushroom buttons. I think other buttons also doesn't work with browser_mod popup.

**Comment by WW1983** [comment]
still not working for me after the update.

**Comment by daanwa** [comment]
Did you copy over the files manually or are you checking if a new update is available in HACS? I don't think there is a new release yet and as such, no update available in HACS.

I copied over the files manually into my HA installation according to the installation instructions in the README. It seems to be working for me now.

**Comment by WW1983** [comment]
> Did you copy over the files manually or are you checking if a new update is available in HACS? I don't think there is a new release yet and as such, no update available in HACS.
> 
> I copied over the files manually into my HA installation according to the installation instructions in the README. It seems to be working for me now.

Fist i download it over HACS again. But i didnt work for me.
![grafik](https://github.com/thomasloven/hass-browser_mod/assets/56581564/6e29a1d7-0de0-4960-81d2-64646888d285)

After that I deleted browser_mod completely. Also the folder config/custom_components/browser_mod. Then I reinstalled browser_mod

**Comment by WW1983** [comment]
> Did you copy over the files manually or are you checking if a new update is available in HACS? I don't think there is a new release yet and as such, no update available in HACS.
> 
> I copied over the files manually into my HA installation according to the installation instructions in the README. It seems to be working for me now.

Do you replace just the files "onfig/custom_components/browser_mod" ?

**Comment by daanwa** [comment]
So I didn't remove or reinstall the integration itself, just replaced the `custom_components/browser_mod` directory. So basically my flow goes like this.

1. Install latest version from HACS
2. Download the `custom_components/browser_mod` from the master branch of this repository.
3. Replace the `custom_components/browser_mod` directory on your HASS installation with the one downloaded from the master branch.
4. Restart HASS and clear browser cache

**Comment by Schlichi83** [comment]
The changed file seems to be in the js folder

**Comment by WW1983** [comment]
> The changed file seems to be in the js folder

Can i replace the js file manually too?

**Comment by smartqasa** [comment]
The popup.js file is incorporated into the browser_mod.js file.  What I did was manually copy the code changes and we through the steps (uninstall the integration, reinstall, clear cache). Now it works. 

I also copies the code changes from 595. That one fixes the header formatting issues.

**Comment by oxymoron1629** [comment]
Is I manually add the new code, can I update via HACS for next update in the future? Any idea when these fixes will be in the next update?

**Comment by smartqasa** [comment]
[Schlichi83](https://github.com/Schlichi83) Yes, browser_mod.js and I just examined the code and cut and pasted the adds, changes, and deletions.

**Comment by Schlichi83** [comment]
I can't seem to find these code positions. Could you maybe upload your browser_mod.js file here, so I can download & exchange it?

**Comment by themaartenz** [comment]
I'm also playing around with replacing files manually (from 'master'), redownload, reinstalling and restarting, but for me it doesn't work. Should we wait for an official update on v2.2.2? Not a github guru either...

**Comment by smartqasa** [comment]
Here you go...

https://github.com/smartqasa/hass-browser_mod/tree/master/custom_components/browser_mod

Be sure to delete the browser_mod.js.gz file.

**Comment by themaartenz** [comment]
> Here you go...
> 
> https://github.com/smartqasa/hass-browser_mod/tree/master/custom_components/browser_mod
> 
> Be sure to delete the browser_mod.js.gz file.

This is working for me! Replaced the contents of the _browser_mod.js_ file, removed _browser_mod.js.gz_, restarted HA, cleared my cache and the actions within my popups work! Thanks @smartqasa!

**Comment by igiannakas** [comment]
Found a bug with this change - the more info pop ups initiated from a mushroom button in a browser_mod pop up are showing but behind the browser mod one #603 

Does anyone else have this issue?

![Screenshot 2023-07-14 at 08 47 26](https://github.com/piitaya/lovelace-mushroom/assets/59056762/136a8c2b-79dc-4cf9-b88b-96f2b9cf899f)

![Screenshot 2023-07-14 at 08 47 46](https://github.com/piitaya/lovelace-mushroom/assets/59056762/5037fdf4-5840-49f7-a397-dfba59eec929)

**Comment by themaartenz** [comment]
> Found a bug with this change - the more info pop ups initiated from a mushroom button in a browser_mod pop up are showing but behind the browser mod one #603
> 
> Does anyone else have this issue?
> 
> ![Screenshot 2023-07-14 at 08 47 26](https://user-images.githubusercontent.com/59056762/253509567-136a8c2b-79dc-4cf9-b88b-96f2b9cf899f.jpg)
> 
> ![Screenshot 2023-07-14 at 08 47 46](https://user-images.githubusercontent.com/59056762/253509594-5037fdf4-5840-49f7-a397-dfba59eec929.jpg)

After the things I did (see above), everything is working fine (for now). Are you launching a popup from a popup? That is not something I've ever tried.

**Comment by igiannakas** [comment]
> > Found a bug with this change - the more info pop ups initiated from a mushroom button in a browser_mod pop up are showing but behind the browser mod one #603
> > Does anyone else have this issue?
> 
> After the things I did (see above), everything is working fine (for now). Are you launching a popup from a popup? That is not something I've ever tried.

Yes correct. Launching the more info pop up from the pop up. For example to see the history of a sensor.

**Comment by Schlichi83** [comment]
It's working for me as well. But I can confirm, that the pop-up (more info) is being display behind the pop up from browser_mod. Would be nice, if this could get fixed.

**Comment by piitaya** [comment]
> It's working for me as well. But I can confirm, that the pop-up (more info) is being display behind the pop up from browser_mod. Would be nice, if this could get fixed.

Pushed a fix for that : https://github.com/thomasloven/hass-browser_mod/pull/605

**Comment by AINER** [comment]
So strange...
I have browser_mod v2.3.0 and Mushroom v3.0.3, but issue is still here.

**Comment by Schlichi83** [comment]
> So strange...
> I have browser_mod v2.3.0 and Mushroom v3.0.3, but issue is still here.

Delete your browser cache. Completely!

**Comment by remocamenisch** [comment]
> Delete your browser cache. Completely!

Thank you now its working fine

**Comment by remocamenisch** [comment]
On my Computer it works fine. But in the Android App on my Phone i have still the same problem. 
Close and reopen the App do not help.
What can i do?

**Comment by Schlichi83** [comment]
> On my Computer it works fine. But in the Android App on my Phone i have still the same problem.
> Close and reopen the App do not help.
> What can i do?

There is a feature to clear the cache in the App. Just Google it. Did the same thing.

**Comment by remocamenisch** [comment]
> There is a feature to clear the cache in the App. Just Google it. Did the same thing.

Thank you, now it works. :)

**Comment by Idan37S** [comment]
It still happens to me with mushroom-chips-card inside a pop-up,
Trying to tap a chip card the more-info is being opened in the background (behind the current pop-up).

With regular mushroom cards it's working fine for me.
I'm on the latest version of everything.

Does it happen to anyone?
