### ISSUE TITLE
Specifying a device not working 

### ISSUE THREAD

**Issue by stainlessray** [thomasloven/hass-browser_mod#6]
When I specify a device to target with a command, the command still hits all available devices. I've tried several variations in the json and may still not have it right.

I have tried it using "deviceid", "deviceID", "device_id" and others. I've tried it with just the numeric portion for the device ID itself etc. 

Can anyone help with a working snippet? 

(This snippet works but hits all available devices) 
{
  "command": "navigate", 
  "navigation_path" : "/lovelace/3", 
  "device": "media_player.d23fd46-be4572f9"
}

**Comment by thomasloven** [comment]
From the documentation: "and deviceID which is a list of devices"

Lists are enclosed by square brackets in json.
