### ISSUE TITLE
"deviceID: this" keeps changing to ID of one of my PC's

### ISSUE THREAD

**Issue by ASNNetworks** [thomasloven/hass-browser_mod#60]
I’m not even sure if this issue is with browser_mod or an external issue, but it does occur using it. 

So I have multiple popupcards setup as global popupcards (using BDuit's light and media player popupcards). These are grouped lights or speakers. In those cards I have added a service call to browser_mod.popup to open an individual light or speaker as a popup. The setup itself works great. However, the deviceID's of some of them keeps changing to a different ID. I have noticed it's always cards I created last, not all of them.

I have put 'this' after every deviceID as such: 'deviceID: this'. Everything works, but then after a random amount of time (usually thing a few minutes) I notice that they don't work. Then I check my lovelace configuration and I see that the devideID has changed to a completely different one. This is happening everyday since I use the browser_mod.popup as a service. I think it changes it to my main laptop every time.

I am going crazy because I cannot figure out what is causing this. I am not changing anything, yet somehow the deviceID of the browser_mod.popup service-call keeps changing. Am I using 'deviceID: this' wrong? If I remove the line completely, the popups open on all my active devices. So I figured this made sure only the device clicking on the service call would open it.

**Comment by Skeletorjus** [comment]
I'm experiencing the exact same thing. It started happening a couple of weeks ago, and it's very frustrating because it forces popups to only work on one device.

**Comment by thomasloven** [comment]
You can now reset your deviceID manually.
