### ISSUE TITLE
Installation stuck on "Waiting for device activation"

### ISSUE THREAD

**Issue by AStoker** [thomasloven/hass-browser_mod#600]
My Home Assistant version: 2023.7.1

**What I am doing:**
Following the installation instructions up to the "Find and download Browser Mod under integrations in HACS".
When I find in the integrations the HACS module, and attempt to authorize with github, everything succeeds and it tells me to go back to the application. When I return to Home Assistant, it's still stuck in the "Waiting for device activation" modal.

**What I expected to happen:**
I'm expecting to return to the Home assistant integration page seeing the activation successful.

**What happened instead:**
It's stuck "waiting for device activation" with no way forward (only a close icon).

**Minimal** steps to reproduce:
Follow the steps described here: https://hacs.xyz/docs/configuration/basic
Note, the documentation is slightly out of date, as it doesn't show the new github login view.
This is also a brand new attempt at installing HACS

**Error messages from the browser console:**
Using the Home Assistant App

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by AStoker** [comment]
Closing issue. All I can say is that it didn't work all day, then tried the exact same steps this evening and it worked just fine. 🤷

**Comment by domoticaDude** [comment]
I have the same problem it is not fixed.

**Comment by JanWesel** [comment]
I have got the Isle as well.
New Installation of HA, Trier different Browser.
Trier at different time cleared the Cache.
Issue is still there.

**Comment by DilpreetSohanpal1** [comment]
Same issue. Fresh HA installation

**Comment by ChrWieg** [comment]
I have the same problem it is not fixed.

**Comment by voltex-at** [comment]
Same issue. The problem it is not fixed.

**Comment by howardilderton** [comment]
Same issue - tried all suggestions but does not progress after authorizing github.
