### ISSUE TITLE
Popup title styling seems to be broken sometimes (Possibly a Light/Dark mode issue)

### ISSUE THREAD

**Issue by IIStevowII** [thomasloven/hass-browser_mod#604]
My Home Assistant version: 2023.6.1 (happens for a few versions atleast)

**What I am doing:**
I am displaying a simple popup using the browser_mod.popup service. The displayed title is display incorrectly, without proper styling. (seems to be happening with every popup, both in the browser as in the mobile app)

**What I expected to happen:**
The title should be displayed correctly, like this:
![afbeelding](https://github.com/thomasloven/hass-browser_mod/assets/4059224/46cee20d-6c98-4975-81e1-1c4e607a42de)

With the given HTML markup when inspecting:
![afbeelding](https://github.com/thomasloven/hass-browser_mod/assets/4059224/52252888-e046-4418-b8fd-e77864026e2b)

**What happened instead:**
The title appears without styling, below the closing icon:
![afbeelding](https://github.com/thomasloven/hass-browser_mod/assets/4059224/72da53db-5929-4319-948d-629088432bea)

The HTML markup seems to be different as well (missing a lot):
![afbeelding](https://github.com/thomasloven/hass-browser_mod/assets/4059224/fd652a74-9735-4953-b1ad-ecead6409a04)

**Minimal** steps to reproduce:
I am not really sure. At first I thought this was an issue with Dark mode, so I switched to Light mode and it worked correctly. I then switched to a different browser (in private mode) also to Light mode to create the above screenshots. Except it now also didn't work properly in Light mode. Switching back and forth between Light/Dark mode and refreshing the page resulted in it working once, but haven't been able to reproduce is consistenly since. Ofcourse the difference in HTML markup is also interesting.

```yaml
service: browser_mod.popup
data:
  title: Just a test
  content: Good for you
```

**Error messages from the browser console:**

```
BROWSER_MOD 2.2.2 IS INSTALLED
    BrowserID: c830ef66-33b4d7cc [browser_mod.js:407:6188](https://[redacted].duckdns.org:1337/browser_mod.js)
HUI-ELEMENT 1.1.2 IS INSTALLED <empty string> [hui-element.js:1:1813](https://[redacted].duckdns.org:1337/hacsfiles/lovelace-hui-element/hui-element.js?hacstag=249942054180547)
SLIDER-ENTITY-ROW 17.3.0 IS INSTALLED <empty string> [slider-entity-row.js:82:184](https://[redacted].duckdns.org:1337/hacsfiles/lovelace-slider-entity-row/slider-entity-row.js?hacstag=1448997001730)
 MULTIPLE-ENTITY-ROW  4.5.0 [multiple-entity-row.js:1:26787](https://[redacted].duckdns.org:1337/hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js?hacstag=178921037441)
Automatisch afspelen is alleen toegestaan wanneer goedgekeurd door de gebruiker, de website is geactiveerd door de gebruiker, of media wordt gedempt. [browser_mod.js:66:14748](https://[redacted].duckdns.org:1337/browser_mod.js)
AUTO-ENTITIES 1.12.1 IS INSTALLED [auto-entities.js:172:7850](https://[redacted].duckdns.org:1337/hacsfiles/lovelace-auto-entities/auto-entities.js?hacstag=1677445841121)
FOLD-ENTITY-ROW 2.2.0 IS INSTALLED <empty string> [fold-entity-row.js:78:255](https://[redacted].duckdns.org:1337/hacsfiles/lovelace-fold-entity-row/fold-entity-row.js?hacstag=150781994220)
banner-card: 0.12.0 [banner-card.js:162:2393](https://[redacted].duckdns.org:1337/hacsfiles/banner-card/banner-card.js?hacstag=1867657040130)
TEMPLATE-ENTITY-ROW 1.3.2 IS INSTALLED <empty string> [template-entity-row.js:49:267](https://[redacted].duckdns.org:1337/hacsfiles/lovelace-template-entity-row/template-entity-row.js?hacstag=231674882132)
 QR-CODE-GENERATOR  v1.0.2 [qr-code-card.js:170:17952](https://[redacted].duckdns.org:1337/hacsfiles/lovelace-qr-code-card/qr-code-card.js?hacstag=449381321102)
vertical-stack-in-card
Version: 0.4.4 [vertical-stack-in-card.js:1:9](https://[redacted].duckdns.org:1337/hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js?hacstag=142051833044)
 MINI-GRAPH-CARD  0.11.0 [mini-graph-card-bundle.js:1:95970](https://[redacted].duckdns.org:1337/hacsfiles/mini-graph-card/mini-graph-card-bundle.js?hacstag=1512800620110)
  TEXT-DIVIDER-ROW  
  Version 1.4.1     [text-divider-row.js:187:2171](https://[redacted].duckdns.org:1337/hacsfiles/text-divider-row/text-divider-row.js?hacstag=179788256141)
LAYOUT-CARD 2.4.4 IS INSTALLED [layout-card.js:228:115](https://[redacted].duckdns.org:1337/hacsfiles/lovelace-layout-card/layout-card.js?hacstag=156434866244)
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
Fixed by #588
