### ISSUE TITLE
Unable to get browser id in custom card on cast device

### ISSUE THREAD

**Issue by ifuller1** [thomasloven/hass-browser_mod#610]
My Home Assistant version: 0.XX.X

**What I am doing:**

- Trying to read `"browser_mod-browser-id"` from local storage

**What I expected to happen:**

- I can get the i.d

**What happened instead:**

- The i.d is empty (it's there on other non cast targets)

**Minimal** steps to reproduce:

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```
            const browserModBrowserId = localStorage.getItem(
                "browser_mod-browser-id"
            );

```
blank output
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by ifuller1** [comment]
Maybe just a quick pointer for where to read the value from? I also trying the query params and it's not there either.

**Comment by thomasloven** [comment]
There is no LocalStorage on cast devices. That's why the special `CAST` browser exists.

Here's a way to see if you're on cast: https://github.com/thomasloven/hass-browser_mod/blob/master/js/plugin/browserID.ts#L41

Or you could read `window.browser_mod.browserID`. That's should always be present if Browser Mod is installed.

**Comment by ifuller1** [comment]
Thank you so much!

**Comment by ifuller1** [comment]
Sorry @thomasloven but "browser_mod" is never set on the cast device. I have the dashboard working across my browsers without issue but on the cast device, my card isn't able to query the browser_mod attribute. And since they dropped the chrome inspector support it's a little hard to work out what's going on. I can confirm the code is running (because I can see runtime errors on the card). I can also confirm I've been rebooting the cast device (nest hub max) to ensure a clear cache.

**Comment by ifuller1** [comment]
And if I look at the "CAST" media player it says it was unavailable some time ago. I'm not sure when or how it was available...

**Comment by ifuller1** [comment]
<img width="626" alt="Screenshot 2023-07-16 at 17 46 35" src="https://github.com/thomasloven/hass-browser_mod/assets/144812/9881f0b4-d0e0-448c-9349-ecdc82431b55">

Not sure if this helps.

I've used both the standard cast media / dashboard setting to send to nest hub max and also the `Google Cast: Show lovelace view` service.

**Comment by thomasloven** [comment]
I'll have to look into if there's been any changes to cast then. Will take a while.

**Comment by ifuller1** [comment]
Anything I can do to help? Anything else you'd like me to output on the window object? 

I had setup weinre because of the lack of debug support although I should probably try the cast SDK.
