### ISSUE TITLE
From the last update, more and more style options are broken, for the popup...

### ISSUE THREAD

**Issue by pickonedev** [thomasloven/hass-browser_mod#621]
Hi!

Till the last update, I had this popup (it is just a part of the complete popup)
```
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      dismissable: true
      style: |
        --popup-border-width: 1px;
        --popup-border-color: #013896;
        --popup-min-width: 450px;
        --popup-max-width: 450px;
        --popup-border-radius: 0px;
        --popup-background-color: rgba(15,15,36,1);
        --popup-padding-x: 5px;
        --popup-padding-y: 5px;
      content:
        type: horizontal-stack
        cards:
```
All the styles were ok, but now, with the new update, only these three are still working:
```
        --popup-min-width: 450px;
        --popup-max-width: 450px;
        --popup-border-radius: 0px;
```
Take a look at the screenshot
![image](https://github.com/thomasloven/hass-browser_mod/assets/34201387/1462f37e-f203-433f-863c-b833236c6419)

How can I change the background color, padding, border and any other style options, for the popup?

Thanks!

**Comment by tieskuh** [comment]
+1

**Comment by pejotigrek** [comment]
I thought I was the only one with "unknown" padding showing up on popups but wasn't sure what's causing those.
there's separate padding for header and for content - but it looks like can't be changed [as far as I tried with all I know]:

header padding: 12px
![image](https://github.com/thomasloven/hass-browser_mod/assets/10796588/7e24b5f8-d585-4fbf-b4da-db13411c7c10)

and content padding: 8px 8px 20px
![image](https://github.com/thomasloven/hass-browser_mod/assets/10796588/17cc7947-b255-4ce8-9741-c142db7795fd)

**Comment by pickonedev** [comment]
I have managed to do this:

![image](https://github.com/thomasloven/hass-browser_mod/assets/34201387/e156eb69-af38-42a6-a46a-96da45dbb287)

I made the tite dissapear and I have moved the close button at the bottom middle of the screen, and it has a short loop animation as blinking

I have used the standard style from the popup, like this
```
      style: |
        --popup-min-width: 900px;
        --popup-max-width: 900px;
        --popup-border-radius: 0px;
```
And card_mod like this:
```
      card_mod:
        style:
          ha-dialog$: |
            .mdc-dialog .mdc-dialog__surface{
              background-color: rgba(15,15,36,1) !important;
              border: 1px solid #013896;}
          ha-dialog-header$: |
            .header{position: absolute;
              width: 0px;
              height: 0px;
              }
            .header-title {display: none !important}
            .header-navigation-icon{position:fixed;
              height:50px !important;
              top:90%;
              left:50%;
              bottom:30%;
              transform: translateX(-50%);
              animation: ha-icon-button 1.0s linear infinite;
              border-radius:50px;
              z-index:9999 !important;
              color: #6cbaff;
              backdrop-filter: blur(5px);}
            @keyframes ha-icon-button {
              0% {box-shadow: 0 0 40px #6cbaff42;}
              50% {box-shadow: none;}
              100% {box-shadow: 0 0 40px #6cbaff42;}
            }
```
The similar style helps me for the non fullscreen popups, to have a blur behind, like this:

![image](https://github.com/thomasloven/hass-browser_mod/assets/34201387/ae8e7172-4cb1-45ee-9c21-c6897dd88bb9)

with this:

```
      card_mod:
        style:
          ha-dialog$: |
            div.mdc-dialog__scrim {
              backdrop-filter: blur(15px) !important;
              -webkit-backdrop-filter: blur(15px) !important;
              border-radius: 0px;
            }
          ha-dialog: |
            .content{
              border: 1px solid #013896 !important;
              background-color: rgba(15,15,36,1);
              padding-top: 10px;
              padding-left: 10px;
              padding-right: 10px;
            }
```

**Comment by Sian-Lee-SA** [comment]
had to change `--popup-background-color: transparent;` to `--mdc-theme-surface: transparent;`... A chore I wish wasn't necessary... For the borders, they seem to be inconsistent and sometimes show and sometimes doesn't cant even find the styles for them with code inspector.
