### ISSUE TITLE
Browser Mod not available under services

### ISSUE THREAD

**Issue by Drewskieza** [thomasloven/hass-browser_mod#622]
My Home Assistant version: 2023.8.1

**What I am doing:**
Developer Toos = > Services => Type Browser

**What I expected to happen:**
Browse Mod options to display

**What happened instead:**
Does not find the options

**Minimal** steps to reproduce:
Developer Toos = > Services => Type Browser

```yaml
# The least amount of code or steps possible to reproduce my error

# Put your code/steps here
```
service: browser_mod.more_info
data:
  entity: light.plug10_lounge_light

**Error messages from the browser console:**

```
// Select everything from the browser console and copy it
developer-tools-service.ts:361 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'more_info')
    at i.value (developer-tools-service.ts:361:42)
    at F.handleEvent (lit-html.ts:2018:29)
value @ developer-tools-service.ts:361
handleEvent @ lit-html.ts:2018
// Paste it here
```

---

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by Destarianon** [comment]
I am running into the same issue. Browser_mod does not appear to be available as a service and I cannot call more_info.

Also running 2023.8.1 and Browser_mod version 2.3.0

**Comment by Destarianon** [comment]
Figured this one out, you need to go to the normal Integrations page and add browser_mod there as well. It will appear in the sidebar and you can edit your personal settings to hide it, but that will make it available to call.
