### ISSUE TITLE
Feature request: Ability to control fully kiosk without using Lovelace.

### ISSUE THREAD

**Issue by Madseason41** [thomasloven/hass-browser_mod#64]
I currently use fully kiosk to display an appdaemon page. Is there any way to add (if it doesn’t exist already), the ability to control fully kiosk without having to rely on Lovelace?

You could possibly use the clientId of Fully Kiosk as the identifier?

Also, the ability to change the fully kiosk url would be great. This function would actually change what page fully kiosk is actively viewing. (i.e. some trigger would allow me to call a browser_mod service to load a fully kiosk url, that happens to not be a homeassistant/ lovelace page).

**Comment by thomasloven** [comment]
Fully Kiosk Browser and Lockdown has a REST based API. Use that.
