### ISSUE TITLE
Request: Ability to make service call before showing pop-up card

### ISSUE THREAD

**Issue by mdegat01** [thomasloven/hass-browser_mod#65]
I'm not seeing a way to submit a feature request so I'll submit this as an issue but its definitely an enhancement request rather then a bug.

I was a previous user of the now deprecated plug-in [popup card](https://github.com/thomasloven/lovelace-popup-card) which now redirects to this one. Unfortunately I'm not going to be able to convert over at this time though because I had tweaked the functionality of popup card with a small enhancement in my local copy - the ability to make a service call before showing the popup card.

My use case is this:  I have a tab in my UI which is just a map card showing all the people in my household.  Anytime someone clicks on a person the popup card shows the streetview image of where they are, the place name for where they are, the distance from home and a time estimate for how long it takes to get home from there driving.

Now in theory this is pretty easy and shouldn't require anything custom.  I have a camera per person with its image set to the google streetview URL templatized with lat/long values and a google time travel sensor per person for the other stuff. Those two source the entire popup, it's literally just a markdown card showing values from those two in templates.

The problem is the APIs that those Google Maps APIs cost money. If I was hitting the distance matrix API and the streetview image API literally anytime any person in my house's lat/long changed that would add up. And it would be pretty wasteful because while its important to me that the popup is accurate when someone clicks to show it most of the time I'm not looking at this UI.  I wouldn't want to pay to make API calls constantly when I only need accurate information once in a while.

So instead I added the ability to make a service call before showing the UI to the OOTB popup card. In my UI when I customize the popup card I can also add a configuration option called "prepare". In it you can configure a service call and that service call is made before it begins showing the popup card UI. For me this allowed me to control it so the camera and the time travel sensor only update when the popup card shows and not at any other time so I don't make more API calls then I need.

Now unfortunately I added this capability to popup card.  I had intended to eventually submit it as a PR but never got around to doing testing and hardening to make me feel comfortable publishing it. And that was to popup card which is now deprecated and way less complicated then Browser Mod.

I'm sure eventually I will find some time and figure out how to add this capability here so I can switch. But I figured I would post this to see if there's other interest in this capability as there are plenty of others that are far more capable then me at making these changes.

**Comment by apop880** [comment]
If you're willing to use buttons below the map card or something like that, you could have a button that calls a script to first execute your service call and then display the popup. That would at least get you close to what you've already got in the interim.
