### ISSUE TITLE
Unable to displaying a popup via a script in the latest version browser_mod and cardmod

### ISSUE THREAD

**Issue by horacecar** [thomasloven/hass-browser_mod#69]
> Please, try `deviceID: this` in lovelace.

After update to HA 0.106.5 and latest version of browser_mod , even deviceID: this is not working anymore, but if it Specify give it a deviceID: c9f5fd48-51c9f5fd , then i works

_Originally posted by @horacecar in https://github.com/thomasloven/hass-browser_mod/issues/25#issuecomment-600000091_

**Comment by thomasloven** [comment]
Please try release 24.

**Comment by horacecar** [comment]
@thomasloven 

thank you so much;) fixed already.
