### ISSUE TITLE
Popup closing

### ISSUE THREAD

**Issue by Shanghaiman** [thomasloven/hass-browser_mod#7]
Love this new browser_mod.
finally got it working (still issiue with Device id to name).
when you have few popups opening in the browser, when you press to close one, they are all closing, can that be changed?
also no way to scroll down. 
so  in case we are using it for popup of camera picture that shows picture if someone is ringing the bell, in case i have'nt check immidiate then i cant scroll down when have more then 4 pictures sent to me

**Comment by thomasloven** [comment]
It's not supposed to be possible to open more than one popup at a time. If it is, that's a bug and I'll fix it.

You can execute `close-popup` before opening a popup to make sure the last one is shown.

Scrollable popups are a work in progress. It's available in the latest version on github, but not released to HACS yet.
