### ISSUE TITLE
Created Fork with Pull Request Fixes

### ISSUE THREAD

**Issue by KyleStilkey** [thomasloven/hass-browser_mod#716]
It seems like support for this has probably ended sadly, I use this for my Home Assistant as it has some very useful features. I have taken all the pull requests and built a fork with the fixes included. I am no developer but any pull requests put in I will pull into my fork until I hoep @thomasloven decides to fix this integration.

https://github.com/KyleStilkey/hass-browser_mod

If you want to use the forked version, just add this as a custom repository in your HACS, remove the old and install this version. This fork will just include any fixes the community makes in hopes we see an official fix some day.

**Comment by KJThaDon** [comment]
> It seems like support for this has probably ended sadly, I use this for my Home Assistant as it has some very useful features. I have taken all the pull requests and built a fork with the fixes included. I am no developer but any pull requests put in I will pull into my fork until I hoep @thomasloven decides to fix this integration.
> 
> https://github.com/KyleStilkey/hass-browser_mod
> 
> If you want to use the forked version, just add this as a custom repository in your HACS, remove the old and install this version. This fork will just include any fixes the community makes in hopes we see an official fix some day.

Thank you, however it seems pop up cards are still broken?

**Comment by KyleStilkey** [comment]
Correct until someone fixes it, I've just pulled in the fixes in the PR nothing more. I'm no developer and if someone releases a fix, I'll pull it.

**Comment by kvanbiesen** [comment]
I did a push for a fix. 

its also in my repo also.

Carefull, needs a hard refresh on the cache. (In chrome, press f12, then with the mouse, hold left click on the refresh button and select "empty cache and hard reload". On other browsers no idea, app also wait untill it refreshes cache

**Comment by KyleStilkey** [comment]
> I did a push for a fix for the settings page
> 
> its also in my repo also.
> 
> Carefull, needs a hard refresh on the cache. (In chrome, press f12, then with the mouse, hold left click on the refresh button and select "empty cache and hard reload". On other browsers no idea, app also wait untill it refreshes cache
> 
> //edit, didnt test it for the popup card, but i dont use those so cant really test unless someone has an example code

Appreciate it, I'll pull it here in the morning and do some testing see how it goes, I use the popups so I'll test that out.

**Comment by kvanbiesen** [comment]
Delete current for, add his fork. (Or mine) I am using mine and I can
install it...

**Comment by lbouriez** [comment]
Neither yours or his works, I am geting the same error.
![image](https://github.com/thomasloven/hass-browser_mod/assets/4749766/4651b2a5-2560-46c6-aeca-dcd679f116ca)

**Comment by kvanbiesen** [comment]
You gotta hard refresh the cash. Popups aren't fixed yet, but workarounds
are posted already

**Comment by kvanbiesen** [comment]
You gotta select integration and not Lovelace with categorie

**Comment by lbouriez** [comment]
Thanks...

**Comment by KyleStilkey** [comment]
@kvanbiesen I pushed your PR in my fork, sorry have a kid along the way so this week was very busy for us. Hopefully we see a fix for the popups without needing a work around.

**Comment by hmmbob** [comment]
You might want to have a look at fixes in #725, #726 and #727

**Comment by kvanbiesen** [comment]
added to mine. Still looking in the borked pop-ups but man this is a huge thing (expecially cause js is not my forte :D )

**Comment by KyleStilkey** [comment]
> You might want to have a look at fixes in #725 and #727

Thanks, they've been pushed into my fork.

**Comment by LDprg** [comment]
@KyleStilkey Why did you disable issues? it would be great if they re enabled.

**Comment by KyleStilkey** [comment]
> @KyleStilkey Why did you disable issues? it would be great if they re enabled.

Because they need to be put here, I only put up fixes in the Pull Request for now, I am hoping that @thomasloven ends up fixing these, I am no dev and putting issues in my fork will not solve anything.

**Comment by srLinux** [comment]
omg, you saved my life... thank you!

**Comment by thomasloven** [comment]
Thanks for your dedication and help!
I've had a bit of family health issues this spring, so a lot of things have had to be put on hold.

I've tested and merged all open PRs but one into release 2.3.1.
That should keep things going for a bit.

**Comment by KyleStilkey** [comment]
Thank you for this, much appreciated and hope all is well.
