### ISSUE TITLE
calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop

### ISSUE THREAD

**Issue by micium** [thomasloven/hass-browser_mod#717]
My Home Assistant version: 2024.7.0
Registratore: homeassistant.helpers.frame
Fonte: helpers/frame.py:184
Prima occorrenza: 10:12:43 (9 occorrenze)
Ultima registrazione: 10:12:58

Detected that custom integration 'browser_mod' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/browser_mod.js", "/config/custom_components/browser_mod/browser_mod.js", True)])`; This function will be removed in 2025.7 at custom_components/browser_mod/mod_view.py, line 13: hass.http.register_static_path(, please report it to the author of the 'browser_mod' custom integration
Detected that custom integration 'browser_mod' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/browser_mod_panel.js", "/config/custom_components/browser_mod/browser_mod_panel.js", True)])`; This function will be removed in 2025.7 at custom_components/browser_mod/mod_view.py, line 20: hass.http.register_static_path(, please report it to the author of the 'browser_mod' custom integration

from HA 2024.7.0

**Comment by Spegeli** [comment]
Its alrdy fixed in the master branche: https://github.com/thomasloven/hass-browser_mod/commit/91741384df2dd2271c459e3c992bc04c814cee52
but not pushed to a release.
