### ISSUE TITLE
pop-up mod for input select does not show all the time

### ISSUE THREAD

**Issue by iptvcld** [thomasloven/hass-browser_mod#72]
pop-up mod for input select does not show all the time
- when i select the pop-up to come up and display a input select drop down, it sometimes shows blank but if i just try again it will work.  Only happening with input selects

**Comment by ghostist** [comment]
same issue. 
I just upgrade hass from 0.105 to 0.108 and the pop-up card must be selected twice so that shown input select.

**Comment by thomasloven** [comment]
Please open a new issue if this is still a problem with the latest version of browser_mod.
