### ISSUE TITLE
How do I reset all settings?

### ISSUE THREAD

**Issue by JacobDB** [thomasloven/hass-browser_mod#729]
When I first set up Home Assistant earlier this year, I couldn't figure out how to edit the sidebar order. I solved this by installing browser_mod and using the sidebar editor built in. Now though, I finally discovered how to edit the sidebar properly, so I want to disable browser_mod's sidebar order to use the native feature.

Problem is, I can't figure out how to do that. It seems like browser_mod might be pretty broken after the latest Home Assistant update; when I go to the page, things don't load right and my PC's fans spin up (seems like an infinite loop with some JS issue from what I'm seeing in the console).

If I remove browser_mod, it fixes the issue, but I still use other features of browser_mod so I don't want to remove it complete, I just want to reset the sidebar order.

Is this possible? I've been poking around my server via terminal, but haven't seen anything that looked relevant...

**Comment by LightMoon** [comment]
I am facing the same issue.

**Comment by LightMoon** [comment]
Found the fix - https://github.com/thomasloven/hass-browser_mod/issues/718
