### ISSUE TITLE
more-info popup not working for non custom cards.

### ISSUE THREAD

**Issue by narrcom** [thomasloven/hass-browser_mod#73]
after updating to version 0.24 and also home assistant to v1.07 my popup_cards for any internal card type repors "custom element dosen't exist: hui-{cart type}"...

custom_cards:
  binary_sensor.front_door_camera:
    title: Front Door
    card:
      type: picture-entity
      entity: binary_sensor.front_door_camera
      camera_image: camera.front_door
      camera_view: live
      show_name: false
      show_state: false
    style:
      width: 75%
      pointer-events: none

**Comment by paparapapapapa** [comment]
idem. I also tried `lovelace-card-preloader` hack but so far it's working only on iOS 13 iPhone and Android 9 tablet, no luck on macOS 10.14

**Comment by narrcom** [comment]
seems to have fixed itsself after i added a new lovelace dashboard, i suspect this issue has something to do with the new resource handling in 1.07
