### ISSUE TITLE
 Pop up dismiss action not executing service

### ISSUE THREAD

**Issue by myevit** [thomasloven/hass-browser_mod#744]
Trying to run a service call on pop dismissal but it seems like it just not executing.
<img width="1016" alt="Screenshot 2024-08-29 at 10 06 01 PM" src="https://github.com/user-attachments/assets/cbc5715f-61bb-45b3-b9bc-cd0abecbb531">

**Comment by lisz8** [comment]
Maybe try "data" instead of "target". I have this, and it works:
```
service: script.turn_on
data:
  entity_id: script.bieganie_nowy_bieg_anulowanie
```

**Comment by myevit** [comment]
Yes! That's it!
Thank you!
