### ISSUE TITLE
media_player gets invalid HTTP method

### ISSUE THREAD

**Issue by kkellner** [thomasloven/hass-browser_mod#75]
When using the media_player to play `text to speak`, nothing happens but the log files shows the following: 

```
Log Details (ERROR)
Logger: aiohttp.server
Source: /usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py:355
First occurred: 1:10:10 AM (1 occurrences)
Last logged: 1:10:10 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
```

This is the attributes of the media_player.  (real DNS name replace with HA_IP below)  I have copied the http address from `media_content_id` and manually opened in browser and the mp3 is accessible and plays correctly.

```
volume_level: 0.66
is_volume_muted: false
media_content_id: http://HA_IP:8123/api/tts_proxy/ba6a9c00c87e2aa5f02c2085214383fe256529ba_en_-_google_translate.mp3
type: browser_mod
deviceID: b5b73691-86c87b33
supported_features: 21005
```

Setup:

browser_mod version:  24

Key | Value
-- | --
arch | x86_64
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 4.19.107
python_version | 3.7.7
version | 0.107.5
virtualenv | false

Thoughts?

**Comment by thomasloven** [comment]
This issue has grown too old. If this is still a problem, please open a new issue.
