### ISSUE TITLE
deviceid debug query freezes the ipad app

### ISSUE THREAD

**Issue by ThePierce** [thomasloven/hass-browser_mod#76]
Is there any other way to retreive the deviceid? On every other device it shows an pop up but on my ipad it doesnt show and kills the app. 

Reinstalled the ipad and only installed home assistant but it doesnt solve it.

**Comment by ThePierce** [comment]
I really need to learn to read... found my deviceid. However, still good to know that the ipad freezes on that command.

**Comment by thomasloven** [comment]
Please try with release 25

**Comment by ThePierce** [comment]
Very late reaction, my apologies for that. But unfortunatly that didn;t solve the crash problem. However, it is possible via the browser-player card method.
