### ISSUE TITLE
Battery Sensor becomes unavailable often.

### ISSUE THREAD

**Issue by fourtrax01** [thomasloven/hass-browser_mod#77]
I use Fully kiosk and when I used to use the old fully kiosk method that was deprecated for controlling and knowing the battery charge state it was flawless but now after switching to browser_mod the tablets battery sensors become unavailable almost daily and are going dead because my charging automations no longer work. Is there something I can do to fix this?

**Comment by SamMousa** [comment]
You refer to the old method, is that the REST API? Because afaik that's not deprecated, it is just now how this component does it.

You could use that REST API to ping the tablet whenever the sensor becomes unavailable..
