### ISSUE TITLE
Strange behavior - Popups and Picture Element Card

### ISSUE THREAD

**Issue by Resinchem** [thomasloven/hass-browser_mod#78]
Here's a little info on what I'm seeing with the popup in HA 0.107 and browser_mod 25.  If I restart HA or even just reload the browser, the popup card containing a picture elements shows:
![image](https://user-images.githubusercontent.com/55962781/78163221-13e37e00-7416-11ea-8a8f-d0343171e6c9.png)

However, if I simply click over to a different Lovelace tab that has this same exact picture elements as a standalone card, I can then return to the original tab and the popup works perfectly:
![image](https://user-images.githubusercontent.com/55962781/78163421-5d33cd80-7416-11ea-876b-6ab05caf41e8.png)

This works consistently, but has to be repeated for each device.  Simply displaying picture element card on its own tab as a standalone card fixes the popup card on that device, but not on others.  The fix stays until that particular device reloads the browser/app or until HA is restarted.  Tested this process on computer, tablet and Android device and it is the same on all.  I can get by with the way it works, but I only provide this info to see if it helps anyone with troubleshooting.

**Comment by OptimusGREEN** [comment]
yes im getting the same issue with picture-entity card.

**Comment by Fredfishface** [comment]
I'm experiencing the same problem with the built in alarm card. I have experienced it is previously with picture elements. If an alarm card exists within the same view or if you go to a view with an alarm card and then back to the view with the browser mod alarm card popup, the problem goes away.

**Comment by ksheyman** [comment]
Having the same issue. Red screen with 'custom element doest exist: hui-picture-entity-card. when I copy the config into a regular lovelace card it works fine. but doesn't work as a popup. I changed nothing and i'm not sure which release this started with.

**Comment by ronsum232** [comment]
Experiencing exact issue as described by OP. Consistently fails to load a popup that contains a card... until that card type is loaded/viewed elsewhere.

**Comment by thomasloven** [comment]
Please open a new issue if this is still a problem with the latest version of browser_mod.
