### ISSUE TITLE
I setup Duckdns and ssl now browsermod doesn't work

### ISSUE THREAD

**Issue by teankum** [thomasloven/hass-browser_mod#81]
I set up duckdns yesterday and ssl now the browser mod doesn't work. I have port 443 forwarding to 8123. would that cause the issue?

**Comment by KTibow** [comment]
I don't know. What does your browser show? Press F12 to open Devtools, and then choose the console tab. Take a screenshot.

**Comment by thomasloven** [comment]
If you use a different URL to access your frontend than before, you will have a new deviceID.
