### ISSUE TITLE
How is the sensor's last_seen updated?

### ISSUE THREAD

**Issue by carlos-sarmiento** [thomasloven/hass-browser_mod#82]
I'm trying to understand how is the last_seen property updated and what triggers it. I'm thinking of building some automation's to restart several dashboards if the browser hosting them crashes (which happens every once in a while). Was thinking of relying on the last_seen property to restart the browser remotely if it has been a while since last_seen. But I'm testing right now with one and I don't see it updating. 

Are my expectations of last_seen correct? Or should I approach this a different way?

**Comment by KTibow** [comment]
Well this behavior differs. I edited my source to send the camera more often, and that is repeatedly updating. I think whenever an attribute updates, it sends a websocket command, which also updates `last_seen`.

**Comment by thomasloven** [comment]
In the next version (1.2.0), the `last_seen` property of the `sensor` will be updated every 10 seconds as a form of ping.
