### ISSUE TITLE
Query: set theme on popup for more-info view

### ISSUE THREAD

**Issue by Alfiegerner** [thomasloven/hass-browser_mod#85]
Hi, 

May have missed the answer , but does anyone know if it's possible to set the theme for a popup replacing more-info?

Currently getting opaque black for title bar - I've tried ` theme: ios-dark-mode-dark-green' under card and entity name but can't get it to bring in a theme colour for the title bar.

If it makes a difference this using it in a[ floorplan](https://github.com/pkozul/lovelace-floorplan) which may be considered non-lovelace, maybe?

Thanks.

**Comment by Dino-Tech** [comment]
You can style the popup itself with pretty much anything you want, including the top/title bar.

**Comment by Alfiegerner** [comment]
That'll do, thanks.
