### ISSUE TITLE
Android app popup back button behaviour

### ISSUE THREAD

**Issue by Zero545** [thomasloven/hass-browser_mod#87]
Hello,

I am using the official Android home assistant app. I noticed that normal more-info dialogs close on back-button, but browser-mod popups do not. Instead the app closes or similar. Correct back button behaviour is very important in Android, so I wanted to suggest to adjust the behaviour to be the same as for the more-info dialogs, if possible.

Hass.io Version: 0.108.8
Browser Mod: 25

**Comment by Xaos1990** [comment]
Have you found a workaround or solution yet?

**Comment by Zero545** [comment]
No, unfortunately not...

**Comment by larena1** [comment]
Having the exact same issue. On devices with big screen the small X in the top left corner is hard to reach and using the back button will just close the app, which is pretty annoying.

Is it possible to fix this, @thomasloven?

**Comment by KTibow** [comment]
See https://stackoverflow.com/a/45816291/12243248

**Comment by KTibow** [comment]
Can everyone make sure this is still an issue?

**Comment by Xaos1990** [comment]
For me this issue has been solved, thanks!  
Android version 10.0.9 - on OnePlus 7 pro

**Comment by KTibow** [comment]
@Zero545 please consider closing if this has been solved.

**Comment by Zero545** [comment]
Thank you. The issue also has been solved for me, so I am now closing this issue.
