### ISSUE TITLE
Setup of browser_mod is taking over 10 seconds. (20min+ for me)

### ISSUE THREAD

**Issue by ttaidapos** [thomasloven/hass-browser_mod#89]
Seems to be anywhere from 10minutes to 25minutes+ by the time it loads.  Installed via hacs, RPi4(4gb), raspbian.

Anyone else experiencing this?

![image](https://user-images.githubusercontent.com/27898709/80616393-796f5e00-8a06-11ea-9d5f-fb8bedcb8be6.png)

**Comment by DeadEnded** [comment]
I just installed and restarted HA - I think I am possibly having the same issue.
After a restart, I do not see any devices created by the browser_mod component.
I restarted again, and checked services, and I do see the services - just no devices.

Maybe I missed something though....

**Comment by ttaidapos** [comment]
> I just installed and restarted HA - I think I am possibly having the same issue.
> After a restart, I do not see any devices created by the browser_mod component.
> I restarted again, and checked services, and I do see the services - just no devices.
> 
> Maybe I missed something though....
> 
> nope.... after writing this message and doing some other tasks, the devices are now showing up. Just took a long time I guess.

I has gotten better with recent updates to browser_mod but it's very delayed.  Withing 5 to 10min it's usually good to go.

**Comment by bbogdanmircea** [comment]
Hello, I installed browser_mod with HACS, having this error and all components using browser_mod are not doing anything.
Any idea how to debug this and would could be the cause?

**Comment by thomasloven** [comment]
If the devices are not showing up after a restart, refresh your browsers.
