### ISSUE TITLE
Why does Batter Level only get reported when on Fully Kiosk Browser

### ISSUE THREAD

**Issue by JonathanTreffler** [thomasloven/hass-browser_mod#91]
There is a HTML5 API for getting the battery state. It doesn't work on all browsers, but on most.
Is there any reason, why the battery level currently doesn't get reported on devices not using Fully Kiosk Browser ?

**Comment by TessyPowder** [comment]
https://whatwebcando.today/battery-status.html

**Comment by SamMousa** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Battery_Status_API

Actually that API is deprecated.. :(

**Comment by JonathanTreffler** [comment]
:( That is very unfortunate

**Comment by KTibow** [comment]
But it still works.

**Comment by JonathanTreffler** [comment]
> But it still works.

Its probably not worth implementing, because it will get removed at some point

**Comment by KTibow** [comment]
It's been there for a while. If the browser supports it, add the attribute. If it doesn't, don't. That way, it works in old browsers without it, browsers with it, and browsers that deprecated it.

**Comment by thomasloven** [comment]
This has been added in release 1.2.0 for devices where available (e.g. not iOS).
