### ISSUE TITLE
0.110.0b2 Light + MediaPlayerDevice Warning

### ISSUE THREAD

**Issue by mynameisdaniel32** [thomasloven/hass-browser_mod#94]
Getting the below on Home Assistant startup since updating to the latest beta.

`2020-05-16 11:49:38 WARNING (MainThread) [homeassistant.components.media_player] MediaPlayerDevice is deprecated, modify BrowserModPlayer to extend MediaPlayerEntity
`

**Comment by mynameisdaniel32** [comment]
Just spotted it's giving a light warning too

`2020-05-16 11:49:44 WARNING (MainThread) [homeassistant.components.light] Light is deprecated, modify BrowserModLight to extend LightEntity`

**Comment by sparment** [comment]
I'm seeing this as well since updating to HA 0.110.0 this morning.

**Comment by avdeevsv91** [comment]
I fixed it https://github.com/thomasloven/hass-browser_mod/pull/99

**Comment by sparment** [comment]
Thanks - that did the trick for me!

**Comment by iptvcld** [comment]
i dont see any updates in HACS for this

**Comment by thomasloven** [comment]
Fixed in release 26
