### ISSUE TITLE
Light is deprecated, modify BrowserModLight

### ISSUE THREAD

**Issue by iptvcld** [thomasloven/hass-browser_mod#97]
Logger: homeassistant.components.light
Source: components/light/__init__.py:451
Integration: Light (documentation, issues)
First occurred: 10:37:15 PM (1 occurrences)
Last logged: 10:37:15 PM

Light is deprecated, modify BrowserModLight to extend LightEntity
Connection lost. Reconnecting…

**Comment by avdeevsv91** [comment]
Duplicate https://github.com/thomasloven/hass-browser_mod/issues/97
